package com.sunny.paintfactory.purchase;

import com.sunny.paintfactory.common.ApiResponse;
import com.sunny.paintfactory.common.DocumentSort;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

@RestController
@RequestMapping("/api/v1/purchases")
public class PurchaseController {
    private final JdbcTemplate jdbc;
    public PurchaseController(JdbcTemplate jdbc){this.jdbc=jdbc;}

    @GetMapping("/orders")
    public ApiResponse<List<Map<String,Object>>> orders(@RequestParam(defaultValue="") String keyword,@RequestParam(defaultValue="") String dateFrom,@RequestParam(defaultValue="") String dateTo,@RequestParam(defaultValue="") String printStatus,@RequestParam(defaultValue="date") String sortBy,@RequestParam(defaultValue="asc") String sortDirection){
        String like="%"+keyword.trim()+"%";
        String sql="SELECT o.id,o.order_no,o.order_date,o.supplier_code_snapshot,o.supplier_name_snapshot,o.total_amount,o.status,o.version,o.created_at,u.display_name,o.completed_at,o.printed_at,o.print_count "+
                "FROM purchase_order o JOIN sys_user u ON u.id=o.created_by WHERE (o.order_no LIKE ? OR o.supplier_code_snapshot LIKE ? OR o.supplier_name_snapshot LIKE ?) AND (?='' OR o.order_date>=CAST(? AS DATE)) AND (?='' OR o.order_date<=CAST(? AS DATE)) AND (?='' OR (?='PRINTED' AND o.printed_at IS NOT NULL) OR (?='UNPRINTED' AND o.printed_at IS NULL)) ORDER BY "+DocumentSort.sql(sortBy,sortDirection,"o.order_date","o.order_no","o.id")+" LIMIT 200";
        return ApiResponse.success(jdbc.query(sql,(rs,n)->{
            List<Map<String,Object>> its=orderItems(rs.getLong(1)); Metrics totals=totals(its);
            Map<String,Object> draft=draftReceipt(rs.getLong(1),null);
            String status=rs.getString(7),fulfillment="VOIDED".equals(status)?"VOIDED":rs.getTimestamp(11)!=null?"CLOSED":allComplete(its)?"COMPLETED":totals.net().signum()!=0?"PARTIAL":"ORDERED";
            return map("id",rs.getLong(1),"orderNo",rs.getString(2),"orderDate",rs.getDate(3).toLocalDate(),"supplierCode",rs.getString(4),"supplierName",rs.getString(5),"totalAmount",rs.getBigDecimal(6),"status",status,"version",rs.getInt(8),"createdAt",rs.getTimestamp(9).toLocalDateTime(),"createdByName",rs.getString(10),"completedAt",rs.getTimestamp(11)==null?null:rs.getTimestamp(11).toLocalDateTime(),"printedAt",rs.getTimestamp(12)==null?null:rs.getTimestamp(12).toLocalDateTime(),"printCount",rs.getInt(13),"orderedQuantity",totals.ordered(),"receivedQuantity",totals.net(),"remainingQuantity",totals.remaining(),"overReceivedQuantity",totals.over(),"fulfillmentStatus",fulfillment,"draftReceiptId",draft==null?null:draft.get("id"),"draftReceiptNo",draft==null?null:draft.get("receiptNo"));
        },like,like,like,dateFrom,dateFrom,dateTo,dateTo,printStatus,printStatus,printStatus));
    }

    @GetMapping("/orders/{id}")
    public ApiResponse<Map<String,Object>> order(@PathVariable long id){
        var rows=jdbc.query("SELECT o.id,o.order_no,o.order_date,o.supplier_id,o.supplier_code_snapshot,o.supplier_name_snapshot,COALESCE(o.supplier_phone_snapshot,''),o.expected_delivery_date,COALESCE(o.delivery_location,''),o.total_amount,o.status,COALESCE(o.remark,''),o.version,o.created_at,o.updated_at,o.completed_at,COALESCE(o.completion_reason,''),cu.display_name,cr.display_name,o.printed_at,o.print_count,pu.display_name FROM purchase_order o LEFT JOIN sys_user cu ON cu.id=o.completed_by LEFT JOIN sys_user cr ON cr.id=o.created_by LEFT JOIN sys_user pu ON pu.id=o.printed_by WHERE o.id=?",(rs,n)->map("id",rs.getLong(1),"orderNo",rs.getString(2),"orderDate",rs.getDate(3).toLocalDate(),"supplierId",rs.getLong(4),"supplierCode",rs.getString(5),"supplierName",rs.getString(6),"supplierPhone",rs.getString(7),"expectedDeliveryDate",rs.getDate(8)==null?null:rs.getDate(8).toLocalDate(),"deliveryLocation",rs.getString(9),"totalAmount",rs.getBigDecimal(10),"status",rs.getString(11),"remark",rs.getString(12),"version",rs.getInt(13),"createdAt",rs.getTimestamp(14).toLocalDateTime(),"updatedAt",rs.getTimestamp(15).toLocalDateTime(),"completedAt",rs.getTimestamp(16)==null?null:rs.getTimestamp(16).toLocalDateTime(),"completionReason",rs.getString(17),"completedByName",rs.getString(18),"createdByName",rs.getString(19),"printedAt",rs.getTimestamp(20)==null?null:rs.getTimestamp(20).toLocalDateTime(),"printCount",rs.getInt(21),"printedByName",rs.getString(22)),id);
        if(rows.isEmpty())throw notFound("Purchase order not found");
        Map<String,Object> result=new LinkedHashMap<>(rows.get(0));List<Map<String,Object>> its=orderItems(id);Metrics t=totals(its);String status=(String)result.get("status");
        Map<String,Object> draft=draftReceipt(id,null);
        result.put("items",its);result.put("orderedQuantity",t.ordered());result.put("receivedQuantity",t.net());result.put("pendingReceiptQuantity",pendingReceiptQuantity(id));result.put("remainingQuantity",t.remaining());result.put("overReceivedQuantity",t.over());result.put("fulfillmentStatus","VOIDED".equals(status)?"VOIDED":result.get("completedAt")!=null?"CLOSED":allComplete(its)?"COMPLETED":t.net().signum()!=0?"PARTIAL":"ORDERED");result.put("draftReceiptId",draft==null?null:draft.get("id"));result.put("draftReceiptNo",draft==null?null:draft.get("receiptNo"));
        return ApiResponse.success(result);
    }

    @PostMapping("/orders") @Transactional
    public ApiResponse<Map<String,Object>> createOrder(@Valid @RequestBody OrderRequest r,Authentication auth){
        Supplier s=supplier(r.supplierId());long uid=userId(auth);LocalDate date=r.orderDate()==null?LocalDate.now():r.orderDate();Prepared p=prepareOrder(r.items());String no=nextNo("PURCHASE_ORDER","CG",date);LocalDateTime now=LocalDateTime.now();
        jdbc.update("INSERT INTO purchase_order(order_no,order_date,supplier_id,supplier_code_snapshot,supplier_name_snapshot,supplier_phone_snapshot,expected_delivery_date,delivery_location,total_amount,status,remark,version,created_by,created_at,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'DRAFT',?,0,?,?,?,?)",no,date,s.id(),s.code(),s.name(),s.phone(),r.expectedDeliveryDate(),r.deliveryLocation(),p.total(),r.remark(),uid,now,uid,now);
        long id=Objects.requireNonNull(jdbc.queryForObject("SELECT id FROM purchase_order WHERE order_no=?",Long.class,no));insertOrderItems(id,p.items());return ApiResponse.success(map("id",id,"orderNo",no,"totalAmount",p.total()));
    }

    @PutMapping("/orders/{id}") @Transactional
    public ApiResponse<Map<String,Object>> updateOrder(@PathVariable long id,@Valid @RequestBody OrderUpdateRequest r,Authentication auth){
        var current=jdbc.query("SELECT status,version,printed_at,completed_at FROM purchase_order WHERE id=? FOR UPDATE",(rs,n)->new Object[]{rs.getString(1),rs.getInt(2),rs.getTimestamp(3),rs.getTimestamp(4)},id);if(current.isEmpty())throw notFound("Purchase order not found");Object[] order=current.get(0);if(!"DRAFT".equals(order[0])||order[3]!=null)throw conflict("The purchase order is completed or voided and cannot be edited");if(order[2]!=null)throw conflict("A printed purchase order cannot be edited");if(!Objects.equals(order[1],r.version()))throw conflict("Purchase order was modified by another user; refresh and try again");Integer receipts=jdbc.queryForObject("SELECT COUNT(*) FROM purchase_receipt WHERE purchase_order_id=? AND status<>'VOIDED'",Integer.class,id);if(receipts!=null&&receipts>0)throw conflict("A purchase order with receipts cannot be edited");
        Supplier s=supplier(r.supplierId());Prepared p=prepareOrder(r.items());long uid=userId(auth);LocalDateTime now=LocalDateTime.now();int changed=jdbc.update("UPDATE purchase_order SET order_date=?,supplier_id=?,supplier_code_snapshot=?,supplier_name_snapshot=?,supplier_phone_snapshot=?,expected_delivery_date=?,delivery_location=?,total_amount=?,remark=?,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND printed_at IS NULL AND completed_at IS NULL AND version=?",r.orderDate()==null?LocalDate.now():r.orderDate(),s.id(),s.code(),s.name(),s.phone(),r.expectedDeliveryDate(),r.deliveryLocation(),p.total(),r.remark(),uid,now,id,r.version());if(changed!=1)throw conflict("Purchase-order status has changed; refresh and try again");jdbc.update("DELETE FROM purchase_order_item WHERE purchase_order_id=?",id);insertOrderItems(id,p.items());return ApiResponse.success(map("id",id,"totalAmount",p.total(),"version",r.version()+1));
    }

    @PostMapping("/orders/{id}/void") @Transactional
    public ApiResponse<Void> voidOrder(@PathVariable long id,@RequestBody VersionReason r,Authentication auth){Integer printed=jdbc.queryForObject("SELECT COUNT(*) FROM purchase_order WHERE id=? AND printed_at IS NOT NULL",Integer.class,id);if(printed!=null&&printed>0)throw conflict("A printed purchase order cannot be changed");Integer count=jdbc.queryForObject("SELECT COUNT(*) FROM purchase_receipt WHERE purchase_order_id=? AND status<>'VOIDED'",Integer.class,id);if(count!=null&&count>0)throw conflict("A purchase order with receipts cannot be voided");LocalDateTime now=LocalDateTime.now();long uid=userId(auth);if(jdbc.update("UPDATE purchase_order SET status='VOIDED',voided_by=?,voided_at=?,void_reason=?,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND printed_at IS NULL AND version=?",uid,now,r.reason(),uid,now,id,r.version())!=1)throw conflict("Purchase-order status has changed; refresh the page");return ApiResponse.success(null);}

    @DeleteMapping("/orders/{id}") @Transactional
    public ApiResponse<Void> deleteOrder(@PathVariable long id,@RequestParam int version){
        var rows=jdbc.query("SELECT status,version,printed_at,completed_at FROM purchase_order WHERE id=? FOR UPDATE",(rs,n)->new Object[]{rs.getString(1),rs.getInt(2),rs.getTimestamp(3),rs.getTimestamp(4)},id);
        if(rows.isEmpty())throw notFound("Purchase order not found");Object[] order=rows.get(0);
        if(!"DRAFT".equals(order[0])||order[2]!=null||order[3]!=null)throw conflict("Only unprinted, incomplete draft purchase orders can be deleted");
        if(((Number)order[1]).intValue()!=version)throw conflict("Purchase order has been modified; refresh and try again");
        Integer receipts=jdbc.queryForObject("SELECT COUNT(*) FROM purchase_receipt WHERE purchase_order_id=?",Integer.class,id);if(receipts!=null&&receipts>0)throw conflict("A purchase order with receipt records cannot be deleted; void it instead when eligible");
        jdbc.update("DELETE FROM purchase_order_item WHERE purchase_order_id=?",id);
        if(jdbc.update("DELETE FROM purchase_order WHERE id=? AND status='DRAFT' AND printed_at IS NULL AND completed_at IS NULL AND version=?",id,version)!=1)throw conflict("Purchase-order status has changed; refresh the page");
        return ApiResponse.success(null);
    }

    @PostMapping("/orders/{id}/confirm-print") @Transactional
    public ApiResponse<Map<String,Object>> confirmOrderPrint(@PathVariable long id,@RequestBody VersionOnly r,Authentication auth){
        var rows=jdbc.query("SELECT status,version,printed_at,print_count FROM purchase_order WHERE id=? FOR UPDATE",(rs,n)->map("status",rs.getString(1),"version",rs.getInt(2),"printedAt",rs.getTimestamp(3),"printCount",rs.getInt(4)),id);
        if(rows.isEmpty())throw notFound("Purchase order not found");Map<String,Object> order=rows.get(0);if("VOIDED".equals(order.get("status")))throw conflict("A voided purchase order cannot be printed");if(((Number)order.get("version")).intValue()!=r.version())throw conflict("Purchase-order status has changed; refresh and try again");
        long uid=userId(auth);LocalDateTime now=LocalDateTime.now();boolean first=order.get("printedAt")==null;int changed=first?jdbc.update("UPDATE purchase_order SET printed_by=?,printed_at=?,print_count=1,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND printed_at IS NULL AND version=?",uid,now,uid,now,id,r.version()):jdbc.update("UPDATE purchase_order SET printed_by=?,printed_at=?,print_count=print_count+1,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND version=?",uid,now,uid,now,id,r.version());if(changed!=1)throw conflict("Purchase-order status has changed; refresh and try again");return ApiResponse.success(map("firstPrint",first,"printedAt",now,"printCount",((Number)order.get("printCount")).intValue()+1));
    }

    @GetMapping("/receipts")
    public ApiResponse<List<Map<String,Object>>> receipts(@RequestParam(defaultValue="") String keyword,@RequestParam(defaultValue="") String dateFrom,@RequestParam(defaultValue="") String dateTo,@RequestParam(defaultValue="") String status,@RequestParam(defaultValue="") String printStatus,@RequestParam(defaultValue="date") String sortBy,@RequestParam(defaultValue="asc") String sortDirection){String like="%"+keyword.trim()+"%";return ApiResponse.success(jdbc.query("SELECT r.id,r.receipt_no,r.receipt_date,r.supplier_code_snapshot,r.supplier_name_snapshot,r.total_amount,r.status,r.version,r.created_at,o.order_no,u.display_name,r.printed_at,r.print_count FROM purchase_receipt r LEFT JOIN purchase_order o ON o.id=r.purchase_order_id JOIN sys_user u ON u.id=r.created_by WHERE (r.receipt_no LIKE ? OR COALESCE(o.order_no,'') LIKE ? OR r.supplier_code_snapshot LIKE ? OR r.supplier_name_snapshot LIKE ?) AND (?='' OR r.receipt_date>=CAST(? AS DATE)) AND (?='' OR r.receipt_date<=CAST(? AS DATE)) AND (?='' OR r.status=?) AND (?='' OR (?='PRINTED' AND r.printed_at IS NOT NULL) OR (?='UNPRINTED' AND r.printed_at IS NULL)) ORDER BY "+DocumentSort.sql(sortBy,sortDirection,"r.receipt_date","r.receipt_no","r.id")+" LIMIT 200",(rs,n)->map("id",rs.getLong(1),"receiptNo",rs.getString(2),"receiptDate",rs.getDate(3).toLocalDate(),"supplierCode",rs.getString(4),"supplierName",rs.getString(5),"totalAmount",rs.getBigDecimal(6),"status",rs.getString(7),"version",rs.getInt(8),"createdAt",rs.getTimestamp(9).toLocalDateTime(),"orderNo",rs.getString(10),"createdByName",rs.getString(11),"printedAt",rs.getTimestamp(12)==null?null:rs.getTimestamp(12).toLocalDateTime(),"printCount",rs.getInt(13)),like,like,like,like,dateFrom,dateFrom,dateTo,dateTo,status,status,printStatus,printStatus,printStatus));}

    @GetMapping("/receipts/{id}")
    public ApiResponse<Map<String,Object>> receipt(@PathVariable long id){var rows=jdbc.query("SELECT r.id,r.receipt_no,r.receipt_date,r.purchase_order_id,r.supplier_id,r.supplier_code_snapshot,r.supplier_name_snapshot,r.warehouse_name,r.settlement_method,r.total_amount,r.status,COALESCE(r.remark,''),r.version,r.created_at,r.updated_at,r.approved_at,cu.display_name,uu.display_name,au.display_name,o.order_no,r.printed_at,r.print_count,pu.display_name FROM purchase_receipt r LEFT JOIN purchase_order o ON o.id=r.purchase_order_id JOIN sys_user cu ON cu.id=r.created_by JOIN sys_user uu ON uu.id=r.updated_by LEFT JOIN sys_user au ON au.id=r.approved_by LEFT JOIN sys_user pu ON pu.id=r.printed_by WHERE r.id=?",(rs,n)->map("id",rs.getLong(1),"receiptNo",rs.getString(2),"receiptDate",rs.getDate(3).toLocalDate(),"purchaseOrderId",rs.getObject(4),"supplierId",rs.getLong(5),"supplierCode",rs.getString(6),"supplierName",rs.getString(7),"warehouseName",rs.getString(8),"settlementMethod",rs.getString(9),"totalAmount",rs.getBigDecimal(10),"status",rs.getString(11),"remark",rs.getString(12),"version",rs.getInt(13),"createdAt",rs.getTimestamp(14).toLocalDateTime(),"updatedAt",rs.getTimestamp(15).toLocalDateTime(),"approvedAt",rs.getTimestamp(16)==null?null:rs.getTimestamp(16).toLocalDateTime(),"createdByName",rs.getString(17),"updatedByName",rs.getString(18),"approvedByName",rs.getString(19),"orderNo",rs.getString(20),"printedAt",rs.getTimestamp(21)==null?null:rs.getTimestamp(21).toLocalDateTime(),"printCount",rs.getInt(22),"printedByName",rs.getString(23)),id);if(rows.isEmpty())throw notFound("Purchase receipt not found");Map<String,Object> result=new LinkedHashMap<>(rows.get(0));result.put("items",receiptItems(id));return ApiResponse.success(result);}

    @PostMapping("/receipts") @Transactional
    public ApiResponse<Map<String,Object>> createReceipt(@Valid @RequestBody ReceiptRequest r,Authentication auth){requireReceiptOrder(r.purchaseOrderId());Supplier s=supplier(r.supplierId());validateOrderForReceipt(r.purchaseOrderId(),r.supplierId(),null);Prepared p=prepareReceipt(r.purchaseOrderId(),r.items());long uid=userId(auth);LocalDate date=r.receiptDate()==null?LocalDate.now():r.receiptDate();String no=nextNo("PURCHASE_RECEIPT","CS",date);LocalDateTime now=LocalDateTime.now();jdbc.update("INSERT INTO purchase_receipt(receipt_no,receipt_date,purchase_order_id,supplier_id,supplier_code_snapshot,supplier_name_snapshot,supplier_phone_snapshot,warehouse_name,settlement_method,total_amount,status,remark,version,created_by,created_at,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'DRAFT',?,0,?,?,?,?)",no,date,r.purchaseOrderId(),s.id(),s.code(),s.name(),s.phone(),blank(r.warehouseName(),"Main Warehouse"),blank(r.settlementMethod(),"Cash"),p.total(),r.remark(),uid,now,uid,now);long id=Objects.requireNonNull(jdbc.queryForObject("SELECT id FROM purchase_receipt WHERE receipt_no=?",Long.class,no));insertReceiptItems(id,p.items());return ApiResponse.success(map("id",id,"receiptNo",no,"totalAmount",p.total()));}

    @PutMapping("/receipts/{id}") @Transactional
    public ApiResponse<Map<String,Object>> updateReceipt(@PathVariable long id,@Valid @RequestBody ReceiptUpdateRequest r,Authentication auth){
        var rows=jdbc.query("SELECT status,version,printed_at,purchase_order_id,supplier_id FROM purchase_receipt WHERE id=? FOR UPDATE",(rs,n)->map("status",rs.getString(1),"version",rs.getInt(2),"printedAt",rs.getTimestamp(3),"purchaseOrderId",rs.getObject(4),"supplierId",rs.getLong(5)),id);
        if(rows.isEmpty())throw notFound("Purchase receipt not found");Map<String,Object> current=rows.get(0);
        if(!"DRAFT".equals(current.get("status"))||current.get("printedAt")!=null)throw conflict("Only unprinted draft receipts can be edited");
        if(((Number)current.get("version")).intValue()!=r.version())throw conflict("Receipt has been modified; refresh and try again");
        Long currentOrderId=current.get("purchaseOrderId")==null?null:((Number)current.get("purchaseOrderId")).longValue();
        if(!Objects.equals(currentOrderId,r.purchaseOrderId())||((Number)current.get("supplierId")).longValue()!=r.supplierId())throw conflict("A draft receipt cannot change its purchase order or supplier");
        requireReceiptOrder(r.purchaseOrderId());Supplier s=supplier(r.supplierId());validateOrderForReceipt(r.purchaseOrderId(),r.supplierId(),id);Prepared p=prepareReceipt(r.purchaseOrderId(),r.items());long uid=userId(auth);LocalDateTime now=LocalDateTime.now();
        int changed=jdbc.update("UPDATE purchase_receipt SET receipt_date=?,supplier_code_snapshot=?,supplier_name_snapshot=?,supplier_phone_snapshot=?,warehouse_name=?,settlement_method=?,total_amount=?,remark=?,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND printed_at IS NULL AND version=?",r.receiptDate()==null?LocalDate.now():r.receiptDate(),s.code(),s.name(),s.phone(),blank(r.warehouseName(),"Main Warehouse"),blank(r.settlementMethod(),"Cash"),p.total(),r.remark(),uid,now,id,r.version());
        if(changed!=1)throw conflict("Receipt status has changed; refresh and try again");jdbc.update("DELETE FROM purchase_receipt_item WHERE purchase_receipt_id=?",id);insertReceiptItems(id,p.items());return ApiResponse.success(map("id",id,"totalAmount",p.total(),"version",r.version()+1));
    }

    @PostMapping("/receipts/{id}/void") @Transactional
    public ApiResponse<Void> voidReceipt(@PathVariable long id,@RequestBody VersionReason r,Authentication auth){
        var rows=jdbc.query("SELECT status,version,printed_at FROM purchase_receipt WHERE id=? FOR UPDATE",(rs,n)->new Object[]{rs.getString(1),rs.getInt(2),rs.getTimestamp(3)},id);
        if(rows.isEmpty())throw notFound("Purchase receipt not found");Object[] receipt=rows.get(0);
        if(!"DRAFT".equals(receipt[0])||receipt[2]!=null)throw conflict("Only unapproved, unprinted draft receipts can be voided");
        if(((Number)receipt[1]).intValue()!=r.version())throw conflict("Receipt has been modified; refresh and try again");
        LocalDateTime now=LocalDateTime.now();long uid=userId(auth);
        if(jdbc.update("UPDATE purchase_receipt SET status='VOIDED',voided_by=?,voided_at=?,void_reason=?,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND printed_at IS NULL AND version=?",uid,now,r.reason(),uid,now,id,r.version())!=1)throw conflict("Receipt status has changed; refresh the page");
        return ApiResponse.success(null);
    }

    @DeleteMapping("/receipts/{id}") @Transactional
    public ApiResponse<Void> deleteReceipt(@PathVariable long id,@RequestParam int version){
        var rows=jdbc.query("SELECT status,version,printed_at FROM purchase_receipt WHERE id=? FOR UPDATE",(rs,n)->new Object[]{rs.getString(1),rs.getInt(2),rs.getTimestamp(3)},id);
        if(rows.isEmpty())throw notFound("Purchase receipt not found");Object[] receipt=rows.get(0);
        if(!"DRAFT".equals(receipt[0])||receipt[2]!=null)throw conflict("Only unapproved, unprinted draft receipts can be deleted");
        if(((Number)receipt[1]).intValue()!=version)throw conflict("Receipt has been modified; refresh and try again");
        jdbc.update("DELETE FROM purchase_receipt_item WHERE purchase_receipt_id=?",id);
        if(jdbc.update("DELETE FROM purchase_receipt WHERE id=? AND status='DRAFT' AND printed_at IS NULL AND version=?",id,version)!=1)throw conflict("Receipt status has changed; refresh the page");
        return ApiResponse.success(null);
    }

    @PostMapping("/receipts/{id}/approve") @Transactional
    public ApiResponse<Map<String,Object>> approveReceipt(@PathVariable long id,@RequestBody VersionOnly r,Authentication auth){
        var rec=jdbc.query("SELECT receipt_no,status,version,purchase_order_id FROM purchase_receipt WHERE id=? FOR UPDATE",(rs,n)->map("receiptNo",rs.getString(1),"status",rs.getString(2),"version",rs.getInt(3),"purchaseOrderId",rs.getObject(4)),id);if(rec.isEmpty())throw notFound("Purchase receipt not found");if(!"DRAFT".equals(rec.get(0).get("status")))throw conflict("Only draft receipts can be approved");if(((Number)rec.get(0).get("version")).intValue()!=r.version())throw conflict("Receipt has been modified; refresh the page");
        Long orderId=rec.get(0).get("purchaseOrderId")==null?null:((Number)rec.get(0).get("purchaseOrderId")).longValue();
        if(orderId==null)throw conflict("A purchase receipt must be linked to a purchase order");
        var order=jdbc.query("SELECT status FROM purchase_order WHERE id=? FOR UPDATE",(rs,n)->rs.getString(1),orderId);if(order.isEmpty())throw notFound("Linked purchase order not found");if(!"DRAFT".equals(order.get(0)))throw conflict("The linked purchase order is voided and cannot be approved");
        var lines=jdbc.query("SELECT id,sku_id,sku_code_snapshot,quantity,business_type FROM purchase_receipt_item WHERE purchase_receipt_id=? ORDER BY sku_id,line_no FOR UPDATE",(rs,n)->new Line(rs.getLong(1),rs.getLong(2),rs.getString(3),rs.getBigDecimal(4),rs.getString(5)),id);long uid=userId(auth);LocalDateTime now=LocalDateTime.now();
        for(Line line:lines){BigDecimal before=jdbc.queryForObject("SELECT total_stock FROM product_sku WHERE id=? FOR UPDATE",BigDecimal.class,line.skuId());if(before==null)throw conflict("Product not found: "+line.skuCode());BigDecimal after=before.add(line.quantity());jdbc.update("UPDATE product_sku SET total_stock=?,version=version+1,updated_by=?,updated_at=? WHERE id=?",after,uid,now,line.skuId());boolean reduced=line.quantity().signum()<0;jdbc.update("INSERT INTO inventory_movement(product_sku_id,movement_type,quantity_change,before_quantity,after_quantity,reason,reference_type,reference_id,reference_line_id,reference_no,created_by,created_at) VALUES(?,?,?,?,?,?, 'PURCHASE_RECEIPT',?,?,?,?,?)",line.skuId(),reduced?"PURCHASE_RETURN":"PURCHASE_RECEIPT",line.quantity(),before,after,"Purchase receipt "+rec.get(0).get("receiptNo")+" approved: "+(reduced?"stock out":"stock in"),id,line.id(),rec.get(0).get("receiptNo"),uid,now);}
        if(jdbc.update("UPDATE purchase_receipt SET status='APPROVED',approved_by=?,approved_at=?,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND version=?",uid,now,uid,now,id,r.version())!=1)throw conflict("Receipt status has changed; refresh the page");
        int orderCompletionChange=reconcileOrderCompletion(orderId,uid,now);
        return ApiResponse.success(map("approvedAt",now,"inventoryLines",lines.size(),"orderAutoCompleted",orderCompletionChange>0,"orderReopened",orderCompletionChange<0));
    }

    @PostMapping("/receipts/{id}/confirm-print") @Transactional
    public ApiResponse<Map<String,Object>> confirmReceiptPrint(@PathVariable long id,@RequestBody VersionOnly r,Authentication auth){
        var rows=jdbc.query("SELECT status,version,printed_at,print_count FROM purchase_receipt WHERE id=? FOR UPDATE",(rs,n)->map("status",rs.getString(1),"version",rs.getInt(2),"printedAt",rs.getTimestamp(3),"printCount",rs.getInt(4)),id);
        if(rows.isEmpty())throw notFound("Purchase receipt not found");Map<String,Object> receipt=rows.get(0);
        if(!"APPROVED".equals(receipt.get("status")))throw conflict("Only supervisor-approved purchase receipts can be confirmed as printed");
        if(((Number)receipt.get("version")).intValue()!=r.version())throw conflict("Receipt status has changed; refresh and try again");
        long uid=userId(auth);LocalDateTime now=LocalDateTime.now();boolean first=receipt.get("printedAt")==null;
        int changed=first?jdbc.update("UPDATE purchase_receipt SET printed_by=?,printed_at=?,print_count=1,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND printed_at IS NULL AND version=?",uid,now,uid,now,id,r.version()):jdbc.update("UPDATE purchase_receipt SET printed_by=?,printed_at=?,print_count=print_count+1,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND version=?",uid,now,uid,now,id,r.version());
        if(changed!=1)throw conflict("Receipt status has changed; refresh and try again");
        return ApiResponse.success(map("firstPrint",first,"printedAt",now,"printCount",((Number)receipt.get("printCount")).intValue()+1));
    }

    private List<Map<String,Object>> receiptItems(long id){return jdbc.query("SELECT id,line_no,sku_id,sku_code_snapshot,product_name_snapshot,COALESCE(specification_snapshot,''),COALESCE(color_snapshot,''),package_spec_snapshot,package_count,COALESCE(package_unit_snapshot,''),quantity,purchase_unit_snapshot,unit_price,reference_price,line_amount,COALESCE(remark,''),purchase_order_item_id,business_type FROM purchase_receipt_item WHERE purchase_receipt_id=? ORDER BY line_no",(rs,n)->map("id",rs.getLong(1),"lineNo",rs.getInt(2),"skuId",rs.getLong(3),"skuCode",rs.getString(4),"productName",rs.getString(5),"specification",rs.getString(6),"color",rs.getString(7),"packageSpec",rs.getBigDecimal(8),"packageCount",rs.getBigDecimal(9),"packageUnit",rs.getString(10),"quantity",rs.getBigDecimal(11),"unit",rs.getString(12),"unitPrice",rs.getBigDecimal(13),"referencePrice",rs.getBigDecimal(14),"lineAmount",rs.getBigDecimal(15),"remark",rs.getString(16),"purchaseOrderItemId",rs.getObject(17),"businessType",rs.getString(18)),id);}

    private List<Map<String,Object>> orderItems(long id){String sql="SELECT oi.id,oi.line_no,oi.sku_id,oi.sku_code_snapshot,oi.product_name_snapshot,COALESCE(oi.specification_snapshot,''),COALESCE(oi.color_snapshot,''),oi.package_spec_snapshot,oi.package_count,COALESCE(oi.package_unit_snapshot,''),oi.quantity,oi.purchase_unit_snapshot,oi.unit_price,oi.line_amount,COALESCE(oi.remark,''),"+
            "COALESCE(SUM(CASE WHEN r.status='APPROVED' AND ri.quantity>0 THEN ri.quantity ELSE 0 END),0),COALESCE(SUM(CASE WHEN r.status='APPROVED' AND ri.quantity<0 THEN -ri.quantity ELSE 0 END),0),COALESCE(SUM(CASE WHEN r.status='APPROVED' THEN ri.quantity ELSE 0 END),0),MAX(p.last_purchase_price) FROM purchase_order_item oi JOIN product_sku p ON p.id=oi.sku_id LEFT JOIN purchase_receipt_item ri ON ri.purchase_order_item_id=oi.id LEFT JOIN purchase_receipt r ON r.id=ri.purchase_receipt_id WHERE oi.purchase_order_id=? GROUP BY oi.id ORDER BY oi.line_no";
        return jdbc.query(sql,(rs,n)->{BigDecimal ordered=rs.getBigDecimal(11),positive=rs.getBigDecimal(16),returned=rs.getBigDecimal(17);LineProgress p=progress(ordered,positive,returned);return map("id",rs.getLong(1),"lineNo",rs.getInt(2),"skuId",rs.getLong(3),"skuCode",rs.getString(4),"productName",rs.getString(5),"specification",rs.getString(6),"color",rs.getString(7),"packageSpec",rs.getBigDecimal(8),"packageCount",rs.getBigDecimal(9),"packageUnit",rs.getString(10),"quantity",ordered,"unit",rs.getString(12),"unitPrice",rs.getBigDecimal(13),"referencePrice",rs.getBigDecimal(19),"lineAmount",rs.getBigDecimal(14),"remark",rs.getString(15),"positiveReceivedQuantity",positive,"returnedQuantity",returned,"netReceivedQuantity",p.net(),"receivedQuantity",p.net(),"remainingQuantity",p.remaining(),"overReceivedQuantity",p.over());},id);}
    static LineProgress progress(BigDecimal ordered,BigDecimal positiveReceived,BigDecimal returned){BigDecimal net=positiveReceived.subtract(returned);return new LineProgress(net,ordered.subtract(net).max(BigDecimal.ZERO),net.subtract(ordered).max(BigDecimal.ZERO));}
    private Metrics totals(List<Map<String,Object>> rows){BigDecimal ordered=BigDecimal.ZERO,net=BigDecimal.ZERO,remaining=BigDecimal.ZERO,over=BigDecimal.ZERO;for(Map<String,Object> r:rows){ordered=ordered.add((BigDecimal)r.get("quantity"));net=net.add((BigDecimal)r.get("netReceivedQuantity"));remaining=remaining.add((BigDecimal)r.get("remainingQuantity"));over=over.add((BigDecimal)r.get("overReceivedQuantity"));}return new Metrics(ordered,net,remaining,over);}
    private boolean allComplete(List<Map<String,Object>> rows){return !rows.isEmpty()&&rows.stream().allMatch(x->((BigDecimal)x.get("remainingQuantity")).signum()==0);}
    private BigDecimal pendingReceiptQuantity(long orderId){BigDecimal v=jdbc.queryForObject("SELECT COALESCE(SUM(ri.quantity),0) FROM purchase_receipt r JOIN purchase_receipt_item ri ON ri.purchase_receipt_id=r.id WHERE r.purchase_order_id=? AND r.status='DRAFT' AND ri.purchase_order_item_id IS NOT NULL",BigDecimal.class,orderId);return v==null?BigDecimal.ZERO:v;}
    private int reconcileOrderCompletion(long orderId,long uid,LocalDateTime now){
        Integer incomplete=jdbc.queryForObject("SELECT COUNT(*) FROM purchase_order_item oi WHERE oi.purchase_order_id=? AND COALESCE((SELECT SUM(ri.quantity) FROM purchase_receipt_item ri JOIN purchase_receipt r ON r.id=ri.purchase_receipt_id WHERE ri.purchase_order_item_id=oi.id AND r.status='APPROVED'),0)<oi.quantity",Integer.class,orderId);
        if(incomplete!=null&&incomplete>0)return jdbc.update("UPDATE purchase_order SET completed_by=NULL,completed_at=NULL,completion_reason=NULL,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND completed_at IS NOT NULL",uid,now,orderId)>0?-1:0;
        return jdbc.update("UPDATE purchase_order SET completed_by=?,completed_at=?,completion_reason='Net received quantity reached ordered quantity',updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND completed_at IS NULL",uid,now,uid,now,orderId)>0?1:0;
    }
    private void requireReceiptOrder(Long orderId){if(orderId==null)throw bad("Purchase receipts must be linked to a purchase order");}
    private void validateOrderForReceipt(Long orderId,long supplierId,Long excludedReceiptId){var rows=jdbc.query("SELECT supplier_id,status FROM purchase_order WHERE id=? FOR UPDATE",(rs,n)->new Object[]{rs.getLong(1),rs.getString(2)},orderId);if(rows.isEmpty()||((Number)rows.get(0)[0]).longValue()!=supplierId||!"DRAFT".equals(rows.get(0)[1]))throw bad("Purchase order does not exist, is voided, or has a different supplier");Map<String,Object> draft=draftReceipt(orderId,excludedReceiptId);if(draft!=null)throw conflict("Purchase order already has pending receipt "+draft.get("receiptNo")+"; continue editing that draft");}
    private Map<String,Object> draftReceipt(long orderId,Long excludedReceiptId){String sql="SELECT id,receipt_no FROM purchase_receipt WHERE purchase_order_id=? AND status='DRAFT'"+(excludedReceiptId==null?"":" AND id<>?")+" ORDER BY created_at ASC,id ASC LIMIT 1";List<Map<String,Object>> rows=excludedReceiptId==null?jdbc.query(sql,(rs,n)->map("id",rs.getLong(1),"receiptNo",rs.getString(2)),orderId):jdbc.query(sql,(rs,n)->map("id",rs.getLong(1),"receiptNo",rs.getString(2)),orderId,excludedReceiptId);return rows.isEmpty()?null:rows.get(0);}
    private Prepared prepareOrder(List<ItemRequest> req){Set<Long> seen=new HashSet<>();for(ItemRequest r:req){if(!seen.add(r.skuId()))throw bad("The same product cannot currently appear twice on a purchase order; this rule still requires owner confirmation");if(r.quantity().signum()<=0)throw bad("Purchase-order quantity must be greater than 0");}return prepare(req,false,null);}
    private Prepared prepareReceipt(Long orderId,List<ItemRequest> req){return prepare(req,true,orderId);}
    private Prepared prepare(List<ItemRequest> req,boolean receipt,Long orderId){List<Item> result=new ArrayList<>();BigDecimal total=BigDecimal.ZERO;for(ItemRequest r:req){String type=receipt?Objects.toString(r.businessType(),""):null;if(receipt)validateReceiptLine(orderId,r,type);var rows=jdbc.query("SELECT sku_code,product_name,specification,color,package_spec,package_unit,sales_unit,last_purchase_price FROM product_sku WHERE id=? AND enabled=1",(rs,n)->{BigDecimal reference=rs.getBigDecimal(8);return new Item(r.skuId(),rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),r.packageSpec()==null?rs.getBigDecimal(5):r.packageSpec(),r.packageCount(),blank(r.packageUnit(),rs.getString(6)),r.quantity(),blank(r.unit(),rs.getString(7)),r.unitPrice()==null?reference:r.unitPrice(),receipt?reference:null,BigDecimal.ZERO,r.remark(),r.purchaseOrderItemId(),type);},r.skuId());if(rows.isEmpty())throw bad("Product does not exist or is disabled");Item x=rows.get(0);if(x.price()==null)throw bad("Product '"+x.name()+"' has no purchase price");BigDecimal amount=x.quantity().multiply(x.price()).setScale(2,RoundingMode.HALF_UP);result.add(x.withAmount(amount));total=total.add(amount);}return new Prepared(result,total.setScale(2,RoundingMode.HALF_UP));}
    private void validateReceiptLine(Long orderId,ItemRequest r,String type){validateReceiptLineShape(orderId,r.purchaseOrderItemId(),type,r.quantity());Integer ok=jdbc.queryForObject("SELECT COUNT(*) FROM purchase_order_item WHERE id=? AND purchase_order_id=? AND sku_id=?",Integer.class,r.purchaseOrderItemId(),orderId,r.skuId());if(ok==null||ok!=1)throw bad("The purchase-order line does not belong to this order or its product does not match");}
    static void validateReceiptLineShape(Long orderId,Long orderItemId,String type,BigDecimal quantity){if(!Set.of("ORDER_RECEIPT","ORDER_RETURN").contains(type))throw bad("Invalid purchase-receipt line business type");if("ORDER_RECEIPT".equals(type)&&quantity.signum()<=0)throw bad("Stock-in quantity must be greater than 0");if("ORDER_RETURN".equals(type)&&quantity.signum()>=0)throw bad("Stock-out quantity must be less than 0");if(orderId==null||orderItemId==null)throw bad("A purchase-receipt line must be linked to a purchase order and order line");}
    private void insertOrderItems(long id,List<Item> lines){int n=1;for(Item x:lines)jdbc.update("INSERT INTO purchase_order_item(purchase_order_id,line_no,sku_id,sku_code_snapshot,product_name_snapshot,specification_snapshot,color_snapshot,package_spec_snapshot,package_count,package_unit_snapshot,quantity,purchase_unit_snapshot,unit_price,line_amount,remark) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,n++,x.skuId(),x.code(),x.name(),x.spec(),x.color(),x.packageSpec(),x.packageCount(),x.packageUnit(),x.quantity(),x.unit(),x.price(),x.amount(),x.remark());}
    private void insertReceiptItems(long id,List<Item> lines){int n=1;for(Item x:lines)jdbc.update("INSERT INTO purchase_receipt_item(purchase_receipt_id,purchase_order_item_id,business_type,line_no,sku_id,sku_code_snapshot,product_name_snapshot,specification_snapshot,color_snapshot,package_spec_snapshot,package_count,package_unit_snapshot,quantity,purchase_unit_snapshot,unit_price,reference_price,line_amount,remark) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,x.purchaseOrderItemId(),x.businessType(),n++,x.skuId(),x.code(),x.name(),x.spec(),x.color(),x.packageSpec(),x.packageCount(),x.packageUnit(),x.quantity(),x.unit(),x.price(),x.referencePrice(),x.amount(),x.remark());}
    private Supplier supplier(long id){var rows=jdbc.query("SELECT id,supplier_code,short_name,COALESCE(NULLIF(mobile,''),phone,'') FROM supplier WHERE id=? AND enabled=1",(rs,n)->new Supplier(rs.getLong(1),rs.getString(2),rs.getString(3),rs.getString(4)),id);if(rows.isEmpty())throw bad("Supplier does not exist or is disabled");return rows.get(0);}
    private String nextNo(String type,String prefix,LocalDate date){List<Integer> rows=jdbc.query("SELECT current_value FROM number_sequence WHERE biz_type=? AND biz_date=? FOR UPDATE",(rs,n)->rs.getInt(1),type,date);int next;if(rows.isEmpty()){next=1;jdbc.update("INSERT INTO number_sequence(biz_type,biz_date,current_value,version) VALUES(?,?,1,0)",type,date);}else{next=rows.get(0)+1;jdbc.update("UPDATE number_sequence SET current_value=?,version=version+1 WHERE biz_type=? AND biz_date=?",next,type,date);}return prefix+date.format(DateTimeFormatter.ofPattern("yyMMdd"))+"-"+String.format("%03d",next);}
    private long userId(Authentication a){Long id=jdbc.queryForObject("SELECT id FROM sys_user WHERE username=?",Long.class,a.getName());if(id==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED);return id;}
    private static String blank(String value,String fallback){return value==null||value.isBlank()?fallback:value.trim();}
    private static Map<String,Object> map(Object... v){Map<String,Object> m=new LinkedHashMap<>();for(int i=0;i<v.length;i+=2)m.put((String)v[i],v[i+1]);return m;}
    private static ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private static ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}private static ResponseStatusException notFound(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
    public record OrderRequest(@NotNull Long supplierId,LocalDate orderDate,LocalDate expectedDeliveryDate,String deliveryLocation,String remark,@NotEmpty List<@Valid ItemRequest> items){}
    public record OrderUpdateRequest(@NotNull Long supplierId,LocalDate orderDate,LocalDate expectedDeliveryDate,String deliveryLocation,String remark,@NotEmpty List<@Valid ItemRequest> items,@NotNull Integer version){}
    public record ReceiptRequest(Long purchaseOrderId,@NotNull Long supplierId,LocalDate receiptDate,String warehouseName,String settlementMethod,String remark,@NotEmpty List<@Valid ItemRequest> items){}
    public record ReceiptUpdateRequest(Long purchaseOrderId,@NotNull Long supplierId,LocalDate receiptDate,String warehouseName,String settlementMethod,String remark,@NotEmpty List<@Valid ItemRequest> items,@NotNull Integer version){}
    public record ItemRequest(@NotNull Long skuId,Long purchaseOrderItemId,String businessType,BigDecimal packageSpec,BigDecimal packageCount,String packageUnit,@NotNull BigDecimal quantity,String unit,BigDecimal unitPrice,String remark){}
    public record VersionOnly(@NotNull Integer version){} public record VersionReason(@NotNull Integer version,String reason){}
    private record Supplier(long id,String code,String name,String phone){} private record Prepared(List<Item> items,BigDecimal total){} private record Metrics(BigDecimal ordered,BigDecimal net,BigDecimal remaining,BigDecimal over){} record LineProgress(BigDecimal net,BigDecimal remaining,BigDecimal over){} private record Line(long id,long skuId,String skuCode,BigDecimal quantity,String businessType){}
    private record Item(long skuId,String code,String name,String spec,String color,BigDecimal packageSpec,BigDecimal packageCount,String packageUnit,BigDecimal quantity,String unit,BigDecimal price,BigDecimal referencePrice,BigDecimal amount,String remark,Long purchaseOrderItemId,String businessType){Item withAmount(BigDecimal a){return new Item(skuId,code,name,spec,color,packageSpec,packageCount,packageUnit,quantity,unit,price,referencePrice,a,remark,purchaseOrderItemId,businessType);}}
}
