package com.sunny.paintfactory.expense;

import com.sunny.paintfactory.common.ApiResponse;
import com.sunny.paintfactory.common.PageResult;
import com.sunny.paintfactory.common.DocumentSort;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.math.BigDecimal;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

@RestController @RequestMapping("/api/v1/other-expenses") @PreAuthorize("hasRole('ADMIN')")
public class OtherExpenseController {
  private final JdbcTemplate jdbc; public OtherExpenseController(JdbcTemplate jdbc){this.jdbc=jdbc;}
  @GetMapping("/categories") public ApiResponse<List<Map<String,Object>>> categories(){return ApiResponse.success(jdbc.query("SELECT category_code,category_name,COALESCE(remark,'') FROM expense_category WHERE enabled=1 ORDER BY sort_order,category_code",(r,n)->map("code",r.getString(1),"name",r.getString(2),"remark",r.getString(3))));}
  @GetMapping public ApiResponse<PageResult<Map<String,Object>>> list(@RequestParam(defaultValue="")String keyword,@RequestParam(defaultValue="")String status,@RequestParam(defaultValue="")String printStatus,@RequestParam(defaultValue="")String dateFrom,@RequestParam(defaultValue="")String dateTo,@RequestParam(defaultValue="date")String sortBy,@RequestParam(defaultValue="asc")String sortDirection,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="50")int pageSize){
    int p=Math.max(1,page),s=Math.min(100,Math.max(1,pageSize));StringBuilder w=new StringBuilder("(e.expense_no LIKE ? OR COALESCE(e.handler_name_snapshot,'') LIKE ? OR COALESCE(e.remark,'') LIKE ?)");List<Object>a=new ArrayList<>(List.of("%"+keyword.trim()+"%","%"+keyword.trim()+"%","%"+keyword.trim()+"%"));
    if(!status.isBlank()){w.append(" AND e.status=?");a.add(status);}if("PRINTED".equals(printStatus))w.append(" AND e.printed_at IS NOT NULL");if("UNPRINTED".equals(printStatus))w.append(" AND e.printed_at IS NULL");if(!dateFrom.isBlank()){w.append(" AND e.expense_date>=?");a.add(LocalDate.parse(dateFrom));}if(!dateTo.isBlank()){w.append(" AND e.expense_date<=?");a.add(LocalDate.parse(dateTo));}
    Long total=jdbc.queryForObject("SELECT COUNT(*) FROM other_expense e WHERE "+w,Long.class,a.toArray());List<Object>q=new ArrayList<>(a);q.add(s);q.add((p-1)*s);var rows=jdbc.query("SELECT e.id,e.expense_no,e.expense_date,e.account_name,COALESCE(e.handler_name_snapshot,''),e.total_amount,e.status,e.version,e.printed_at,e.print_count,cu.display_name FROM other_expense e JOIN sys_user cu ON cu.id=e.created_by WHERE "+w+" ORDER BY "+DocumentSort.sql(sortBy,sortDirection,"e.expense_date","e.expense_no","e.id")+" LIMIT ? OFFSET ?",(r,n)->map("id",r.getLong(1),"expenseNo",r.getString(2),"expenseDate",r.getDate(3).toLocalDate(),"accountName",r.getString(4),"handlerName",r.getString(5),"totalAmount",r.getBigDecimal(6),"status",r.getString(7),"version",r.getInt(8),"printedAt",ts(r,9),"printCount",r.getInt(10),"createdByName",r.getString(11)),q.toArray());return ApiResponse.success(new PageResult<>(rows,total==null?0:total,p,s));}
  @GetMapping("/{id}") public ApiResponse<Map<String,Object>> detail(@PathVariable long id){var h=jdbc.query("SELECT e.id,e.expense_no,e.expense_date,e.account_name,e.handler_employee_id,COALESCE(e.handler_name_snapshot,''),e.total_amount,e.status,COALESCE(e.remark,''),e.version,e.created_at,e.updated_at,e.approved_at,e.printed_at,e.print_count,e.void_reason,e.voided_at,cu.display_name,uu.display_name,au.display_name,pu.display_name,vu.display_name FROM other_expense e JOIN sys_user cu ON cu.id=e.created_by JOIN sys_user uu ON uu.id=e.updated_by LEFT JOIN sys_user au ON au.id=e.approved_by LEFT JOIN sys_user pu ON pu.id=e.printed_by LEFT JOIN sys_user vu ON vu.id=e.voided_by WHERE e.id=?",(r,n)->map("id",r.getLong(1),"expenseNo",r.getString(2),"expenseDate",r.getDate(3).toLocalDate(),"accountName",r.getString(4),"handlerEmployeeId",nullableLong(r,5),"handlerName",r.getString(6),"totalAmount",r.getBigDecimal(7),"status",r.getString(8),"remark",r.getString(9),"version",r.getInt(10),"createdAt",ts(r,11),"updatedAt",ts(r,12),"approvedAt",ts(r,13),"printedAt",ts(r,14),"printCount",r.getInt(15),"voidReason",r.getString(16),"voidedAt",ts(r,17),"createdByName",r.getString(18),"updatedByName",r.getString(19),"approvedByName",r.getString(20),"printedByName",r.getString(21),"voidedByName",r.getString(22)),id);if(h.isEmpty())throw notFound();Map<String,Object>x=new LinkedHashMap<>(h.get(0));x.put("items",jdbc.query("SELECT id,line_no,category_code,category_name_snapshot,COALESCE(summary,''),amount FROM other_expense_item WHERE other_expense_id=? ORDER BY line_no",(r,n)->map("id",r.getLong(1),"lineNo",r.getInt(2),"categoryCode",r.getString(3),"categoryName",r.getString(4),"summary",r.getString(5),"amount",r.getBigDecimal(6)),id));return ApiResponse.success(x);}
  @PostMapping @Transactional public ApiResponse<Map<String,Object>> create(@Valid @RequestBody ExpenseRequest r,Authentication a){long u=userId(a);LocalDate d=r.expenseDate()==null?LocalDate.now():r.expenseDate();Prepared p=prepare(r.items());String no=nextNo(d);LocalDateTime now=LocalDateTime.now();Employee e=employee(r.handlerEmployeeId());jdbc.update("INSERT INTO other_expense(expense_no,expense_date,account_name,handler_employee_id,handler_name_snapshot,total_amount,status,remark,version,created_by,created_at,updated_by,updated_at) VALUES(?,?,'Cash',?,?,?,'DRAFT',?,0,?,?,?,?)",no,d,e.id,e.name,p.total,r.remark(),u,now,u,now);Long id=jdbc.queryForObject("SELECT id FROM other_expense WHERE expense_no=?",Long.class,no);insertItems(id,p.items);return ApiResponse.success(detail(id).data());}
  @PutMapping("/{id}") @Transactional public ApiResponse<Map<String,Object>> update(@PathVariable long id,@Valid @RequestBody ExpenseRequest r,Authentication a){Prepared p=prepare(r.items());Employee e=employee(r.handlerEmployeeId());long u=userId(a);int n=jdbc.update("UPDATE other_expense SET expense_date=?,handler_employee_id=?,handler_name_snapshot=?,total_amount=?,remark=?,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND printed_at IS NULL AND version=?",r.expenseDate(),e.id,e.name,p.total,r.remark(),u,LocalDateTime.now(),id,r.version());if(n!=1)throw conflict("单据已打印、已审核或已被修改，请刷新");jdbc.update("DELETE FROM other_expense_item WHERE other_expense_id=?",id);insertItems(id,p.items);return ApiResponse.success(detail(id).data());}
  @PostMapping("/{id}/approve") @Transactional public ApiResponse<Void> approve(@PathVariable long id,@Valid @RequestBody VersionOnly r,Authentication a){long u=userId(a);int n=jdbc.update("UPDATE other_expense SET status='APPROVED',approved_by=?,approved_at=?,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND version=?",u,LocalDateTime.now(),u,LocalDateTime.now(),id,r.version());if(n!=1)throw conflict("单据已审核、已作废或状态已变化");return ApiResponse.success(null);}
  @PostMapping("/{id}/confirm-print") @Transactional public ApiResponse<Map<String,Object>> print(@PathVariable long id,@Valid @RequestBody VersionOnly r,Authentication a){var x=jdbc.query("SELECT status,version,printed_at,print_count FROM other_expense WHERE id=? FOR UPDATE",(z,n)->map("status",z.getString(1),"version",z.getInt(2),"printedAt",z.getTimestamp(3),"count",z.getInt(4)),id);if(x.isEmpty())throw notFound();Map<String,Object>v=x.get(0);if("VOIDED".equals(v.get("status")))throw conflict("已作废单据不能打印");if(((Number)v.get("version")).intValue()!=r.version())throw conflict("单据状态已变化，请刷新");long u=userId(a);LocalDateTime now=LocalDateTime.now();boolean first=v.get("printedAt")==null;int n=jdbc.update("UPDATE other_expense SET printed_by=?,printed_at=?,print_count=print_count+1,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status<>'VOIDED' AND version=?",u,now,u,now,id,r.version());if(n!=1)throw conflict("单据状态已变化，请刷新");return ApiResponse.success(map("firstPrint",first,"printedAt",now,"printCount",((Number)v.get("count")).intValue()+1));}
  @PostMapping("/{id}/void") @Transactional public ApiResponse<Void> voidExpense(@PathVariable long id,@Valid @RequestBody VoidRequest r,Authentication a){long u=userId(a);int n=jdbc.update("UPDATE other_expense SET status='VOIDED',voided_by=?,voided_at=?,void_reason=?,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND printed_at IS NULL AND version=?",u,LocalDateTime.now(),r.reason().trim(),u,LocalDateTime.now(),id,r.version());if(n!=1)throw conflict("只有未打印、未审核的草稿可以作废");return ApiResponse.success(null);}
  private Prepared prepare(List<ItemRequest> req){if(req==null||req.isEmpty())throw bad("至少填写一条支出明细");List<Item> out=new ArrayList<>();BigDecimal total=BigDecimal.ZERO;for(ItemRequest i:req){if(i.amount()==null||i.amount().signum()<=0)throw bad("支出金额必须大于0");var n=jdbc.query("SELECT category_name FROM expense_category WHERE category_code=? AND enabled=1",(r,k)->r.getString(1),i.categoryCode());if(n.isEmpty())throw bad("收支类别不存在或已停用");out.add(new Item(i.categoryCode(),n.get(0),i.summary(),i.amount()));total=total.add(i.amount());}return new Prepared(out,total);}
  private Employee employee(Long id){if(id==null)return new Employee(null,null);var x=jdbc.query("SELECT employee_name FROM employee WHERE id=? AND enabled=1",(r,n)->r.getString(1),id);if(x.isEmpty())throw bad("经手人不存在或已停用");return new Employee(id,x.get(0));}
  private void insertItems(long id,List<Item> items){int line=1;for(Item i:items)jdbc.update("INSERT INTO other_expense_item(other_expense_id,line_no,category_code,category_name_snapshot,summary,amount) VALUES(?,?,?,?,?,?)",id,line++,i.code,i.name,i.summary,i.amount);}
  private String nextNo(LocalDate d){List<Integer>x=jdbc.query("SELECT current_value FROM number_sequence WHERE biz_type='OTHER_EXPENSE' AND biz_date=? FOR UPDATE",(r,n)->r.getInt(1),d);int n;if(x.isEmpty()){n=1;jdbc.update("INSERT INTO number_sequence(biz_type,biz_date,current_value,version) VALUES('OTHER_EXPENSE',?,1,0)",d);}else{n=x.get(0)+1;jdbc.update("UPDATE number_sequence SET current_value=?,version=version+1 WHERE biz_type='OTHER_EXPENSE' AND biz_date=?",n,d);}return "ZC"+d.format(DateTimeFormatter.ofPattern("yyMMdd"))+"-"+String.format("%03d",n);}
  private long userId(Authentication a){Long id=jdbc.queryForObject("SELECT id FROM sys_user WHERE username=?",Long.class,a.getName());if(id==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED);return id;}
  private static LocalDateTime ts(java.sql.ResultSet r,int i)throws java.sql.SQLException{var x=r.getTimestamp(i);return x==null?null:x.toLocalDateTime();}private static Long nullableLong(java.sql.ResultSet r,int i)throws java.sql.SQLException{long x=r.getLong(i);return r.wasNull()?null:x;}private static Map<String,Object> map(Object...v){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<v.length;i+=2)m.put((String)v[i],v[i+1]);return m;}private static ResponseStatusException bad(String s){return new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,s);}private static ResponseStatusException conflict(String s){return new ResponseStatusException(HttpStatus.CONFLICT,s);}private static ResponseStatusException notFound(){return new ResponseStatusException(HttpStatus.NOT_FOUND,"未找到其它支出单");}
  public record ExpenseRequest(@NotNull LocalDate expenseDate,Long handlerEmployeeId,String remark,@NotEmpty List<@Valid ItemRequest> items,Integer version){} public record ItemRequest(@NotBlank String categoryCode,String summary,@NotNull @DecimalMin("0.01") BigDecimal amount){} public record VersionOnly(@NotNull Integer version){} public record VoidRequest(@NotNull Integer version,@NotBlank String reason){} private record Item(String code,String name,String summary,BigDecimal amount){} private record Prepared(List<Item>items,BigDecimal total){} private record Employee(Long id,String name){}
}
