CREATE TABLE purchase_order (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_no VARCHAR(32) NOT NULL,
  order_date DATE NOT NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  supplier_code_snapshot VARCHAR(64) NOT NULL,
  supplier_name_snapshot VARCHAR(200) NOT NULL,
  supplier_phone_snapshot VARCHAR(128) NULL,
  expected_delivery_date DATE NULL,
  delivery_location VARCHAR(500) NULL,
  total_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  remark VARCHAR(1000) NULL,
  version INT UNSIGNED NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  voided_by BIGINT UNSIGNED NULL,
  voided_at DATETIME(3) NULL,
  void_reason VARCHAR(500) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_purchase_order_no (order_no),
  KEY idx_purchase_order_date (order_date),
  KEY idx_purchase_order_supplier (supplier_id),
  CONSTRAINT fk_purchase_order_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id),
  CONSTRAINT fk_purchase_order_created_by FOREIGN KEY (created_by) REFERENCES sys_user(id),
  CONSTRAINT fk_purchase_order_updated_by FOREIGN KEY (updated_by) REFERENCES sys_user(id),
  CONSTRAINT fk_purchase_order_voided_by FOREIGN KEY (voided_by) REFERENCES sys_user(id),
  CONSTRAINT ck_purchase_order_status CHECK (status IN ('DRAFT','VOIDED'))
) ENGINE=InnoDB;

CREATE TABLE purchase_order_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  purchase_order_id BIGINT UNSIGNED NOT NULL,
  line_no INT UNSIGNED NOT NULL,
  sku_id BIGINT UNSIGNED NOT NULL,
  sku_code_snapshot VARCHAR(64) NOT NULL,
  product_name_snapshot VARCHAR(200) NOT NULL,
  specification_snapshot VARCHAR(200) NULL,
  color_snapshot VARCHAR(100) NULL,
  package_spec_snapshot DECIMAL(18,4) NULL,
  package_count DECIMAL(18,4) NULL,
  package_unit_snapshot VARCHAR(32) NULL,
  quantity DECIMAL(18,4) NOT NULL,
  purchase_unit_snapshot VARCHAR(32) NOT NULL,
  unit_price DECIMAL(18,2) NOT NULL,
  line_amount DECIMAL(18,2) NOT NULL,
  remark VARCHAR(500) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_purchase_order_line (purchase_order_id, line_no),
  CONSTRAINT fk_purchase_order_item_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
  CONSTRAINT fk_purchase_order_item_sku FOREIGN KEY (sku_id) REFERENCES product_sku(id),
  CONSTRAINT ck_purchase_order_item_quantity CHECK (quantity <> 0)
) ENGINE=InnoDB;

CREATE TABLE purchase_receipt (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  receipt_no VARCHAR(32) NOT NULL,
  receipt_date DATE NOT NULL,
  purchase_order_id BIGINT UNSIGNED NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  supplier_code_snapshot VARCHAR(64) NOT NULL,
  supplier_name_snapshot VARCHAR(200) NOT NULL,
  supplier_phone_snapshot VARCHAR(128) NULL,
  warehouse_name VARCHAR(100) NOT NULL DEFAULT 'Main Warehouse',
  settlement_method VARCHAR(32) NOT NULL DEFAULT 'Cash',
  total_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  remark VARCHAR(1000) NULL,
  version INT UNSIGNED NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_by BIGINT UNSIGNED NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  approved_by BIGINT UNSIGNED NULL,
  approved_at DATETIME(3) NULL,
  voided_by BIGINT UNSIGNED NULL,
  voided_at DATETIME(3) NULL,
  void_reason VARCHAR(500) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_purchase_receipt_no (receipt_no),
  KEY idx_purchase_receipt_date (receipt_date),
  KEY idx_purchase_receipt_order (purchase_order_id),
  KEY idx_purchase_receipt_supplier (supplier_id),
  CONSTRAINT fk_purchase_receipt_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
  CONSTRAINT fk_purchase_receipt_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id),
  CONSTRAINT fk_purchase_receipt_created_by FOREIGN KEY (created_by) REFERENCES sys_user(id),
  CONSTRAINT fk_purchase_receipt_updated_by FOREIGN KEY (updated_by) REFERENCES sys_user(id),
  CONSTRAINT fk_purchase_receipt_approved_by FOREIGN KEY (approved_by) REFERENCES sys_user(id),
  CONSTRAINT fk_purchase_receipt_voided_by FOREIGN KEY (voided_by) REFERENCES sys_user(id),
  CONSTRAINT ck_purchase_receipt_status CHECK (status IN ('DRAFT','APPROVED','VOIDED'))
) ENGINE=InnoDB;

CREATE TABLE purchase_receipt_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  purchase_receipt_id BIGINT UNSIGNED NOT NULL,
  purchase_order_item_id BIGINT UNSIGNED NULL,
  line_no INT UNSIGNED NOT NULL,
  sku_id BIGINT UNSIGNED NOT NULL,
  sku_code_snapshot VARCHAR(64) NOT NULL,
  product_name_snapshot VARCHAR(200) NOT NULL,
  specification_snapshot VARCHAR(200) NULL,
  color_snapshot VARCHAR(100) NULL,
  package_spec_snapshot DECIMAL(18,4) NULL,
  package_count DECIMAL(18,4) NULL,
  package_unit_snapshot VARCHAR(32) NULL,
  quantity DECIMAL(18,4) NOT NULL,
  purchase_unit_snapshot VARCHAR(32) NOT NULL,
  unit_price DECIMAL(18,2) NOT NULL,
  line_amount DECIMAL(18,2) NOT NULL,
  remark VARCHAR(500) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_purchase_receipt_line (purchase_receipt_id, line_no),
  UNIQUE KEY uk_purchase_receipt_sku (purchase_receipt_id, sku_id),
  CONSTRAINT fk_purchase_receipt_item_receipt FOREIGN KEY (purchase_receipt_id) REFERENCES purchase_receipt(id),
  CONSTRAINT fk_purchase_receipt_item_order_item FOREIGN KEY (purchase_order_item_id) REFERENCES purchase_order_item(id),
  CONSTRAINT fk_purchase_receipt_item_sku FOREIGN KEY (sku_id) REFERENCES product_sku(id),
  CONSTRAINT ck_purchase_receipt_item_quantity CHECK (quantity <> 0)
) ENGINE=InnoDB;

ALTER TABLE inventory_movement
  DROP CHECK ck_inventory_movement_type,
  ADD CONSTRAINT ck_inventory_movement_type CHECK (movement_type IN ('INBOUND','OUTBOUND','ADJUSTMENT','REVERSAL','SALE_PRINT','PURCHASE_RECEIPT'));
