export default {
  language:{label:'Language'},
  brand:{name:'Xinfa Paint Factory',system:'Business Management System',full:'Xinfa Paint Factory · Business Management System'},
  common:{currentUser:'Current User',signOut:'Sign Out',systemHealthy:'System Healthy',view:'View',handle:'Handle',all:'All'},
  login:{subtitle:'Business Management System',username:'Username',password:'Password',signIn:'Sign In',required:'Enter username and password',invalid:'Username or password is incorrect'},
  nav:{dashboard:'Dashboard',sales:'Sales',salesOrder:'Sales Order',salesReturns:'Sales Returns',returnWarehousing:'Return Warehousing',dispatch:'Dispatch',dispatchSheet:'Dispatch Sheet',purchasing:'Purchasing',purchaseDocuments:'Purchase Orders & Receipts',productsInventory:'Products & Inventory',productCatalog:'Product Catalog',inventoryReconciliation:'Inventory Reconciliation',ledgers:'Ledgers',inventoryLedger:'Inventory Movement Ledger',purchaseLedger:'Purchase Ledger',salesLedger:'Sales Ledger',cashflowLedger:'Cashflow Ledger',finance:'Finance',otherExpenses:'Other Expenses',masterData:'Master Data',customers:'Customers',suppliers:'Suppliers',employees:'Employees',vehicles:'Vehicles',routes:'Routes',departments:'Departments',employeeTypes:'Employee Types',legacyImport:'Legacy Data Import',systemSettings:'System Settings',users:'User Accounts',auditLog:'Audit Log'},
  role:{ADMIN:'System Administrator',SALES:'Sales Staff',WAREHOUSE:'Warehouse Staff',DISPATCH:'Dispatch Staff'},
  home:{
    selectOperation:'{name}, Please select an operation',ownerSubtitle:"Operations Overview & Today's Tasks",ownerView:'Owner View',businessView:'Operations View',
    estimatedProfit:"Yesterday's Estimated Gross Profit",estimated:'Estimated',profitNote:'Sales amount minus recent purchase price; this is an estimate, not posted or net profit.',missingCost:'{count} line items have no recent purchase price; estimated gross profit may be overstated.',noComparison:'No comparison data for the previous day',previousDay:'vs. previous day {value}%',yesterdaySales:"Yesterday's Sales",yesterdayOrders:"Yesterday's Sales Orders",orders:'orders',firstPrintCount:'Counted by first confirmed print',stockAlerts:'Stock Alerts',items:'items',stockLimitNote:'Current stock below minimum stock',todayTasks:"Today's Tasks",sales:'Sales',dispatch:'Dispatch',purchase:'Purchasing',inventory:'Inventory',businessType:'Business Type',tasks:'Tasks',quantity:'Quantity',status:'Status',actions:'Actions',quickActions:'Quick Actions',createSales:'Create Sales Order',createDispatch:'Create Dispatch Sheet',createPurchase:'Create Purchase Order',reconcile:'Inventory Reconciliation',operationalAlerts:'Operational Alerts',documents:'documents',yesterdayActivity:"Yesterday's Sales Activity",viewSales:'View Sales Orders',time:'Time',orderNo:'Sales Order No.',customer:'Customer',salesAmount:'Sales Amount',referenceCost:'Reference Cost',estimatedGrossProfit:'Estimated Gross Profit',printStatus:'Print Status',emptySales:'No sales orders were first-printed yesterday',loadFailed:'Failed to load operational data. Try again later.',
    taskSales:'Sales Orders Awaiting Print',taskDispatch:'Dispatch Sheets Awaiting Approval',taskPurchase:'Purchase Receipts Awaiting Approval',taskInventory:'Stock Alerts',
    entryPurchase:'Purchasing',entryPurchaseDesc:'Create purchase orders, record receipts, and approve stock-in',entrySales:'Sales Order Entry',entrySalesDesc:'Create orders, check inventory, and print delivery notes',entryDispatch:'Dispatch Management',entryDispatchDesc:'Add printed sales orders and approve dispatch sheets',entryProducts:'Product Catalog',entryProductsDesc:'Find products quickly by manufacturer, category, and subcategory',entryInventory:'Inventory Reconciliation',entryInventoryDesc:'Review stock, shortages, and inventory movements',entryMaster:'Master Data',entryMasterDesc:'Manage customers, suppliers, dispatch data, and organization records',entrySystem:'System Settings',entrySystemDesc:'Manage user accounts, permissions, and audit logs'
  }
}
