<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api'
const query=reactive({keyword:'',regionLarge:'',regionSmall:'',enabled:true as boolean|'',page:1,pageSize:20}),rows=ref<any[]>([]),regions=ref<any[]>([]),total=ref(0),loading=ref(false),dialog=ref(false),editing=ref(false)
const regionLargeOptions=computed(()=>[...new Set(regions.value.map(x=>x.regionLarge).filter(Boolean))])
const regionSmallOptions=computed(()=>[...new Set(regions.value.filter(x=>!query.regionLarge||x.regionLarge===query.regionLarge).map(x=>x.regionSmall).filter(Boolean))])
const empty=()=>({id:0,customerCode:'',shortName:'',contactName:'',mobile:'',phone:'',route:'',settlementMethod:'现款',version:0})
const form=reactive(empty())
async function load(){loading.value=true;try{const{data}=await api.get('/customers',{params:{...query,enabled:query.enabled===''?true:query.enabled,includeDisabled:query.enabled==='' }});rows.value=data.data.items;total.value=data.data.total}finally{loading.value=false}}
async function loadRegions(){const{data}=await api.get('/customer-regions');regions.value=data.data}
function changeRegionLarge(){query.regionSmall='';search()}
function search(){query.page=1;load()} function add(){Object.assign(form,empty());editing.value=false;dialog.value=true} function edit(row:any){Object.assign(form,row);editing.value=true;dialog.value=true}
async function save(){if(!form.customerCode.trim()||!form.shortName.trim())return ElMessage.warning('客户编号和名称不能为空');try{editing.value?await api.put(`/customers/${form.id}`,form):await api.post('/customers',form);ElMessage.success('保存成功');dialog.value=false;load()}catch(e:any){ElMessage.error(e.response?.data?.message||'保存失败，请检查编号是否重复')}}
async function toggle(row:any){const action=row.enabled?'停用':'恢复使用';await ElMessageBox.confirm(`确定${action}客户“${row.shortName}”吗？`,`${action}确认`,{type:row.enabled?'warning':'info'});await api.patch(`/customers/${row.id}/enabled`,{enabled:!row.enabled,version:row.version});ElMessage.success(`${action}成功`);load()}
onMounted(()=>{loadRegions();load()})
</script>
<template><section><div class="page-heading"><div><h1>客户资料</h1><p>按编号、名称、助记码或电话检索</p></div><el-button type="primary" @click="add">新增客户</el-button></div>
<el-card><div class="toolbar customer-toolbar"><el-input v-model="query.keyword" clearable placeholder="客户编号 / 名称 / 电话" @keyup.enter="search"/><el-select v-model="query.regionLarge" clearable filterable placeholder="全部大区" @change="changeRegionLarge"><el-option v-for="item in regionLargeOptions" :key="item" :label="item" :value="item"/></el-select><el-select v-model="query.regionSmall" clearable filterable placeholder="全部小区" @change="search"><el-option v-for="item in regionSmallOptions" :key="item" :label="item" :value="item"/></el-select><el-select v-model="query.enabled" @change="search"><el-option label="全部状态" value=""/><el-option label="使用中" :value="true"/><el-option label="已停用" :value="false"/></el-select><el-button type="primary" @click="search">查询</el-button></div>
<el-table :data="rows" v-loading="loading" stripe><el-table-column prop="customerCode" label="客户编号" width="130"/><el-table-column prop="shortName" label="客户名称" min-width="200"/><el-table-column prop="regionLarge" label="大区" width="85"/><el-table-column prop="regionSmall" label="小区" width="90"/><el-table-column prop="contactName" label="联系人" width="110"/><el-table-column prop="mobile" label="手机" width="140"/><el-table-column prop="phone" label="电话" min-width="160"/><el-table-column prop="route" label="路线" width="110"/><el-table-column prop="settlementMethod" label="结算方式" width="100"/><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.enabled?'success':'info'">{{s.row.enabled?'使用中':'已停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="170" fixed="right"><template #default="s"><el-button link type="primary" @click="edit(s.row)">编辑</el-button><el-button link :type="s.row.enabled?'danger':'success'" @click="toggle(s.row)">{{s.row.enabled?'停用':'恢复'}}</el-button></template></el-table-column></el-table>
<el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" :page-sizes="[20,50,100]" :total="total" layout="total, sizes, prev, pager, next" @current-change="load" @size-change="search"/></el-card>
<el-dialog v-model="dialog" :title="editing?'编辑客户':'新增客户'" width="620px"><el-form label-width="90px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="客户编号" required><el-input v-model="form.customerCode"/></el-form-item></el-col><el-col :span="12"><el-form-item label="客户名称" required><el-input v-model="form.shortName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="联系人"><el-input v-model="form.contactName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="手机"><el-input v-model="form.mobile"/></el-form-item></el-col><el-col :span="12"><el-form-item label="电话"><el-input v-model="form.phone"/></el-form-item></el-col><el-col :span="12"><el-form-item label="路线"><el-input v-model="form.route"/></el-form-item></el-col><el-col :span="12"><el-form-item label="结算方式"><el-select v-model="form.settlementMethod"><el-option label="现款" value="现款"/><el-option label="挂账" value="挂账"/></el-select></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></section></template>
<style scoped>.customer-toolbar{display:grid;grid-template-columns:minmax(240px,1fr) 140px 140px 130px 80px;gap:10px}@media(max-width:900px){.customer-toolbar{grid-template-columns:1fr}}</style>
