<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api} from '../api'
import BusinessDocumentDialog from '../components/BusinessDocumentDialog.vue'
import {localToday} from '../utils/date'
const today=localToday
const rows=ref<any[]>([]),selected=ref<any>(),loading=ref(false)
const documentDialog=ref(false),documentType=ref(''),documentId=ref<number|null>(null)
const summary=reactive<any>({rowCount:0,documentCount:0,inboundQuantity:0,outboundQuantity:0,inboundAmount:0,outboundAmount:0})
const query=reactive({dateFrom:today(),dateTo:today(),types:['PURCHASE_RECEIPT','SALES_OUTBOUND','SALES_RETURN','STOCK_ADJUSTMENT'],keyword:'',referenceNo:'',sortBy:'date',sortDirection:'asc'})
const money=(v:any)=>v===null||v===undefined?'—':`¥${Number(v).toFixed(2)}`
const qty=(v:any)=>v===null||v===undefined?'':Number(v).toLocaleString('zh-CN',{maximumFractionDigits:4})
function handleSortChange({prop,order}:{prop:string,order:string}){query.sortBy=prop==='referenceNo'?'documentNo':'date';query.sortDirection=order==='descending'?'desc':'asc';load()}
async function load(){if(!query.types.length){rows.value=[];selected.value=undefined;Object.assign(summary,{rowCount:0,documentCount:0,inboundQuantity:0,outboundQuantity:0,inboundAmount:0,outboundAmount:0});return}loading.value=true;try{const {types,...rest}=query;const {data}=await api.get('/ledgers/inventory',{params:{...rest,type:types.join(',')}});rows.value=data.data.items;Object.assign(summary,data.data.summary);selected.value=rows.value[0]}catch(e:any){ElMessage.error(e?.response?.data?.message||e?.message||'查询失败')}finally{loading.value=false}}
function clear(){Object.assign(query,{dateFrom:today(),dateTo:today(),types:['PURCHASE_RECEIPT','SALES_OUTBOUND','SALES_RETURN','STOCK_ADJUSTMENT'],keyword:'',referenceNo:'',sortBy:'date',sortDirection:'asc'});load()}
function openDocument(row:any){const type=({PURCHASE_RECEIPT:'purchase-receipt',SALES_ORDER_PRINT:'sales-order',RETURN_WAREHOUSE:'return-warehouse'} as any)[row.referenceType];if(!type||!row.documentId)return ElMessageBox.alert(`货品：${row.skuCode} ${row.productName}<br>变动前：${qty(row.beforeQuantity)}　变动后：${qty(row.afterQuantity)}<br>原因：${row.reason||'—'}<br>经办人：${row.operatorName||'—'}　时间：${row.occurredAt}`,row.referenceNo?`库存调整单 ${row.referenceNo}`:'库存调整资料',{dangerouslyUseHTMLString:true,confirmButtonText:'关闭'});documentType.value=type;documentId.value=row.documentId;documentDialog.value=true}
onMounted(load)
</script>
<template><div class="ledger-page"><div class="page-heading"><div><h1>货品进出流水账</h1><p>只读显示真实库存变动；销售打印扣库、采购收货审核增减库存、销售退货入仓审核后入库</p></div></div><el-card>
  <div class="filters"><el-date-picker v-model="query.dateFrom" type="date" value-format="YYYY-MM-DD"/><span>至</span><el-date-picker v-model="query.dateTo" type="date" value-format="YYYY-MM-DD"/>
    <el-checkbox-group v-model="query.types"><el-checkbox value="PURCHASE_RECEIPT">采购收货</el-checkbox><el-checkbox value="SALES_OUTBOUND">销售单</el-checkbox><el-checkbox value="SALES_RETURN">销售退货</el-checkbox><el-checkbox value="STOCK_ADJUSTMENT">库存盘点/调整</el-checkbox></el-checkbox-group>
    <el-input v-model="query.keyword" clearable placeholder="货品编号 / 品名规格" @keyup.enter="load"/><el-input v-model="query.referenceNo" clearable placeholder="来源单号" @keyup.enter="load"/><el-button type="primary" @click="load">查询</el-button><el-button @click="clear">清空条件</el-button>
  </div>
  <el-table :data="rows" v-loading="loading" height="46vh" highlight-current-row stripe class="document-ledger" :default-sort="{prop:'occurredAt',order:'ascending'}" @sort-change="handleSortChange" @row-click="selected=$event" @row-dblclick="openDocument"><el-table-column prop="occurredAt" label="发生时间" width="170" sortable="custom" :sort-orders="['ascending','descending']"/><el-table-column prop="documentType" label="单据类型" width="130"/><el-table-column prop="warehouseName" label="仓库" width="90"/><el-table-column prop="skuCode" label="编号" width="120"/><el-table-column label="品名规格" min-width="240"><template #default="s">{{s.row.productName}} {{s.row.specification}}</template></el-table-column><el-table-column prop="unit" label="单位" width="70"/><el-table-column label="单价" width="105" align="right"><template #default="s">{{money(s.row.unitPrice)}}</template></el-table-column><el-table-column label="进仓数量" width="105" align="right"><template #default="s">{{qty(s.row.inboundQuantity)}}</template></el-table-column><el-table-column label="进仓金额" width="115" align="right"><template #default="s">{{money(s.row.inboundAmount)}}</template></el-table-column><el-table-column label="出仓数量" width="105" align="right"><template #default="s">{{qty(s.row.outboundQuantity)}}</template></el-table-column><el-table-column label="出仓金额" width="115" align="right"><template #default="s">{{money(s.row.outboundAmount)}}</template></el-table-column><el-table-column label="供应商 / 客户" min-width="190"><template #default="s">{{s.row.supplierName||s.row.customerName||'—'}}</template></el-table-column><el-table-column prop="referenceNo" label="来源单号" width="155" sortable="custom" :sort-orders="['ascending','descending']"/></el-table>
  <div class="summary"><span>流水 {{summary.rowCount}} 行</span><span>单据 {{summary.documentCount}} 张</span><span>进仓数量 {{qty(summary.inboundQuantity)}}</span><span>进仓金额 {{money(summary.inboundAmount)}}</span><span>出仓数量 {{qty(summary.outboundQuantity)}}</span><span>出仓金额 {{money(summary.outboundAmount)}}</span></div>
  <section class="inline-detail"><div class="detail-title"><strong>{{selected?`${selected.referenceNo||'无来源单号'} · ${selected.skuCode} 流水详情`:'单击上方流水查看详情'}}</strong></div><div v-if="selected" class="detail-grid"><span>货品：{{selected.productName}} {{selected.specification}}</span><span>变动前：{{qty(selected.beforeQuantity)}}</span><span>变动后：{{qty(selected.afterQuantity)}}</span><span>供应商：{{selected.supplierCode}} {{selected.supplierName||'—'}}</span><span>客户：{{selected.customerCode}} {{selected.customerName||'—'}}</span><span>经办人：{{selected.operatorName}}</span><span class="wide">变动原因：{{selected.reason}}</span><span>发生时间：{{selected.occurredAt}}</span></div><el-empty v-else :image-size="48" description="暂无流水"/></section>
</el-card><BusinessDocumentDialog v-model="documentDialog" :type="documentType" :id="documentId"/></div></template>
<style scoped>
.page-heading{margin-bottom:14px}.page-heading h1{margin:0}.page-heading p{margin:6px 0 0;color:#6b7280}.filters{display:flex;gap:9px;align-items:center;margin-bottom:12px;flex-wrap:wrap}.filters .el-input{width:220px}.summary{display:flex;justify-content:flex-end;gap:22px;padding:10px 4px;color:#0f766e;font-weight:600;border-bottom:1px solid #dcdfe6}.inline-detail{padding-top:10px;min-height:138px}.detail-title{margin-bottom:10px}.detail-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:10px 20px;color:#606266;max-height:118px;overflow:auto}.detail-grid .wide{grid-column:span 2}.ledger-page :deep(.el-card__body){padding-bottom:10px}
.document-ledger :deep(.el-table__row){cursor:pointer}
</style>
