<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api} from '../api'
import {localToday} from '../utils/date'
const rows=ref<any[]>([]),detail=ref<any>(),categories=ref<any[]>([]),employees=ref<any[]>([]),loading=ref(false),dialog=ref(false),printPreview=ref(false),saving=ref(false)
const query=reactive({dateFrom:localToday(),dateTo:localToday(),keyword:'',status:'',printStatus:'',sortBy:'date',sortDirection:'asc',page:1,pageSize:100})
const form=reactive<any>({id:null,expenseDate:localToday(),handlerEmployeeId:null,remark:'',version:null,items:[]})
const errorMessage=(e:any)=>e?.response?.data?.message||e?.response?.data?.error||e?.message||'操作失败'
async function load(){loading.value=true;try{const{data}=await api.get('/other-expenses',{params:query});rows.value=data.data.items;if(detail.value){const same=rows.value.find(x=>x.id===detail.value.id);if(!same)detail.value=undefined}}finally{loading.value=false}}
function handleSortChange({prop,order}:{prop:string,order:string}){query.sortBy=prop==='expenseNo'?'documentNo':'date';query.sortDirection=order==='descending'?'desc':'asc';query.page=1;load()}
async function select(row:any){const{data}=await api.get(`/other-expenses/${row.id}`);detail.value=data.data}
function rowClassName({row}:any){return row.status==='VOIDED'?'void-row':''}
function addLine(){form.items.push({categoryCode:'',summary:'',amount:0})}
function openNew(){Object.assign(form,{id:null,expenseDate:localToday(),handlerEmployeeId:null,remark:'',version:null,items:[]});addLine();dialog.value=true}
async function edit(row:any){await select(row);Object.assign(form,{id:detail.value.id,expenseDate:detail.value.expenseDate,handlerEmployeeId:detail.value.handlerEmployeeId,remark:detail.value.remark,version:detail.value.version,items:detail.value.items.map((x:any)=>({categoryCode:x.categoryCode,summary:x.summary,amount:Number(x.amount)}))});dialog.value=true}
async function save(){saving.value=true;try{const editingId=form.id;const payload={expenseDate:form.expenseDate,handlerEmployeeId:form.handlerEmployeeId,remark:form.remark,version:form.version,items:form.items};if(editingId)await api.put(`/other-expenses/${editingId}`,payload);else await api.post('/other-expenses',payload);dialog.value=false;await load();if(editingId){const same=rows.value.find(x=>x.id===editingId);if(same)await select(same)}ElMessage.success('其它支出单已保存')}catch(e){ElMessage.error(errorMessage(e))}finally{saving.value=false}}
async function approve(row:any){await ElMessageBox.confirm(`确认审核 ${row.expenseNo}？审核后不能修改。`,'审核确认',{type:'warning'});try{await api.post(`/other-expenses/${row.id}/approve`,{version:row.version});await load();if(detail.value?.id===row.id)await select(row);ElMessage.success('审核成功')}catch(e){ElMessage.error(errorMessage(e))}}
async function voidExpense(row:any){try{const{value}=await ElMessageBox.prompt('请输入作废原因','作废其它支出单',{inputValidator:v=>!!v||'必须填写原因',type:'warning'});await api.post(`/other-expenses/${row.id}/void`,{version:row.version,reason:value});await load();if(detail.value?.id===row.id)await select(row);ElMessage.success('已作废')}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(errorMessage(e))}}
async function openPrintPreview(row:any){await select(row);printPreview.value=true}
async function printExpense(){if(!detail.value)return;const row={id:detail.value.id};window.print();try{await ElMessageBox.confirm('是否已经成功打印或另存为 PDF？','确认打印结果',{confirmButtonText:'打印成功',cancelButtonText:'打印失败或取消',type:'warning'});await api.post(`/other-expenses/${row.id}/confirm-print`,{version:detail.value.version});await load();await select(row);printPreview.value=true;ElMessage.success('已记录打印状态')}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(errorMessage(e))}}
async function init(){const [c,e]=await Promise.all([api.get('/other-expenses/categories'),api.get('/reference-data/employees',{params:{enabled:true,page:1,pageSize:500}})]);categories.value=c.data.data;employees.value=e.data.data.items||e.data.data;await load()}
onMounted(init)
</script>
<template><div class="expense-page"><div class="page-heading"><div><h1>其它支出</h1><p>现金支出登记；打印与审核互不依赖</p></div><el-button type="primary" @click="openNew">新增其它支出</el-button></div>
<el-card><div class="filters"><el-date-picker v-model="query.dateFrom" type="date" value-format="YYYY-MM-DD"/><span>至</span><el-date-picker v-model="query.dateTo" type="date" value-format="YYYY-MM-DD"/><el-input v-model="query.keyword" clearable placeholder="单据号码 / 经手人 / 备注" @keyup.enter="load"/><el-select v-model="query.status" clearable placeholder="全部状态"><el-option label="草稿" value="DRAFT"/><el-option label="已审核" value="APPROVED"/><el-option label="已作废" value="VOIDED"/></el-select><el-select v-model="query.printStatus" clearable placeholder="全部打印状态"><el-option label="未打印" value="UNPRINTED"/><el-option label="已打印" value="PRINTED"/></el-select><el-button type="primary" @click="load">查询</el-button></div>
<el-table :data="rows" v-loading="loading" height="42vh" highlight-current-row stripe :row-class-name="rowClassName" :default-sort="{prop:'expenseDate',order:'ascending'}" @sort-change="handleSortChange" @row-click="select"><el-table-column prop="expenseNo" label="单据号码" width="155" sortable="custom" :sort-orders="['ascending','descending']"/><el-table-column prop="expenseDate" label="日期" width="115" sortable="custom" :sort-orders="['ascending','descending']"/><el-table-column prop="accountName" label="账户" width="85"/><el-table-column prop="handlerName" label="经手人"/><el-table-column prop="totalAmount" label="总金额" width="120"/><el-table-column prop="createdByName" label="录入人"/><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.status==='VOIDED'?'danger':s.row.status==='APPROVED'?'success':'info'">{{s.row.status==='VOIDED'?'已作废':s.row.status==='APPROVED'?'已审核':'草稿'}}</el-tag></template></el-table-column><el-table-column label="打印状态" width="120"><template #default="s"><el-tag :type="s.row.printedAt?'warning':'info'">{{s.row.printedAt?`已打印 × ${s.row.printCount||1}`:'未打印'}}</el-tag></template></el-table-column><el-table-column label="操作" width="290" fixed="right"><template #default="s"><el-button link type="primary" @click.stop="select(s.row)">详情</el-button><el-button v-if="s.row.status==='DRAFT'&&!s.row.printedAt" link type="primary" @click.stop="edit(s.row)">修改</el-button><el-button v-if="s.row.status!=='VOIDED'" link type="primary" @click.stop="openPrintPreview(s.row)">打印预览</el-button><el-button v-if="s.row.status==='DRAFT'" link type="success" @click.stop="approve(s.row)">审核</el-button><el-button v-if="s.row.status==='DRAFT'&&!s.row.printedAt" link type="danger" @click.stop="voidExpense(s.row)">作废</el-button></template></el-table-column></el-table>
<section class="inline-detail"><div class="detail-title"><strong>{{detail?`其它支出单 ${detail.expenseNo} 明细`:'单击上方单据查看明细'}}</strong><span v-if="detail">合计 ¥{{Number(detail.totalAmount).toFixed(2)}}</span></div><el-table v-if="detail" :data="detail.items" height="190" border><el-table-column prop="lineNo" label="行号" width="70"/><el-table-column prop="categoryCode" label="编号" width="100"/><el-table-column prop="categoryName" label="收支类别" width="210"/><el-table-column prop="summary" label="摘要"/><el-table-column prop="amount" label="金额" width="130"/></el-table><el-empty v-else :image-size="54" description="请选择一张单据"/><div v-if="detail" class="audit-info"><span>备注：{{detail.remark||'—'}}</span><span>录入人：{{detail.createdByName}}　{{detail.createdAt}}</span><span>修改人：{{detail.updatedByName}}　{{detail.updatedAt}}</span><span>审核人：{{detail.approvedByName||'—'}}　{{detail.approvedAt||'—'}}</span><span>打印人：{{detail.printedByName||'—'}}　{{detail.printedAt||'—'}}</span><span v-if="detail.status==='VOIDED'">作废：{{detail.voidedByName||'—'}}　{{detail.voidedAt||'—'}}</span><span v-if="detail.status==='VOIDED'">作废原因：{{detail.voidReason||'—'}}</span></div></section></el-card>
<el-dialog v-model="dialog" :title="form.id?'修改其它支出':'新增其它支出'" width="950px" destroy-on-close><el-form label-width="72px"><div class="header-form"><el-form-item label="日期"><el-date-picker v-model="form.expenseDate" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="账户"><el-input value="现金" disabled/></el-form-item><el-form-item label="经手人"><el-select v-model="form.handlerEmployeeId" clearable filterable><el-option v-for="e in employees" :key="e.id" :label="e.name||e.employeeName" :value="e.id"/></el-select></el-form-item></div><el-table :data="form.items" border max-height="360"><el-table-column type="index" label="行号" width="65"/><el-table-column label="编号 / 收支类别" width="260"><template #default="s"><el-select v-model="s.row.categoryCode" filterable><el-option v-for="c in categories" :key="c.code" :label="`${c.code} ${c.name}`" :value="c.code"/></el-select></template></el-table-column><el-table-column label="摘要"><template #default="s"><el-input v-model="s.row.summary"/></template></el-table-column><el-table-column label="金额" width="160"><template #default="s"><el-input-number v-model="s.row.amount" :min="0" :precision="2" :controls="false"/></template></el-table-column><el-table-column label="操作" width="80"><template #default="s"><el-button link type="danger" @click="form.items.splice(s.$index,1)">删除</el-button></template></el-table-column></el-table><el-button class="add-line" @click="addLine">增加明细</el-button><el-form-item label="备注"><el-input v-model="form.remark"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
<el-dialog v-model="printPreview" :title="`其它支出单打印预览 ${detail?.expenseNo||''}`" width="900px" class="expense-print-dialog"><div v-if="detail" class="expense-print-area"><h2>其 它 支 出 单</h2><div class="print-meta"><span>日期：{{detail.expenseDate}}</span><span>账户：{{detail.accountName}}</span><span>经手人：{{detail.handlerName||'—'}}</span></div><el-table :data="detail.items" border><el-table-column prop="lineNo" label="行号" width="70"/><el-table-column prop="categoryCode" label="编号" width="100"/><el-table-column prop="categoryName" label="收支类别" width="210"/><el-table-column prop="summary" label="摘要"/><el-table-column prop="amount" label="金额" width="130"/></el-table><div class="print-total">合计：¥{{Number(detail.totalAmount).toFixed(2)}}</div><p>备注：{{detail.remark||'—'}}</p></div><template #footer><el-button @click="printPreview=false">关闭</el-button><el-button type="primary" :disabled="!detail||detail.status==='VOIDED'" @click="printExpense">打开系统打印</el-button></template></el-dialog></div></template>
<style scoped>.page-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.page-heading h1{margin:0}.page-heading p{margin:6px 0 0;color:#6b7280}.filters{display:flex;gap:10px;align-items:center;margin-bottom:14px}.filters .el-input{max-width:300px}.filters .el-select{width:150px}.inline-detail{border-top:1px solid #dcdfe6;padding-top:10px}.detail-title{display:flex;justify-content:space-between;margin-bottom:8px}.audit-info{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px;color:#606266}.header-form{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.add-line{margin:10px 0}.expense-page :deep(.el-card__body){padding-bottom:10px}.expense-page :deep(.void-row td){color:#f56c6c!important;background:#fff1f0!important}.expense-print-area h2{text-align:center;letter-spacing:8px}.print-meta{display:flex;justify-content:space-between;margin-bottom:14px}.print-total{text-align:right;margin-top:14px;font-size:18px;font-weight:700}@media print{.page-heading,.filters,.expense-page>.el-card{display:none!important}.expense-print-dialog :deep(.el-dialog__header),.expense-print-dialog :deep(.el-dialog__footer){display:none}}</style>
