<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api'

const router=useRouter(),rows=ref<any[]>([]),total=ref(0),categories=ref<any[]>([]),suggestionGroups=ref<any[]>([]),selected=ref<any[]>([]),parentId=ref<number>(),categoryId=ref<number>(),loading=ref(false),running=ref(false)
const query=reactive({keyword:'',page:1,pageSize:50})
const children=()=>categories.value.find((x:any)=>x.id===parentId.value)?.children||[]
async function load(){loading.value=true;try{const[r,c,g]=await Promise.all([api.get('/product-classification/pending',{params:query}),api.get('/product-categories/tree'),api.get('/product-classification/suggestion-groups')]);rows.value=r.data.data.items;total.value=r.data.data.total;categories.value=c.data.data;suggestionGroups.value=g.data.data}finally{loading.value=false}}
function search(){query.page=1;load()}
function chooseParent(){categoryId.value=undefined}
async function autoClassify(){running.value=true;try{const{data}=await api.post('/product-classification/auto-classify');ElMessage.success(`自动归类 ${data.data.matched} 条，其中内部耗材 ${data.data.internal} 条`);await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'自动归类失败')}finally{running.value=false}}
async function confirm(){if(!selected.value.length)return ElMessage.warning('请先勾选要归类的货品');const target=categoryId.value||parentId.value;if(!target)return ElMessage.warning('请选择厂家或货物小类');try{const{data}=await api.post('/product-classification/confirm',{productIds:selected.value.map(x=>x.id),categoryId:target});ElMessage.success(`已确认 ${data.data.updated} 条`);selected.value=[];await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'归类失败')}}
async function acceptSuggestion(row:any){if(!row.suggestion)return;try{await api.post('/product-classification/confirm',{productIds:[row.id],categoryId:row.suggestion.id});ElMessage.success(`已归入“${row.suggestion.name}”`);await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'采用建议失败')}}
async function confirmSuggestionGroup(group:any){try{await ElMessageBox.confirm(`系统找到 ${group.count} 条建议归入“${group.name}”的待归类货品。确认后将统一归类，此操作不会影响没有建议的货品。`,'批量采用系统建议',{type:'warning',confirmButtonText:`确认归类 ${group.count} 条`,cancelButtonText:'取消'});const{data}=await api.post('/product-classification/confirm-suggestion',{categoryId:group.id});ElMessage.success(`已归类 ${data.data.updated} 条到“${group.name}”`);await load()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.response?.data?.message||'批量采用建议失败')}}
async function confirmAllMatches(){const keyword=query.keyword.trim(),target=categoryId.value||parentId.value;if(keyword.length<2)return ElMessage.warning('先输入至少2个字的明确关键词');if(!target)return ElMessage.warning('请选择厂家或货物小类');if(!total.value)return ElMessage.warning('当前没有匹配的待归类货品');const parent=categories.value.find((x:any)=>x.id===parentId.value),child=children().find((x:any)=>x.id===categoryId.value),name=child?`${parent?.name} → ${child.name}`:parent?.name;try{await ElMessageBox.confirm(`将全部 ${total.value} 条“${keyword}”搜索结果归入“${name}”。请确认关键词足够明确。`,'批量归类确认',{type:'warning',confirmButtonText:'确认归类',cancelButtonText:'取消'});const{data}=await api.post('/product-classification/confirm-matches',{keyword,categoryId:target});ElMessage.success(`已批量归类 ${data.data.updated} 条`);await load()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.response?.data?.message||'批量归类失败')}}
onMounted(load)
</script>
<template><section><div class="page-heading"><div><h1>待归类货品</h1><p>系统只自动匹配名称明确的货品；不确定的在这里勾选后一次归类，避免放错厂家</p></div><div><el-button @click="router.push('/products')">返回按厂家找货品</el-button><el-button type="primary" :loading="running" @click="autoClassify">自动匹配明显货品</el-button></div></div>
<el-alert title="包装空罐、空桶、包装箱、纸箱会自动归为内部耗材，不能加入销售单" type="warning" :closable="false" show-icon/>
<el-card class="classify-card"><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="输入明确关键词，如：双枪酚醛" @keyup.enter="search"/><el-button @click="search">查找</el-button><span class="divider"/><el-select v-model="parentId" placeholder="第一步：选择厂家/大类" filterable @change="chooseParent"><el-option v-for="c in categories" :key="c.id" :value="c.id" :label="`${c.code} ${c.name}`"/></el-select><el-select v-model="categoryId" clearable placeholder="第二步：选择小类（可不选）" filterable><el-option v-for="c in children()" :key="c.id" :value="c.id" :label="`${c.code} ${c.name}`"/></el-select><el-button type="success" @click="confirm">归类所选 {{selected.length}} 条</el-button><el-button type="warning" plain @click="confirmAllMatches">归类全部搜索结果（{{total}} 条）</el-button></div>
<div v-if="suggestionGroups.length" class="suggestion-groups"><strong>可批量确认的系统建议：</strong><span v-for="g in suggestionGroups" :key="g.id" class="suggestion-item"><el-tag type="warning" effect="plain">{{g.name}} {{g.count}} 条</el-tag><el-button link type="primary" @click="confirmSuggestionGroup(g)">批量采用</el-button></span></div><el-table :data="rows" v-loading="loading" stripe @selection-change="selected=$event"><el-table-column type="selection" width="48"/><el-table-column prop="skuCode" label="编号" width="130"/><el-table-column prop="productName" label="品名" min-width="260"/><el-table-column prop="salesUnit" label="单位" width="70"/><el-table-column prop="totalStock" label="库存" width="90"/><el-table-column prop="lastPurchasePrice" label="最近进价" width="100"/><el-table-column prop="wholesalePrice" label="批发价" width="90"/><el-table-column label="系统建议" width="210"><template #default="s"><template v-if="s.row.suggestion"><el-tag type="warning" effect="plain">{{s.row.suggestion.name}}</el-tag><el-button link type="primary" @click="acceptSuggestion(s.row)">采用建议</el-button></template><span v-else class="no-suggestion">暂无可靠建议</span></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :page-size="query.pageSize" :total="total" layout="total, prev, pager, next" @current-change="load"/></el-card></section></template>
<style scoped>.classify-card{margin-top:16px}.toolbar{display:flex;gap:10px;align-items:center;margin-bottom:14px;flex-wrap:wrap}.toolbar>.el-input{width:230px}.toolbar>.el-select{width:230px}.divider{width:1px;height:28px;background:#dcdfe6;margin:0 4px}.no-suggestion{color:#909399;font-size:13px}.suggestion-groups{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:0 0 14px;padding:10px 12px;background:#fff8e8;border:1px solid #f3d19e;border-radius:6px}.suggestion-item{display:inline-flex;align-items:center;gap:2px}</style>
