<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api'
const route=useRoute(),rows=ref<any[]>([]),total=ref(0),loading=ref(false),detail=ref(false),dialog=ref(false),editing=ref(false),current=ref<any>({}),options=reactive({types:[] as any[],departments:[] as any[]}),query=reactive({keyword:'',enabled:'',page:1,pageSize:20})
const empty=()=>({id:0,code:'',name:'',phone:'',mobile:'',fax:'',address:'',remark:'',plateNo:'',vehicleType:'',gender:'',employeeTypeId:null,departmentId:null,positionName:'',education:'',idCard:'',salesperson:false,hometown:'',postalCode:'',hireDate:'',version:0})
const form=reactive<any>(empty())
const simple=(title:string,singular:string)=>({title,singular,hint:`按${singular}编号、名称或备注查询`,columns:[['code',`${singular}编号`,160],['name',`${singular}名称`,240],['remark','备注',320]],details:[['code',`${singular}编号`],['name',`${singular}名称`],['remark','备注']]})
const configs:any={suppliers:{title:'供应商资料',singular:'供应商',hint:'按供应商编号、名称或电话查询',columns:[['code','供应商编号',130],['name','供应商名称',220],['phone','电话',160],['mobile','手机',140],['address','地址',260]],details:[['code','供应商编号'],['name','供应商名称'],['phone','电话'],['mobile','手机'],['fax','传真'],['address','地址'],['remark','备注']]},employees:{title:'员工资料',singular:'员工',hint:'按员工编号、姓名、电话、类别或部门查询',columns:[['code','员工编号',120],['name','员工姓名',140],['typeName','员工类别',140],['departmentName','部门',140],['positionName','职务',140],['phone','电话',150]],details:[['code','员工编号'],['name','员工姓名'],['gender','性别'],['phone','电话'],['typeName','员工类别'],['departmentName','部门'],['positionName','职务'],['education','学历'],['idCard','身份证（已脱敏）'],['address','地址'],['hometown','籍贯'],['hireDate','入职日期'],['remark','备注']]},vehicles:{title:'车辆资料',singular:'车辆',hint:'按车辆编号、车牌或车辆类型查询',columns:[['code','车辆编号',140],['plateNo','车牌号',160],['vehicleType','车辆类型',180],['remark','备注',260]],details:[['code','车辆编号'],['plateNo','车牌号'],['vehicleType','车辆类型'],['remark','备注']]},'employee-types':simple('员工类别','类别'),departments:simple('部门资料','部门'),routes:simple('路线资料','路线')}
const kind=computed(()=>String(route.meta.kind)),config=computed(()=>configs[kind.value])
const canManage=computed(()=>(localStorage.getItem('role')||'ADMIN')==='ADMIN')
async function load(){loading.value=true;try{const{data}=await api.get(`/reference-data/${kind.value}`,{params:{keyword:query.keyword,enabled:query.enabled===''?undefined:query.enabled,page:query.page,pageSize:query.pageSize}});rows.value=data.data.items;total.value=data.data.total}catch(e:any){ElMessage.error(e.response?.data?.message||'资料加载失败')}finally{loading.value=false}}
async function loadOptions(){if(kind.value!=='employees')return;const{data}=await api.get('/reference-data/employee-options');options.types=data.data.types;options.departments=data.data.departments}
function search(){query.page=1;load()} function show(row:any){current.value=row;detail.value=true}
function add(){Object.assign(form,empty());editing.value=false;dialog.value=true}
function edit(row:any){Object.assign(form,empty(),row,{idCard:''});editing.value=true;dialog.value=true}
async function save(){if(!form.code.trim()||(kind.value!=='vehicles'&&!form.name.trim()))return ElMessage.warning('编号和名称不能为空');try{editing.value?await api.put(`/reference-data/${kind.value}/${form.id}`,form):await api.post(`/reference-data/${kind.value}`,form);ElMessage.success('保存成功');dialog.value=false;load()}catch(e:any){ElMessage.error(e.response?.data?.message||'保存失败，请检查编号是否重复')}}
async function toggle(row:any){const action=row.enabled?'停用':'恢复使用';await ElMessageBox.confirm(`确定${action}“${row.name||row.plateNo||row.code}”吗？`,`${action}确认`,{type:row.enabled?'warning':'info'});await api.patch(`/reference-data/${kind.value}/${row.id}/enabled`,{enabled:!row.enabled,version:row.version??0});ElMessage.success(`${action}成功`);load()}
async function remove(row:any){await ElMessageBox.confirm(`确定永久删除“${row.name||row.plateNo||row.code}”吗？删除后不能恢复。`,'删除确认',{type:'error',confirmButtonText:'永久删除'});try{await api.delete(`/reference-data/${kind.value}/${row.id}`);ElMessage.success('删除成功');load()}catch(e:any){ElMessage.error(e.response?.data?.message||'该资料已被业务单据使用，不能删除；可以改为停用')}}
watch(kind,()=>{Object.assign(query,{keyword:'',enabled:'',page:1,pageSize:20});load();loadOptions()},{immediate:true})
</script>
<template><section><div class="page-heading"><div><h1>{{config.title}}</h1><p>{{config.hint}}</p></div><el-button v-if="canManage" type="primary" @click="add">新增{{config.singular}}</el-button></div><el-card><div class="toolbar"><el-input v-model="query.keyword" clearable :placeholder="config.hint" @keyup.enter="search"/><el-select v-model="query.enabled" style="width:130px"><el-option label="全部状态" value=""/><el-option label="使用中" :value="true"/><el-option label="已停用" :value="false"/></el-select><el-button type="primary" @click="search">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column v-for="c in config.columns" :key="c[0]" :prop="c[0]" :label="c[1]" :width="c[2]" show-overflow-tooltip/><el-table-column v-if="kind==='employees'" label="业务员" width="80"><template #default="s">{{s.row.salesperson?'是':'否'}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.enabled?'success':'info'">{{s.row.enabled?'使用中':'已停用'}}</el-tag></template></el-table-column><el-table-column label="操作" :width="canManage?220:80" fixed="right"><template #default="s"><el-button link type="primary" @click="show(s.row)">查看</el-button><template v-if="canManage"><el-button link type="primary" @click="edit(s.row)">编辑</el-button><el-button link :type="s.row.enabled?'warning':'success'" @click="toggle(s.row)">{{s.row.enabled?'停用':'恢复'}}</el-button><el-button link type="danger" @click="remove(s.row)">删除</el-button></template></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :page-size="query.pageSize" :total="total" layout="total, prev, pager, next" @current-change="load"/></el-card>
<el-drawer v-model="detail" :title="config.title+'详情'" size="480px"><el-descriptions :column="1" border><el-descriptions-item v-for="d in config.details" :key="d[0]" :label="d[1]">{{current[d[0]]||'—'}}</el-descriptions-item><el-descriptions-item v-if="kind==='employees'" label="业务员">{{current.salesperson?'是':'否'}}</el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="current.enabled?'success':'info'">{{current.enabled?'使用中':'已停用'}}</el-tag></el-descriptions-item></el-descriptions></el-drawer>
<el-dialog v-model="dialog" :title="(editing?'编辑':'新增')+config.singular" width="680px"><el-form label-width="100px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="编号" required><el-input v-model="form.code"/></el-form-item></el-col><el-col v-if="kind!=='vehicles'" :span="12"><el-form-item label="名称" required><el-input v-model="form.name"/></el-form-item></el-col>
<template v-if="kind==='suppliers'"><el-col :span="12"><el-form-item label="电话"><el-input v-model="form.phone"/></el-form-item></el-col><el-col :span="12"><el-form-item label="手机"><el-input v-model="form.mobile"/></el-form-item></el-col><el-col :span="12"><el-form-item label="传真"><el-input v-model="form.fax"/></el-form-item></el-col><el-col :span="24"><el-form-item label="地址"><el-input v-model="form.address"/></el-form-item></el-col></template>
<template v-if="kind==='vehicles'"><el-col :span="12"><el-form-item label="车牌号"><el-input v-model="form.plateNo"/></el-form-item></el-col><el-col :span="12"><el-form-item label="车辆类型"><el-input v-model="form.vehicleType"/></el-form-item></el-col></template>
<template v-if="kind==='employees'"><el-col :span="12"><el-form-item label="电话"><el-input v-model="form.phone"/></el-form-item></el-col><el-col :span="12"><el-form-item label="性别"><el-select v-model="form.gender" clearable><el-option label="男" value="男"/><el-option label="女" value="女"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="员工类别"><el-select v-model="form.employeeTypeId" clearable><el-option v-for="o in options.types" :key="o.id" :label="o.name" :value="o.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="部门"><el-select v-model="form.departmentId" clearable><el-option v-for="o in options.departments" :key="o.id" :label="o.name" :value="o.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="职务"><el-input v-model="form.positionName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="入职日期"><el-date-picker v-model="form.hireDate" value-format="YYYY-MM-DD" type="date"/></el-form-item></el-col><el-col :span="12"><el-form-item label="身份证"><el-input v-model="form.idCard" :placeholder="editing?'留空则保留原号码':''"/></el-form-item></el-col><el-col :span="12"><el-form-item label="业务员"><el-switch v-model="form.salesperson"/></el-form-item></el-col><el-col :span="24"><el-form-item label="地址"><el-input v-model="form.address"/></el-form-item></el-col></template>
<el-col :span="24"><el-form-item label="备注"><el-input v-model="form.remark" type="textarea"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></section></template>
