<script setup lang="ts">
import {computed,nextTick,onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api} from '../api'
import {localToday} from '../utils/date'

const today=localToday
const query=reactive({dateFrom:today(),dateTo:today(),keyword:'',status:'',printStatus:'',sortBy:'date',sortDirection:'asc'})
const rows=ref<any[]>([]), selected=ref<any>(), loading=ref(false), saving=ref(false), dialog=ref(false), printPreview=ref(false), editingId=ref<number|null>(null), editingVersion=ref(0)
const customers=ref<any[]>([]), products=ref<any[]>([]), salespeople=ref<any[]>([]), sourceOrders=ref<any[]>([])
const productId=ref<any>(), sourceOrderId=ref<any>()
const form=reactive<any>({returnDate:today(),sourceSalesOrderId:null,customerId:null,salespersonId:null,settlementMethod:'现金',remark:'',items:[]})
const total=computed(()=>form.items.reduce((s:number,x:any)=>s+Number(x.quantity||0)*Number(x.unitPrice||0),0))
const statusText=(s:string)=>({DRAFT:'草稿',APPROVED:'已审核/已入仓',VOIDED:'已作废'} as any)[s]||s
async function load(){loading.value=true;try{const{data}=await api.get('/sales-returns',{params:query});rows.value=data.data||[]}finally{loading.value=false}}
function handleSortChange({prop,order}:{prop:string,order:string}){query.sortBy=prop==='returnNo'?'documentNo':'date';query.sortDirection=order==='descending'?'desc':'asc';load()}
async function select(row:any){if(!row)return;const{data}=await api.get(`/sales-returns/${row.id}`);selected.value=data.data}
async function viewReturn(row:any){await select(row);const d=selected.value;const lines=(d.items||[]).map((x:any)=>`<tr><td>${x.skuCode}</td><td>${x.productName}</td><td>${x.quantity}</td><td>${x.unit}</td><td>${Number(x.unitPrice).toFixed(2)}</td><td>${Number(x.lineAmount).toFixed(2)}</td></tr>`).join('');await ElMessageBox.alert(`<div class="document-view"><p>日期：${d.returnDate}　客户：${d.customerCode} ${d.customerName}　业务员：${d.salespersonName||'—'}</p><table><thead><tr><th>编号</th><th>品名规格</th><th>数量</th><th>单位</th><th>单价</th><th>金额</th></tr></thead><tbody>${lines}</tbody></table><p>合计：¥${Number(d.totalAmount).toFixed(2)}　备注：${d.remark||'—'}</p></div>`,`销售退货单 ${d.returnNo}`,{dangerouslyUseHTMLString:true,customClass:'document-view-dialog',confirmButtonText:'关闭'})}
async function focusNewReturn(returnNo:string){await nextTick();const row=Array.from(document.querySelectorAll('.sales-return-table .el-table__body-wrapper tbody tr')).find(x=>x.textContent?.includes(returnNo));if(!row)return;row.classList.add('newly-created-row');row.scrollIntoView({behavior:'smooth',block:'center'});window.setTimeout(()=>row.classList.remove('newly-created-row'),5000)}
async function loadOptions(){const [c,p,e,o]=await Promise.all([api.get('/customers',{params:{pageSize:500,enabled:true}}),api.get('/products',{params:{pageSize:500,enabled:true,saleable:true}}),api.get('/employees',{params:{pageSize:500,enabled:true}}),api.get('/sales-orders',{params:{dateFrom:'2020-01-01',dateTo:today(),pageSize:100,returnableOnly:true,sortBy:'date',sortDirection:'desc'}})]);customers.value=c.data.data.items;products.value=p.data.data.items;salespeople.value=(e.data.data.items||e.data.data).filter((x:any)=>x.salesperson);sourceOrders.value=o.data.data.items||[]}
async function openNew(){const{data}=await api.get('/sales-orders',{params:{dateFrom:'2020-01-01',dateTo:today(),pageSize:100,returnableOnly:true,sortBy:'date',sortDirection:'desc'}});sourceOrders.value=data.data.items||[];editingId.value=null;editingVersion.value=0;Object.assign(form,{returnDate:today(),sourceSalesOrderId:null,customerId:null,salespersonId:null,settlementMethod:'现金',remark:'',items:[]});sourceOrderId.value=null;dialog.value=true}
async function openEdit(row:any){if(row.status!=='DRAFT'||row.printedAt||row.warehouseId)return ElMessage.warning('只有未打印、未入仓的草稿销售退货单可以编辑');const{data}=await api.get(`/sales-returns/${row.id}`);const d=data.data;editingId.value=d.id;editingVersion.value=d.version;Object.assign(form,{returnDate:d.returnDate,sourceSalesOrderId:d.sourceSalesOrderId??null,customerId:d.customerId,salespersonId:d.salespersonId??null,settlementMethod:d.settlementMethod||'现金',remark:d.remark||'',items:(d.items||[]).map((x:any)=>({...x,quantity:Number(x.quantity),unitPrice:Number(x.unitPrice),referencePrice:Number(x.referencePrice||0)}))});sourceOrderId.value=d.sourceSalesOrderId??null;if(d.sourceSalesOrderId&&!sourceOrders.value.some((x:any)=>x.id===d.sourceSalesOrderId)){const{data:source}=await api.get(`/sales-orders/${d.sourceSalesOrderId}`);sourceOrders.value.push(source.data)}dialog.value=true}
async function importOrder(){if(!sourceOrderId.value)return;const{data}=await api.get(`/sales-orders/${sourceOrderId.value}`);const d=data.data;form.sourceSalesOrderId=d.id;form.customerId=d.customerId;form.salespersonId=d.salespersonId;form.settlementMethod=d.settlementMethod||'现金';const sourceItems=d.items||[];form.items=sourceItems.filter((x:any)=>Number(x.remainingReturnQuantity)>0).map((x:any)=>({sourceSalesOrderItemId:x.id,skuId:x.skuId,skuCode:x.skuCode,productName:x.productName,quantity:Number(x.remainingReturnQuantity),soldQuantity:Number(x.quantity),returnedQuantity:Number(x.returnedQuantity||0),unit:x.salesUnit,unitPrice:Number(x.unitPrice),referencePrice:Number(x.referencePrice),remark:''}));const adjusted=sourceItems.filter((x:any)=>Number(x.returnedQuantity||0)>0).length;if(!form.items.length)return ElMessage.warning('该销售单的货品已经全部退完，没有可退数量');if(adjusted)ElMessage.warning(`已按剩余可退数量导入，${adjusted} 条货品已有退货记录`)}
function addProduct(){const p=products.value.find(x=>x.id===productId.value);if(!p||form.items.some((x:any)=>x.skuId===p.id))return;form.items.push({sourceSalesOrderItemId:null,skuId:p.id,skuCode:p.skuCode,productName:p.productName,quantity:1,unit:p.salesUnit,unitPrice:Number(p.wholesalePrice||0),referencePrice:Number(p.wholesalePrice||0),remark:''});productId.value=null}
async function save(){if(saving.value)return;if(!form.customerId||!form.items.length)return ElMessage.warning('请选择客户并添加退货货品');saving.value=true;const payload={...form,items:form.items.map((x:any)=>({sourceSalesOrderItemId:x.sourceSalesOrderItemId,skuId:x.skuId,quantity:x.quantity,unitPrice:x.unitPrice,remark:x.remark}))};try{const{data}=editingId.value?await api.put(`/sales-returns/${editingId.value}`,{version:editingVersion.value,data:payload}):await api.post('/sales-returns',payload);const changedId=editingId.value;const returnNo=data.data?.returnNo;dialog.value=false;await load();if(changedId){const row=rows.value.find((x:any)=>x.id===changedId);if(row)await select(row)}else if(returnNo){await focusNewReturn(returnNo)}ElMessage({type:'success',message:changedId?'销售退货单草稿已修改':`销售退货单 ${returnNo} 已保存，已为你定位并高亮`,duration:5000,showClose:true})}catch(e:any){ElMessage.error(e.response?.data?.message||'销售退货单保存失败，请检查退货数量')}finally{saving.value=false}}
async function openPrintPreview(row:any){await select(row);printPreview.value=true}
async function printReturn(){if(!selected.value)return;const row={id:selected.value.id};window.print();try{await ElMessageBox.confirm('是否已经成功打印或另存为 PDF？','确认打印结果',{confirmButtonText:'打印成功',cancelButtonText:'打印失败或取消'});await api.post(`/sales-returns/${row.id}/confirm-print`,{version:selected.value.version});await load();await select(row);printPreview.value=true;ElMessage.success('已记录打印状态')}catch(e:any){if(e!=='cancel'&&e!=='close')throw e}}
async function voidReturn(row:any){const{value}=await ElMessageBox.prompt('请输入作废原因','作废销售退货单',{inputValidator:v=>!!v||'必须填写原因',type:'warning'});await api.post(`/sales-returns/${row.id}/void`,{version:row.version,reason:value});await load();selected.value=undefined;ElMessage.success('已作废')}
onMounted(()=>{load();loadOptions()})
</script>

<template><section class="page"><header><div><h1>销售退货</h1><p>退货单审核由“退货入仓”完成；入仓审核后才增加库存。</p></div><el-button type="primary" @click="openNew">新建销售退货单</el-button></header>
<el-card><el-form inline><el-form-item label="日期"><el-date-picker v-model="query.dateFrom" value-format="YYYY-MM-DD"/><span class="sep">至</span><el-date-picker v-model="query.dateTo" value-format="YYYY-MM-DD"/></el-form-item><el-form-item><el-input v-model="query.keyword" clearable placeholder="退货单号 / 客户编号 / 客户名称" @keyup.enter="load"/></el-form-item><el-form-item><el-select v-model="query.status" clearable placeholder="全部审核状态"><el-option label="未审核" value="DRAFT"/><el-option label="已审核" value="APPROVED"/><el-option label="已作废" value="VOIDED"/></el-select></el-form-item><el-form-item><el-select v-model="query.printStatus" clearable placeholder="全部打印状态"><el-option label="未打印" value="UNPRINTED"/><el-option label="已打印" value="PRINTED"/></el-select></el-form-item><el-button type="primary" @click="load">查询</el-button></el-form>
<div class="split"><div class="upper"><el-table :data="rows" v-loading="loading" highlight-current-row class="sales-return-table" :default-sort="{prop:'returnDate',order:'ascending'}" @sort-change="handleSortChange" @current-change="select" @row-dblclick="viewReturn"><el-table-column prop="returnNo" label="退货单号" width="145" sortable="custom" :sort-orders="['ascending','descending']"/><el-table-column prop="returnDate" label="日期" width="110" sortable="custom" :sort-orders="['ascending','descending']"/><el-table-column prop="customerCode" label="客户编号" width="110"/><el-table-column prop="customerName" label="客户名称" min-width="180"/><el-table-column prop="salespersonName" label="业务员" width="100"/><el-table-column prop="totalAmount" label="金额" width="110"/><el-table-column label="状态" width="150"><template #default="{row}"><el-tag :type="row.status==='APPROVED'?'success':row.status==='VOIDED'?'danger':row.warehouseId?'warning':'info'">{{row.status==='DRAFT'&&row.warehouseId?'已加入入仓单':statusText(row.status)}}</el-tag></template></el-table-column><el-table-column label="打印状态" width="120"><template #default="{row}"><el-tag :type="row.printedAt?'warning':'info'">{{row.printedAt?`已打印 × ${row.printCount||1}`:'未打印'}}</el-tag></template></el-table-column><el-table-column label="操作" width="230" fixed="right"><template #default="{row}"><el-button v-if="row.status==='DRAFT'&&!row.printedAt&&!row.warehouseId" link type="primary" @click.stop="openEdit(row)">编辑</el-button><el-button link type="primary" @click.stop="openPrintPreview(row)">打印预览</el-button><el-button v-if="row.status==='DRAFT'&&!row.printedAt&&!row.warehouseId" link type="danger" @click.stop="voidReturn(row)">作废</el-button></template></el-table-column></el-table></div>
<div class="lower"><div v-if="selected"><b>{{selected.returnNo}}</b>　客户：{{selected.customerCode}} {{selected.customerName}}　合计：¥{{Number(selected.totalAmount).toFixed(2)}}　状态：{{statusText(selected.status)}}<el-table :data="selected.items" size="small" max-height="190"><el-table-column prop="skuCode" label="编号" width="110"/><el-table-column prop="productName" label="品名规格" min-width="230"/><el-table-column prop="quantity" label="数量" width="90"/><el-table-column prop="unit" label="单位" width="70"/><el-table-column prop="unitPrice" label="单价" width="90"/><el-table-column prop="lineAmount" label="金额" width="100"/><el-table-column prop="remark" label="备注"/></el-table><div class="audit">录入时间：{{selected.createdAt}}　审核时间：{{selected.approvedAt||'—'}}　打印时间：{{selected.printedAt||'—'}}</div></div><el-empty v-else description="单击上方销售退货单查看货品" :image-size="45"/></div></div></el-card>
<el-dialog v-model="dialog" :title="editingId?'编辑销售退货单草稿':'新建销售退货单'" width="1050px"><el-form label-width="80"><el-row :gutter="12"><el-col :span="5"><el-form-item label="退货日期"><el-date-picker v-model="form.returnDate" value-format="YYYY-MM-DD"/></el-form-item></el-col><el-col :span="8"><el-form-item label="原销售单"><el-select v-model="sourceOrderId" filterable clearable :disabled="!!editingId" placeholder="可选：选择后导入"><el-option v-for="x in sourceOrders" :key="x.id" :label="`${x.orderNo} ${x.customerName||''}`" :value="x.id"/></el-select></el-form-item></el-col><el-col :span="3"><el-button :disabled="!!editingId" @click="importOrder">导入</el-button></el-col><el-col :span="8"><el-form-item label="客户"><el-select v-model="form.customerId" filterable><el-option v-for="x in customers" :key="x.id" :label="`${x.customerCode} ${x.shortName}`" :value="x.id"/></el-select></el-form-item></el-col></el-row><el-row :gutter="12"><el-col :span="8"><el-form-item label="业务员"><el-select v-model="form.salespersonId" clearable><el-option v-for="x in salespeople" :key="x.id" :label="x.name" :value="x.id"/></el-select></el-form-item></el-col><el-col :span="13"><el-form-item label="添加货品"><el-select v-model="productId" filterable><el-option v-for="x in products" :key="x.id" :label="`${x.skuCode} ${x.productName}`" :value="x.id"/></el-select></el-form-item></el-col><el-col :span="3"><el-button type="primary" @click="addProduct">加入</el-button></el-col></el-row></el-form><el-table :data="form.items" max-height="330"><el-table-column prop="skuCode" label="编号" width="105"/><el-table-column prop="productName" label="品名规格" min-width="230"/><el-table-column label="数量" width="125"><template #default="{row}"><el-input-number v-model="row.quantity" :min="0.0001" :controls="false"/></template></el-table-column><el-table-column prop="unit" label="单位" width="65"/><el-table-column label="退货单价" width="125"><template #default="{row}"><el-input-number v-model="row.unitPrice" :min="0" :controls="false"/></template></el-table-column><el-table-column label="金额" width="100"><template #default="{row}">{{(row.quantity*row.unitPrice).toFixed(2)}}</template></el-table-column><el-table-column label="备注"><template #default="{row}"><el-input v-model="row.remark"/></template></el-table-column><el-table-column label="操作" width="70"><template #default="{$index}"><el-button link type="danger" @click="form.items.splice($index,1)">删除</el-button></template></el-table-column></el-table><div class="sum">合计：¥{{total.toFixed(2)}}</div><el-input v-model="form.remark" placeholder="备注"/><template #footer><el-button :disabled="saving" @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">{{editingId?'保存修改':'保存草稿'}}</el-button></template></el-dialog>
<el-dialog v-model="printPreview" :title="`销售退货单打印预览 ${selected?.returnNo||''}`" width="980px" class="return-print-dialog"><div v-if="selected" class="return-print-area"><h2>销 售 退 货 单</h2><div class="print-meta"><span>日期：{{selected.returnDate}}</span><span>客户：{{selected.customerCode}} {{selected.customerName}}</span><span>业务员：{{selected.salespersonName||'—'}}</span></div><el-table :data="selected.items" border><el-table-column prop="skuCode" label="编号" width="120"/><el-table-column prop="productName" label="品名规格" min-width="260"/><el-table-column prop="quantity" label="数量" width="90"/><el-table-column prop="unit" label="单位" width="75"/><el-table-column prop="unitPrice" label="单价" width="100"/><el-table-column prop="lineAmount" label="金额" width="110"/><el-table-column prop="remark" label="备注"/></el-table><div class="print-total">合计：¥{{Number(selected.totalAmount).toFixed(2)}}</div><p>备注：{{selected.remark||'—'}}</p></div><template #footer><el-button @click="printPreview=false">关闭</el-button><el-button type="primary" :disabled="!selected||selected.status==='VOIDED'" @click="printReturn">打开系统打印</el-button></template></el-dialog></section></template>
<style scoped>.page{padding:16px}.sales-return-table :deep(.el-table__row){cursor:pointer}.sales-return-table :deep(.newly-created-row>td.el-table__cell){background:#fff3bf!important;transition:background-color 1s ease}.sales-return-table :deep(.newly-created-row>td.el-table__cell:first-child){box-shadow:inset 4px 0 #e6a23c}header{display:flex;justify-content:space-between;align-items:center}h1{margin:0}header p{color:#667085}.sep{margin:0 8px}.split{height:calc(100vh - 265px);min-height:470px;display:grid;grid-template-rows:minmax(250px,1fr) 245px;gap:10px}.upper,.lower{overflow:auto;border:1px solid #e5e7eb}.lower{padding:10px}.sum{text-align:right;font-size:20px;font-weight:700;color:#087b65;margin:12px}.audit{padding:8px;color:#667085}.return-print-area h2{text-align:center;letter-spacing:8px}.print-meta{display:flex;justify-content:space-between;margin-bottom:14px}.print-total{text-align:right;margin-top:14px;font-size:18px;font-weight:700}@media print{header,.el-form,.upper{display:none}.split{display:block;height:auto}.lower{border:0}.return-print-dialog :deep(.el-dialog__header),.return-print-dialog :deep(.el-dialog__footer){display:none}}</style>
