<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api'
const rows=ref<any[]>([]),total=ref(0),loading=ref(false),dialog=ref(false),resetDialog=ref(false),editing=ref(false),query=reactive({keyword:'',page:1,pageSize:20})
const empty=()=>({id:0,username:'',displayName:'',role:'SALES',password:'',version:0}),form=reactive<any>(empty()),passwordForm=reactive({id:0,password:'',version:0})
const roles=[['ADMIN','管理员'],['SALES','销售员'],['WAREHOUSE','仓库人员'],['DISPATCH','调度人员']],roleName=(v:string)=>roles.find(r=>r[0]===v)?.[1]||v
async function load(){loading.value=true;try{const{data}=await api.get('/users',{params:query});rows.value=data.data.items;total.value=data.data.total}finally{loading.value=false}}
function search(){query.page=1;load()} function add(){Object.assign(form,empty());editing.value=false;dialog.value=true} function edit(row:any){Object.assign(form,empty(),row);editing.value=true;dialog.value=true}
async function save(){if(!form.username&&!editing.value)return ElMessage.warning('请输入用户名');if(!form.displayName)return ElMessage.warning('请输入显示姓名');try{editing.value?await api.put(`/users/${form.id}`,form):await api.post('/users',form);ElMessage.success('保存成功');dialog.value=false;load()}catch(e:any){ElMessage.error(e.response?.data?.message||'保存失败，请检查用户名和密码格式')}}
async function toggle(row:any){const action=row.enabled?'停用':'恢复';await ElMessageBox.confirm(`确定${action}账号“${row.displayName}”吗？`,`${action}确认`,{type:'warning'});try{await api.patch(`/users/${row.id}/enabled`,{enabled:!row.enabled,version:row.version});ElMessage.success(`${action}成功`);load()}catch(e:any){ElMessage.error(e.response?.data?.message||'操作失败')}}
function reset(row:any){Object.assign(passwordForm,{id:row.id,password:'',version:row.version});resetDialog.value=true} async function savePassword(){try{await api.patch(`/users/${passwordForm.id}/password`,passwordForm);ElMessage.success('密码已重置，该账号下次登录必须修改密码');resetDialog.value=false;load()}catch(e:any){ElMessage.error(e.response?.data?.message||'密码至少8位，并同时包含字母和数字')}}
async function unlock(row:any){await ElMessageBox.confirm(`确定解锁账号“${row.displayName}”吗？`,'解锁确认',{type:'warning'});try{await api.patch(`/users/${row.id}/unlock`,{version:row.version});ElMessage.success('账号已解锁');load()}catch(e:any){ElMessage.error(e.response?.data?.message||'解锁失败')}}
onMounted(load)
</script>
<template><section><div class="page-heading"><div><h1>用户账号</h1><p>创建内部账号、分配角色、停用账号、解锁账号和重置密码</p></div><el-button type="primary" @click="add">新增账号</el-button></div><el-card><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="用户名 / 姓名 / 角色" @keyup.enter="search"/><el-button type="primary" @click="search">查询</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="username" label="用户名" width="170"/><el-table-column prop="displayName" label="显示姓名" width="160"/><el-table-column label="角色" width="120"><template #default="s">{{roleName(s.row.role)}}</template></el-table-column><el-table-column label="登录安全" width="190"><template #default="s"><el-tag v-if="s.row.locked" type="danger">已锁定（输错10次）</el-tag><el-tag v-else-if="!s.row.enabled" type="info">已停用</el-tag><el-tag v-else-if="s.row.mustChangePassword" type="warning">首次登录需改密码</el-tag><el-tag v-else type="success">正常</el-tag><small v-if="!s.row.locked&&s.row.failedLoginAttempts" class="attempts">已输错 {{s.row.failedLoginAttempts }} 次</small></template></el-table-column><el-table-column prop="updatedAt" label="最后更新" min-width="185"/><el-table-column label="操作" width="305"><template #default="s"><el-button link type="primary" @click="edit(s.row)">编辑</el-button><el-button link type="primary" @click="reset(s.row)">重置密码</el-button><el-button v-if="s.row.locked" link type="warning" @click="unlock(s.row)">解锁</el-button><el-button link :type="s.row.enabled?'danger':'success'" @click="toggle(s.row)">{{s.row.enabled?'停用':'恢复'}}</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :page-size="query.pageSize" :total="total" layout="total, prev, pager, next" @current-change="load"/></el-card>
<el-dialog v-model="dialog" :title="editing?'编辑账号':'新增账号'" width="520px"><el-form label-width="90px"><el-form-item v-if="!editing" label="用户名" required><el-input v-model="form.username" maxlength="64" placeholder="字母、数字、点、横线或下划线"/></el-form-item><el-form-item label="显示姓名" required><el-input v-model="form.displayName" maxlength="100"/></el-form-item><el-form-item label="角色" required><el-select v-model="form.role"><el-option v-for="r in roles" :key="r[0]" :value="r[0]" :label="r[1]"/></el-select></el-form-item><el-form-item v-if="!editing" label="初始密码" required><el-input v-model="form.password" type="password" show-password placeholder="至少8位，包含字母和数字"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
<el-dialog v-model="resetDialog" title="重置密码" width="460px"><el-alert title="重置后，该账号下次登录必须修改密码" type="warning" :closable="false"/><el-form label-width="90px" style="margin-top:18px"><el-form-item label="新密码" required><el-input v-model="passwordForm.password" type="password" show-password placeholder="至少8位，包含字母和数字"/></el-form-item></el-form><template #footer><el-button @click="resetDialog=false">取消</el-button><el-button type="primary" @click="savePassword">确认重置</el-button></template></el-dialog></section></template>
<style scoped>.attempts{display:block;color:#c45656;margin-top:4px}</style>
