package com.sunny.paintfactory.sales;

import com.sunny.paintfactory.common.ApiResponse;
import com.sunny.paintfactory.common.PageResult;
import com.sunny.paintfactory.common.DocumentSort;
import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

@RestController
@RequestMapping("/api/v1/sales-orders")
public class SalesOrderController {
    private final JdbcTemplate jdbc;
    public SalesOrderController(JdbcTemplate jdbc){this.jdbc=jdbc;}

    @GetMapping
    public ApiResponse<PageResult<Map<String,Object>>> list(@RequestParam(defaultValue="") String keyword,@RequestParam(defaultValue="") String status,@RequestParam(defaultValue="") String workflowStatus,@RequestParam(defaultValue="") String dateFrom,@RequestParam(defaultValue="") String dateTo,@RequestParam(defaultValue="") String salesperson,@RequestParam(defaultValue="") String recorder,@RequestParam(defaultValue="") String settlementMethod,@RequestParam(defaultValue="false") boolean returnableOnly,@RequestParam(required=false) BigDecimal minAmount,@RequestParam(required=false) BigDecimal maxAmount,@RequestParam(defaultValue="date") String sortBy,@RequestParam(defaultValue="asc") String sortDirection,@RequestParam(defaultValue="1") int page,@RequestParam(defaultValue="20") int pageSize){
        int p=Math.max(1,page),size=Math.min(100,Math.max(1,pageSize));String normalizedKeyword=keyword.trim(),like="%"+normalizedKeyword+"%",prefixLike=normalizedKeyword+"%";
        StringBuilder where=new StringBuilder("(s.order_no LIKE ? OR s.customer_code_snapshot LIKE ? OR s.customer_name_snapshot LIKE ?)");List<Object> args=new ArrayList<>(List.of(like,like,like));
        if(!status.isBlank()){where.append(" AND s.status=?");args.add(status);}
        if(!dateFrom.isBlank()){where.append(" AND s.order_date>=?");args.add(LocalDate.parse(dateFrom));}
        if(!dateTo.isBlank()){where.append(" AND s.order_date<=?");args.add(LocalDate.parse(dateTo));}
        if(!salesperson.isBlank()){where.append(" AND COALESCE(s.salesperson_name_snapshot,'') LIKE ?");args.add("%"+salesperson.trim()+"%");}
        if(!recorder.isBlank()){where.append(" AND EXISTS(SELECT 1 FROM sys_user ru WHERE ru.id=s.created_by AND (ru.username LIKE ? OR ru.display_name LIKE ?))");args.add("%"+recorder.trim()+"%");args.add("%"+recorder.trim()+"%");}
        if(!settlementMethod.isBlank()){where.append(" AND s.settlement_method=?");args.add(settlementMethod);}
        if(minAmount!=null){where.append(" AND s.total_amount>=?");args.add(minAmount);}
        if(maxAmount!=null){where.append(" AND s.total_amount<=?");args.add(maxAmount);}
        if(returnableOnly){where.append(" AND s.status<>'VOIDED' AND EXISTS(SELECT 1 FROM sales_order_item soi WHERE soi.sales_order_id=s.id AND soi.quantity>COALESCE((SELECT SUM(sri.quantity) FROM sales_return_item sri JOIN sales_return sr ON sr.id=sri.sales_return_id WHERE sri.source_sales_order_item_id=soi.id AND sr.status<>'VOIDED'),0))");}
        switch(workflowStatus){case "UNPRINTED"->where.append(" AND s.status<>'VOIDED' AND s.printed_at IS NULL");case "PRINTED"->where.append(" AND s.status<>'VOIDED' AND s.printed_at IS NOT NULL");case "UNDISPATCHED"->where.append(" AND s.status<>'VOIDED' AND NOT EXISTS(SELECT 1 FROM dispatch_sales_order x JOIN dispatch_sheet xd ON xd.id=x.dispatch_sheet_id WHERE x.sales_order_id=s.id AND x.is_active=1 AND xd.status<>'VOIDED')");case "DISPATCHED"->where.append(" AND EXISTS(SELECT 1 FROM dispatch_sales_order x JOIN dispatch_sheet xd ON xd.id=x.dispatch_sheet_id WHERE x.sales_order_id=s.id AND x.is_active=1 AND xd.status<>'VOIDED')");case "APPROVED"->where.append(" AND EXISTS(SELECT 1 FROM dispatch_sales_order x JOIN dispatch_sheet xd ON xd.id=x.dispatch_sheet_id WHERE x.sales_order_id=s.id AND x.is_active=1 AND xd.status IN ('APPROVED','COMPLETED'))");default->{} }
        Long total=jdbc.queryForObject("SELECT COUNT(*) FROM sales_order s WHERE "+where,Long.class,args.toArray());List<Object> params=new ArrayList<>(args);Collections.addAll(params,normalizedKeyword,normalizedKeyword,prefixLike,normalizedKeyword,prefixLike,size,(p-1)*size);
        String relevanceOrder=" CASE WHEN ?='' THEN 0 WHEN s.order_no=? THEN 0 WHEN s.order_no LIKE ? THEN 1 WHEN s.customer_code_snapshot=? THEN 2 WHEN s.customer_code_snapshot LIKE ? THEN 3 ELSE 4 END, "+DocumentSort.sql(sortBy,sortDirection,"s.order_date","s.order_no","s.id");
        var items=jdbc.query("SELECT s.id,s.order_no,s.order_date,s.customer_code_snapshot,s.customer_name_snapshot,s.settlement_method,s.total_amount,s.status,s.version,s.created_at,s.printed_at,s.print_count,EXISTS(SELECT 1 FROM dispatch_sales_order dso JOIN dispatch_sheet d ON d.id=dso.dispatch_sheet_id WHERE dso.sales_order_id=s.id AND dso.is_active=1 AND d.status IN ('APPROVED','COMPLETED')) approved_and_dispatched,EXISTS(SELECT 1 FROM dispatch_sales_order dso JOIN dispatch_sheet d ON d.id=dso.dispatch_sheet_id WHERE dso.sales_order_id=s.id AND dso.is_active=1 AND d.status<>'VOIDED') dispatched FROM sales_order s WHERE "+where+" ORDER BY"+relevanceOrder+" LIMIT ? OFFSET ?",(rs,n)->map("id",rs.getLong(1),"orderNo",rs.getString(2),"orderDate",rs.getDate(3).toLocalDate(),"customerCode",rs.getString(4),"customerName",rs.getString(5),"settlementMethod",rs.getString(6),"totalAmount",rs.getBigDecimal(7),"status",rs.getString(8),"version",rs.getInt(9),"createdAt",rs.getTimestamp(10).toLocalDateTime(),"printedAt",rs.getTimestamp(11)==null?null:rs.getTimestamp(11).toLocalDateTime(),"printCount",rs.getInt(12),"dispatchApproved",rs.getBoolean(13),"dispatched",rs.getBoolean(14)),params.toArray());
        return ApiResponse.success(new PageResult<>(items,total==null?0:total,p,size));
    }

    @GetMapping("/{id}")
    public ApiResponse<Map<String,Object>> detail(@PathVariable long id){
        var headers=jdbc.query("SELECT s.id,s.order_no,s.order_date,s.customer_id,s.customer_code_snapshot,s.customer_name_snapshot,COALESCE(s.customer_phone_snapshot,''),s.salesperson_id,COALESCE(s.salesperson_name_snapshot,''),s.settlement_method,s.immediate_amount,s.on_account_amount,s.total_amount,s.status,COALESCE(s.remark,''),s.version,s.created_at,s.updated_at,s.printed_at,s.print_count,cu.display_name,uu.display_name,pu.display_name,EXISTS(SELECT 1 FROM dispatch_sales_order dso JOIN dispatch_sheet d ON d.id=dso.dispatch_sheet_id WHERE dso.sales_order_id=s.id AND dso.is_active=1 AND d.status<>'VOIDED') dispatched,EXISTS(SELECT 1 FROM dispatch_sales_order dso JOIN dispatch_sheet d ON d.id=dso.dispatch_sheet_id WHERE dso.sales_order_id=s.id AND dso.is_active=1 AND d.status IN ('APPROVED','COMPLETED')) dispatch_approved,(SELECT du.display_name FROM dispatch_sales_order dso JOIN dispatch_sheet d ON d.id=dso.dispatch_sheet_id LEFT JOIN sys_user du ON du.id=d.approved_by WHERE dso.sales_order_id=s.id AND dso.is_active=1 AND d.status IN ('APPROVED','COMPLETED') LIMIT 1) dispatch_approved_by,(SELECT d.approved_at FROM dispatch_sales_order dso JOIN dispatch_sheet d ON d.id=dso.dispatch_sheet_id WHERE dso.sales_order_id=s.id AND dso.is_active=1 AND d.status IN ('APPROVED','COMPLETED') LIMIT 1) dispatch_approved_at FROM sales_order s JOIN sys_user cu ON cu.id=s.created_by JOIN sys_user uu ON uu.id=s.updated_by LEFT JOIN sys_user pu ON pu.id=s.printed_by WHERE s.id=?",
            (rs,n)->map("id",rs.getLong(1),"orderNo",rs.getString(2),"orderDate",rs.getDate(3).toLocalDate(),"customerId",rs.getLong(4),"customerCode",rs.getString(5),"customerName",rs.getString(6),"customerPhone",rs.getString(7),"salespersonId",rs.getObject(8),"salespersonName",rs.getString(9),"settlementMethod",rs.getString(10),"immediateAmount",rs.getBigDecimal(11),"onAccountAmount",rs.getBigDecimal(12),"totalAmount",rs.getBigDecimal(13),"status",rs.getString(14),"remark",rs.getString(15),"version",rs.getInt(16),"createdAt",rs.getTimestamp(17).toLocalDateTime(),"updatedAt",rs.getTimestamp(18).toLocalDateTime(),"printedAt",rs.getTimestamp(19)==null?null:rs.getTimestamp(19).toLocalDateTime(),"printCount",rs.getInt(20),"createdByName",rs.getString(21),"updatedByName",rs.getString(22),"printedByName",rs.getString(23),"dispatched",rs.getBoolean(24),"dispatchApproved",rs.getBoolean(25),"dispatchApprovedByName",rs.getString(26),"dispatchApprovedAt",rs.getTimestamp(27)==null?null:rs.getTimestamp(27).toLocalDateTime()),id);
        if(headers.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Sales order not found");
        var items=jdbc.query("SELECT i.id,i.line_no,i.line_type,i.sku_id,i.sku_code_snapshot,i.product_name_snapshot,COALESCE(i.specification_snapshot,''),COALESCE(i.color_snapshot,''),i.package_spec_snapshot,i.package_count,COALESCE(i.package_unit_snapshot,''),i.quantity,i.sales_unit_snapshot,i.unit_price,i.reference_price,i.line_amount,COALESCE(i.remark,''),p.total_stock,"+
                "COALESCE((SELECT SUM(ri.quantity) FROM sales_return_item ri JOIN sales_return r ON r.id=ri.sales_return_id WHERE ri.source_sales_order_item_id=i.id AND r.status<>'VOIDED'),0) returned_quantity " +
                "FROM sales_order_item i LEFT JOIN product_sku p ON p.id=i.sku_id WHERE i.sales_order_id=? ORDER BY i.line_no",
            (rs,n)->{var quantity=rs.getBigDecimal(12);var returned=rs.getBigDecimal(19);return map("id",rs.getLong(1),"lineNo",rs.getInt(2),"lineType",rs.getString(3),"skuId",rs.getLong(4),"skuCode",rs.getString(5),"productName",rs.getString(6),"specification",rs.getString(7),"color",rs.getString(8),"packageSpec",rs.getBigDecimal(9),"packageCount",rs.getBigDecimal(10),"packageUnit",rs.getString(11),"quantity",quantity,"salesUnit",rs.getString(13),"unitPrice",rs.getBigDecimal(14),"referencePrice",rs.getBigDecimal(15),"lineAmount",rs.getBigDecimal(16),"remark",rs.getString(17),"currentStock",rs.getBigDecimal(18),"returnedQuantity",returned,"remainingReturnQuantity",quantity.subtract(returned).max(java.math.BigDecimal.ZERO));},id);
        var printHistory=jdbc.query("SELECT l.print_no,l.print_kind,COALESCE(l.reason,''),u.display_name,l.printed_at FROM sales_order_print_log l JOIN sys_user u ON u.id=l.printed_by WHERE l.sales_order_id=? ORDER BY l.print_no",
            (rs,n)->map("printNo",rs.getInt(1),"printKind",rs.getString(2),"reason",rs.getString(3),"printedByName",rs.getString(4),"printedAt",rs.getTimestamp(5).toLocalDateTime()),id);
        Map<String,Object> result=new LinkedHashMap<>(headers.get(0));result.put("items",items);result.put("printHistory",printHistory);return ApiResponse.success(result);
    }

    @PostMapping
    @Transactional
    public ApiResponse<Map<String,Object>> create(@Valid @RequestBody CreateRequest r,Authentication auth){
        long uid=userId(auth);var customers=jdbc.query("SELECT customer_code,short_name,phone,settlement_method FROM customer WHERE id=? AND enabled=1",(rs,n)->new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)},r.customerId());if(customers.isEmpty())throw bad("The customer does not exist or is disabled");
        Object[] salesperson=null;if(r.salespersonId()!=null){var people=jdbc.query("SELECT id,employee_name FROM employee WHERE id=? AND enabled=1 AND is_salesperson=1",(rs,n)->new Object[]{rs.getLong(1),rs.getString(2)},r.salespersonId());if(people.isEmpty())throw bad("The salesperson does not exist, is disabled, or is not marked as a salesperson");salesperson=people.get(0);}
        LocalDate date=r.orderDate()==null?LocalDate.now():r.orderDate();String orderNo=nextNo(date);BigDecimal total=BigDecimal.ZERO;List<ItemSnapshot> snapshots=new ArrayList<>();int line=1;
        for(ItemRequest item:r.items()){
            validateSaleQuantity(item.quantity());
            Integer saleable=jdbc.queryForObject("SELECT COUNT(*) FROM product_sku WHERE id=? AND enabled=1 AND saleable=1",Integer.class,item.skuId());
            if(saleable==null||saleable==0)throw bad("Internal supplies cannot be added to a sales order");
        }
        for(ItemRequest item:r.items()){var products=jdbc.query("SELECT sku_code,product_name,specification,color,package_spec,package_unit,sales_unit,wholesale_price FROM product_sku WHERE id=? AND enabled=1",(rs,n)->{BigDecimal reference=normalizedReferencePrice(rs.getBigDecimal(8));return new ItemSnapshot(item.skuId(),rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),item.packageSpec()==null?rs.getBigDecimal(5):item.packageSpec(),item.packageCount(),item.packageUnit()==null?rs.getString(6):item.packageUnit().trim(),rs.getString(7),item.quantity(),item.unitPrice()==null?reference:item.unitPrice(),reference,BigDecimal.ZERO,item.remark());},item.skuId());if(products.isEmpty())throw bad("The product does not exist or is disabled");ItemSnapshot s=products.get(0);validateSalePrice(s.productName(),s.unitPrice(),s.referencePrice());BigDecimal amount=s.quantity().multiply(s.unitPrice()).setScale(2,RoundingMode.HALF_UP);snapshots.add(new ItemSnapshot(s.skuId(),s.skuCode(),s.productName(),s.specification(),s.color(),s.packageSpec(),s.packageCount(),s.packageUnit(),s.salesUnit(),s.quantity(),s.unitPrice(),s.referencePrice(),amount,s.remark()));total=total.add(amount);line++;}
        String settlement=r.settlementMethod()==null||r.settlementMethod().isBlank()?Objects.toString(customers.get(0)[3],"Cash"):r.settlementMethod();BigDecimal immediate="Credit".equals(settlement)?BigDecimal.ZERO:total;BigDecimal account="Credit".equals(settlement)?total:BigDecimal.ZERO;LocalDateTime now=LocalDateTime.now();
        jdbc.update("INSERT INTO sales_order(order_no,order_date,customer_id,customer_code_snapshot,customer_name_snapshot,customer_phone_snapshot,salesperson_id,salesperson_name_snapshot,settlement_method,immediate_amount,on_account_amount,total_amount,status,remark,version,created_by,created_at,updated_by,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'DRAFT',?,0,?,?,?,?)",orderNo,date,r.customerId(),customers.get(0)[0],customers.get(0)[1],customers.get(0)[2],salesperson==null?null:salesperson[0],salesperson==null?null:salesperson[1],settlement,immediate,account,total,r.remark(),uid,now,uid,now);
        Long orderId=jdbc.queryForObject("SELECT id FROM sales_order WHERE order_no=?",Long.class,orderNo);line=1;for(ItemSnapshot s:snapshots){jdbc.update("INSERT INTO sales_order_item(sales_order_id,line_no,line_type,sku_id,sku_code_snapshot,product_name_snapshot,specification_snapshot,color_snapshot,package_spec_snapshot,package_count,package_unit_snapshot,quantity,sales_unit_snapshot,unit_price,reference_price,line_amount,remark) VALUES(?,?,'PRODUCT',?,?,?,?,?,?,?,?,?,?,?,?,?,?)",orderId,line++,s.skuId(),s.skuCode(),s.productName(),s.specification(),s.color(),s.packageSpec(),s.packageCount(),s.packageUnit(),s.quantity(),s.salesUnit(),s.unitPrice(),s.referencePrice(),s.amount(),s.remark());}
        return ApiResponse.success(Map.of("id",orderId,"orderNo",orderNo,"totalAmount",total));
    }

    @PutMapping("/{id}")
    @Transactional
    public ApiResponse<Map<String,Object>> update(@PathVariable long id,@Valid @RequestBody UpdateRequest r,Authentication auth){
        var current=jdbc.query("SELECT status,version,printed_at FROM sales_order WHERE id=? FOR UPDATE",(rs,n)->new Object[]{rs.getString(1),rs.getInt(2),rs.getTimestamp(3)},id);if(current.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Sales order not found");if(!"DRAFT".equals(current.get(0)[0]))throw conflict("This sales order cannot be edited");if(current.get(0)[2]!=null)throw conflict("This sales order has been printed and inventory has been deducted, so it cannot be edited");if(!Objects.equals(current.get(0)[1],r.version()))throw conflict("The sales order was changed by another user. Refresh and try again");
        var customers=jdbc.query("SELECT customer_code,short_name,phone,settlement_method FROM customer WHERE id=? AND enabled=1",(rs,n)->new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)},r.customerId());if(customers.isEmpty())throw bad("The customer does not exist or is disabled");
        Object[] salesperson=null;if(r.salespersonId()!=null){var people=jdbc.query("SELECT id,employee_name FROM employee WHERE id=? AND enabled=1 AND is_salesperson=1",(rs,n)->new Object[]{rs.getLong(1),rs.getString(2)},r.salespersonId());if(people.isEmpty())throw bad("The salesperson does not exist, is disabled, or is not marked as a salesperson");salesperson=people.get(0);}
        BigDecimal total=BigDecimal.ZERO;List<ItemSnapshot> snapshots=new ArrayList<>();for(ItemRequest item:r.items()){validateSaleQuantity(item.quantity());Integer saleable=jdbc.queryForObject("SELECT COUNT(*) FROM product_sku WHERE id=? AND enabled=1 AND saleable=1",Integer.class,item.skuId());if(saleable==null||saleable==0)throw bad("The product does not exist, is disabled, or is an internal supply");var products=jdbc.query("SELECT sku_code,product_name,specification,color,package_spec,package_unit,sales_unit,wholesale_price FROM product_sku WHERE id=?",(rs,n)->{BigDecimal reference=normalizedReferencePrice(rs.getBigDecimal(8));return new ItemSnapshot(item.skuId(),rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),item.packageSpec()==null?rs.getBigDecimal(5):item.packageSpec(),item.packageCount(),item.packageUnit()==null?rs.getString(6):item.packageUnit().trim(),rs.getString(7),item.quantity(),item.unitPrice()==null?reference:item.unitPrice(),reference,BigDecimal.ZERO,item.remark());},item.skuId());ItemSnapshot s=products.get(0);validateSalePrice(s.productName(),s.unitPrice(),s.referencePrice());BigDecimal amount=s.quantity().multiply(s.unitPrice()).setScale(2,RoundingMode.HALF_UP);snapshots.add(new ItemSnapshot(s.skuId(),s.skuCode(),s.productName(),s.specification(),s.color(),s.packageSpec(),s.packageCount(),s.packageUnit(),s.salesUnit(),s.quantity(),s.unitPrice(),s.referencePrice(),amount,s.remark()));total=total.add(amount);}
        String settlement=r.settlementMethod()==null||r.settlementMethod().isBlank()?Objects.toString(customers.get(0)[3],"Cash"):r.settlementMethod();BigDecimal immediate="Credit".equals(settlement)?BigDecimal.ZERO:total;BigDecimal account="Credit".equals(settlement)?total:BigDecimal.ZERO;long uid=userId(auth);int changed=jdbc.update("UPDATE sales_order SET customer_id=?,customer_code_snapshot=?,customer_name_snapshot=?,customer_phone_snapshot=?,salesperson_id=?,salesperson_name_snapshot=?,settlement_method=?,immediate_amount=?,on_account_amount=?,total_amount=?,remark=?,version=version+1,updated_by=?,updated_at=? WHERE id=? AND status='DRAFT' AND version=?",r.customerId(),customers.get(0)[0],customers.get(0)[1],customers.get(0)[2],salesperson==null?null:salesperson[0],salesperson==null?null:salesperson[1],settlement,immediate,account,total,r.remark(),uid,LocalDateTime.now(),id,r.version());requireChanged(changed,"Sales order status has changed. Refresh and try again.");
        jdbc.update("DELETE FROM sales_order_item WHERE sales_order_id=?",id);int line=1;for(ItemSnapshot s:snapshots){jdbc.update("INSERT INTO sales_order_item(sales_order_id,line_no,line_type,sku_id,sku_code_snapshot,product_name_snapshot,specification_snapshot,color_snapshot,package_spec_snapshot,package_count,package_unit_snapshot,quantity,sales_unit_snapshot,unit_price,reference_price,line_amount,remark) VALUES(?,?,'PRODUCT',?,?,?,?,?,?,?,?,?,?,?,?,?,?)",id,line++,s.skuId(),s.skuCode(),s.productName(),s.specification(),s.color(),s.packageSpec(),s.packageCount(),s.packageUnit(),s.quantity(),s.salesUnit(),s.unitPrice(),s.referencePrice(),s.amount(),s.remark());}
        return ApiResponse.success(Map.of("id",id,"totalAmount",total,"version",r.version()+1));
    }

    @PostMapping("/{id}/approve")
    @Transactional
    public ApiResponse<Void> approve(@PathVariable long id,@RequestBody VersionRequest r,Authentication auth){throw bad("Sales orders do not require approval. Print the delivery note, add the order to a dispatch sheet, and have a supervisor approve the dispatch sheet");}

    @PostMapping("/{id}/confirm-print")
    @Transactional
    public ApiResponse<Map<String,Object>> confirmPrint(@PathVariable long id,@RequestBody PrintRequest request,Authentication auth){
        var rows=jdbc.query("SELECT order_no,status,printed_at,print_count,version FROM sales_order WHERE id=? FOR UPDATE",(rs,n)->map("orderNo",rs.getString(1),"status",rs.getString(2),"printedAt",rs.getTimestamp(3),"printCount",rs.getInt(4),"version",rs.getInt(5)),id);
        if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Sales order not found");
        Map<String,Object> order=rows.get(0);if("VOIDED".equals(order.get("status")))throw conflict("A voided sales order cannot be printed");
        int currentVersion=((Number)order.get("version")).intValue();if(request.version()!=null&&request.version()!=currentVersion)throw conflict("The sales order has changed. Refresh and try again");
        long uid=userId(auth);LocalDateTime now=LocalDateTime.now();int previous=((Number)order.get("printCount")).intValue();PrintDecision decision=decidePrint((java.sql.Timestamp)order.get("printedAt"),previous,request.reason());boolean first=decision.firstPrint();
        if(first){
            var demands=jdbc.query("SELECT i.sku_id,i.sku_code_snapshot,i.product_name_snapshot,SUM(i.quantity) FROM sales_order_item i WHERE i.sales_order_id=? AND i.sku_id IS NOT NULL AND i.quantity>0 GROUP BY i.sku_id,i.sku_code_snapshot,i.product_name_snapshot ORDER BY i.sku_id FOR UPDATE",(rs,n)->new PrintDemand(rs.getLong(1),rs.getString(2),rs.getString(3),rs.getBigDecimal(4)),id);
            for(PrintDemand demand:demands){BigDecimal before=jdbc.queryForObject("SELECT total_stock FROM product_sku WHERE id=? FOR UPDATE",BigDecimal.class,demand.skuId());if(before==null)throw conflict("Product “"+demand.skuCode()+" "+demand.productName()+"” does not exist");BigDecimal after=before.subtract(demand.quantity());jdbc.update("UPDATE product_sku SET total_stock=?,version=version+1,updated_by=?,updated_at=? WHERE id=?",after,uid,now,demand.skuId());jdbc.update("INSERT INTO inventory_movement(product_sku_id,movement_type,quantity_change,before_quantity,after_quantity,reason,reference_type,reference_id,reference_no,created_by,created_at) VALUES(?,'SALE_PRINT',?,?,?,?, 'SALES_ORDER_PRINT',?,?,?,?)",demand.skuId(),demand.quantity().negate(),before,after,"Inventory deducted when delivery note for sales order "+order.get("orderNo")+" was printed for the first time",id,order.get("orderNo"),uid,now);}
            jdbc.update("UPDATE sales_order SET printed_by=?,printed_at=?,print_count=1,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND printed_at IS NULL",uid,now,uid,now,id);
        }else{
            jdbc.update("UPDATE sales_order SET print_count=print_count+1,updated_by=?,updated_at=?,version=version+1 WHERE id=?",uid,now,id);
        }
        int printNo=decision.printNo();jdbc.update("INSERT INTO sales_order_print_log(sales_order_id,print_no,print_kind,reason,printed_by,printed_at) VALUES(?,?,?,?,?,?)",id,printNo,decision.printKind(),request.reason(),uid,now);
        return ApiResponse.success(map("firstPrint",first,"printCount",printNo,"printedAt",now));
    }

    @PostMapping("/{id}/void")
    @Transactional
    public ApiResponse<Void> voidOrder(@PathVariable long id,@Valid @RequestBody VoidRequest r,Authentication auth){var rows=jdbc.query("SELECT status,printed_at,version FROM sales_order WHERE id=? FOR UPDATE",(rs,n)->new Object[]{rs.getString(1),rs.getTimestamp(2),rs.getInt(3)},id);if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Sales order not found");Object[] current=rows.get(0);if(!"DRAFT".equals(current[0]))throw conflict("An approved or voided sales order cannot be changed");if(current[1]!=null)throw conflict("A printed sales order cannot be changed");if(!Objects.equals(current[2],r.version()))throw conflict("The sales order status has changed. Refresh and try again");Integer occupied=jdbc.queryForObject("SELECT COUNT(*) FROM dispatch_sales_order dso JOIN dispatch_sheet d ON d.id=dso.dispatch_sheet_id WHERE dso.sales_order_id=? AND dso.is_active=1 AND d.status<>'VOIDED'",Integer.class,id);if(occupied!=null&&occupied>0)throw conflict("A sales order assigned to an active dispatch sheet cannot be voided");long uid=userId(auth);LocalDateTime now=LocalDateTime.now();String reason=r.reason()==null||r.reason().isBlank()?"Voided after user confirmation":r.reason().trim();int changed=jdbc.update("UPDATE sales_order SET status='VOIDED',voided_by=?,voided_at=?,void_reason=?,updated_by=?,updated_at=?,version=version+1 WHERE id=? AND status='DRAFT' AND printed_at IS NULL AND version=?",uid,now,reason,uid,now,id,r.version());requireChanged(changed,"The sales order status has changed. Refresh and try again");return ApiResponse.success(null);}

    private String nextNo(LocalDate date){List<Integer> values=jdbc.query("SELECT current_value FROM number_sequence WHERE biz_type='SALES_ORDER' AND biz_date=? FOR UPDATE",(rs,n)->rs.getInt(1),date);int next;if(values.isEmpty()){next=1;jdbc.update("INSERT INTO number_sequence(biz_type,biz_date,current_value,version) VALUES('SALES_ORDER',?,1,0)",date);}else{next=values.get(0)+1;jdbc.update("UPDATE number_sequence SET current_value=?,version=version+1 WHERE biz_type='SALES_ORDER' AND biz_date=?",next,date);}return "XS"+date.format(DateTimeFormatter.ofPattern("yyMMdd"))+"-"+String.format("%03d",next);}
    static boolean isFirstPrint(java.sql.Timestamp printedAt){return printedAt==null;}
    static PrintDecision decidePrint(java.sql.Timestamp printedAt,int previousPrintCount,String reason){
        boolean first=isFirstPrint(printedAt);
        if(!first&&(reason==null||reason.isBlank()))throw bad("A reason is required when reprinting a delivery note");
        return new PrintDecision(first,first,first?"FIRST_PRINT":"REPRINT",previousPrintCount+1);
    }
    static void validateSalePrice(String productName,BigDecimal unitPrice,BigDecimal referencePrice){if(unitPrice==null||referencePrice==null)throw bad("No valid price is available for product “"+productName+"”");if(unitPrice.signum()<0)throw bad("The unit price for product “"+productName+"” cannot be negative");if(unitPrice.signum()>0&&unitPrice.compareTo(referencePrice)<0)throw bad("Price too low: the unit price for product “"+productName+"” cannot be below the reference price "+referencePrice.stripTrailingZeros().toPlainString());}
    static void validateSaleQuantity(BigDecimal quantity){if(quantity==null||quantity.compareTo(new BigDecimal("0.01"))<0)throw bad("The sales quantity cannot be less than 0.01");if(quantity.stripTrailingZeros().scale()>2)throw bad("The sales quantity can have at most two decimal places");}
    static BigDecimal normalizedReferencePrice(BigDecimal referencePrice){return referencePrice==null?BigDecimal.ZERO:referencePrice;}
    private long userId(Authentication a){Long id=jdbc.queryForObject("SELECT id FROM sys_user WHERE username=?",Long.class,a.getName());if(id==null)throw new ResponseStatusException(HttpStatus.UNAUTHORIZED);return id;}
    private static Map<String,Object> map(Object... values){Map<String,Object> result=new LinkedHashMap<>();for(int i=0;i<values.length;i+=2)result.put((String)values[i],values[i+1]);return result;}
    private static void requireChanged(int n,String m){if(n!=1)throw conflict(m);}private static ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private static ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}
    public record CreateRequest(LocalDate orderDate,@NotNull Long customerId,Long salespersonId,String settlementMethod,String remark,@NotEmpty List<@Valid ItemRequest> items){}
    public record UpdateRequest(@NotNull Long customerId,Long salespersonId,String settlementMethod,String remark,@NotEmpty List<@Valid ItemRequest> items,@NotNull Integer version){}
    public record ItemRequest(@NotNull Long skuId,@DecimalMin("0") BigDecimal packageSpec,@DecimalMin("0") BigDecimal packageCount,String packageUnit,@NotNull @DecimalMin(value="0.01") BigDecimal quantity,BigDecimal unitPrice,String remark){}
    public record VersionRequest(@NotNull Integer version){}
    public record PrintRequest(Integer version,String reason){}
    public record VoidRequest(@NotNull Integer version,String reason){}
    private record ItemSnapshot(Long skuId,String skuCode,String productName,String specification,String color,BigDecimal packageSpec,BigDecimal packageCount,String packageUnit,String salesUnit,BigDecimal quantity,BigDecimal unitPrice,BigDecimal referencePrice,BigDecimal amount,String remark){}
    private record PrintDemand(Long skuId,String skuCode,String productName,BigDecimal quantity){}
    record PrintDecision(boolean firstPrint,boolean deductInventory,String printKind,int printNo){}
}
