<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api'
const query=reactive({keyword:'',regionLarge:'',regionSmall:'',enabled:true as boolean|'',page:1,pageSize:20}),rows=ref<any[]>([]),regions=ref<any[]>([]),total=ref(0),loading=ref(false),dialog=ref(false),editing=ref(false)
const regionLargeOptions=computed(()=>[...new Set(regions.value.map(x=>x.regionLarge).filter(Boolean))])
const regionSmallOptions=computed(()=>[...new Set(regions.value.filter(x=>!query.regionLarge||x.regionLarge===query.regionLarge).map(x=>x.regionSmall).filter(Boolean))])
const empty=()=>({id:0,customerCode:'',shortName:'',contactName:'',mobile:'',phone:'',route:'',settlementMethod:'Cash',version:0})
const form=reactive(empty())
async function load(){loading.value=true;try{const{data}=await api.get('/customers',{params:{...query,enabled:query.enabled===''?true:query.enabled,includeDisabled:query.enabled==='' }});rows.value=data.data.items;total.value=data.data.total}finally{loading.value=false}}
async function loadRegions(){const{data}=await api.get('/customer-regions');regions.value=data.data}
function changeRegionLarge(){query.regionSmall='';search()}
function search(){query.page=1;load()} function add(){Object.assign(form,empty());editing.value=false;dialog.value=true} function edit(row:any){Object.assign(form,row);editing.value=true;dialog.value=true}
async function save(){if(!form.customerCode.trim()||!form.shortName.trim())return ElMessage.warning('Customer Code and name are required');try{editing.value?await api.put(`/customers/${form.id}`,form):await api.post('/customers',form);ElMessage.success('Saved Successfully');dialog.value=false;load()}catch(e:any){ElMessage.error(e.response?.data?.message||'SaveFailed, Check whether the code is duplicated')}}
async function toggle(row:any){const action=row.enabled?'Disable':'Enable';await ElMessageBox.confirm(`Confirm${action}Customer“${row.shortName}”?`,`${action}Confirm`,{type:row.enabled?'warning':'info'});await api.patch(`/customers/${row.id}/enabled`,{enabled:!row.enabled,version:row.version});ElMessage.success(`${action}Successful`);load()}
onMounted(()=>{loadRegions();load()})
</script>
<template><section><div class="page-heading"><div><h1>Customers</h1><p>Search by code, name, mnemonic, or phone</p></div><el-button type="primary" @click="add">Add Customer</el-button></div>
<el-card><div class="toolbar customer-toolbar"><el-input v-model="query.keyword" clearable placeholder="Customer Code / Name / Phone" @keyup.enter="search"/><el-select v-model="query.regionLarge" clearable filterable placeholder="All Regions" @change="changeRegionLarge"><el-option v-for="item in regionLargeOptions" :key="item" :label="item" :value="item"/></el-select><el-select v-model="query.regionSmall" clearable filterable placeholder="All Subregions" @change="search"><el-option v-for="item in regionSmallOptions" :key="item" :label="item" :value="item"/></el-select><el-select v-model="query.enabled" @change="search"><el-option label="All Statuses" value=""/><el-option label="Active" :value="true"/><el-option label="Disabled" :value="false"/></el-select><el-button type="primary" @click="search">Search</el-button></div>
<el-table :data="rows" v-loading="loading" stripe><el-table-column prop="customerCode" label="Customer Code" width="130"/><el-table-column prop="shortName" label="Customer Name" min-width="200"/><el-table-column prop="regionLarge" label="Region" width="85"/><el-table-column prop="regionSmall" label="Subregion" width="90"/><el-table-column prop="contactName" label="Contact" width="110"/><el-table-column prop="mobile" label="Mobile" width="140"/><el-table-column prop="phone" label="Phone" min-width="160"/><el-table-column prop="route" label="Route" width="110"/><el-table-column prop="settlementMethod" label="Payment Method" width="100"/><el-table-column label="Status" width="90"><template #default="s"><el-tag :type="s.row.enabled?'success':'info'">{{s.row.enabled?'Active':'Disabled'}}</el-tag></template></el-table-column><el-table-column label="Actions" width="170" fixed="right"><template #default="s"><el-button link type="primary" @click="edit(s.row)">Edit</el-button><el-button link :type="s.row.enabled?'danger':'success'" @click="toggle(s.row)">{{s.row.enabled?'Disable':'Restore'}}</el-button></template></el-table-column></el-table>
<el-pagination v-model:current-page="query.page" v-model:page-size="query.pageSize" :page-sizes="[20,50,100]" :total="total" layout="total, sizes, prev, pager, next" @current-change="load" @size-change="search"/></el-card>
<el-dialog v-model="dialog" :title="editing?'EditCustomer':'Add Customer'" width="620px"><el-form label-width="90px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="Customer Code" required><el-input v-model="form.customerCode"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Customer Name" required><el-input v-model="form.shortName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Contact"><el-input v-model="form.contactName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Mobile"><el-input v-model="form.mobile"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Phone"><el-input v-model="form.phone"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Route"><el-input v-model="form.route"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Payment Method"><el-select v-model="form.settlementMethod"><el-option label="Cash" value="Cash"/><el-option label="Credit" value="Credit"/></el-select></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">Cancel</el-button><el-button type="primary" @click="save">Save</el-button></template></el-dialog></section></template>
<style scoped>.customer-toolbar{display:grid;grid-template-columns:minmax(240px,1fr) 140px 140px 130px 80px;gap:10px}@media(max-width:900px){.customer-toolbar{grid-template-columns:1fr}}</style>


