<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api} from '../api'
import BusinessDocumentDialog from '../components/BusinessDocumentDialog.vue'
import {localToday} from '../utils/date'
const today=localToday
const rows=ref<any[]>([]),selected=ref<any>(),loading=ref(false)
const documentDialog=ref(false),documentType=ref(''),documentId=ref<number|null>(null)
const summary=reactive<any>({rowCount:0,documentCount:0,inboundQuantity:0,outboundQuantity:0,inboundAmount:0,outboundAmount:0})
const query=reactive({dateFrom:today(),dateTo:today(),types:['PURCHASE_RECEIPT','SALES_OUTBOUND','SALES_RETURN','STOCK_ADJUSTMENT'],keyword:'',referenceNo:'',sortBy:'date',sortDirection:'asc'})
const money=(v:any)=>v===null||v===undefined?'—':`¥${Number(v).toFixed(2)}`
const qty=(v:any)=>v===null||v===undefined?'':Number(v).toLocaleString('zh-CN',{maximumFractionDigits:4})
function handleSortChange({prop,order}:{prop:string,order:string}){query.sortBy=prop==='referenceNo'?'documentNo':'date';query.sortDirection=order==='descending'?'desc':'asc';load()}
async function load(){if(!query.types.length){rows.value=[];selected.value=undefined;Object.assign(summary,{rowCount:0,documentCount:0,inboundQuantity:0,outboundQuantity:0,inboundAmount:0,outboundAmount:0});return}loading.value=true;try{const {types,...rest}=query;const {data}=await api.get('/ledgers/inventory',{params:{...rest,type:types.join(',')}});rows.value=data.data.items;Object.assign(summary,data.data.summary);selected.value=rows.value[0]}catch(e:any){ElMessage.error(e?.response?.data?.message||e?.message||'Search failed')}finally{loading.value=false}}
function clear(){Object.assign(query,{dateFrom:today(),dateTo:today(),types:['PURCHASE_RECEIPT','SALES_OUTBOUND','SALES_RETURN','STOCK_ADJUSTMENT'],keyword:'',referenceNo:'',sortBy:'date',sortDirection:'asc'});load()}
function openDocument(row:any){const type=({PURCHASE_RECEIPT:'purchase-receipt',SALES_ORDER_PRINT:'sales-order',RETURN_WAREHOUSE:'return-warehouse'} as any)[row.referenceType];if(!type||!row.documentId)return ElMessageBox.alert(`Product: ${row.skuCode} ${row.productName}<br>Before: ${qty(row.beforeQuantity)} After: ${qty(row.afterQuantity)}<br>Reason: ${row.reason||'—'}<br>Handler: ${row.operatorName||'—'} Time: ${row.occurredAt}`,row.referenceNo?`Inventory Adjustment ${row.referenceNo}`:'Inventory Adjustment Data',{dangerouslyUseHTMLString:true,confirmButtonText:'Close'});documentType.value=type;documentId.value=row.documentId;documentDialog.value=true}
onMounted(load)
</script>
<template><div class="ledger-page"><div class="page-heading"><div><h1>Inventory Movement Ledger</h1><p>Read-only inventory movements: sales printing deducts stock, approved purchase receipts add stock, and approved return warehousing adds stock.</p></div></div><el-card>
  <div class="filters"><el-date-picker v-model="query.dateFrom" type="date" value-format="YYYY-MM-DD"/><span>to</span><el-date-picker v-model="query.dateTo" type="date" value-format="YYYY-MM-DD"/>
    <el-checkbox-group v-model="query.types"><el-checkbox value="PURCHASE_RECEIPT">Purchase Receipt</el-checkbox><el-checkbox value="SALES_OUTBOUND">Sales Order</el-checkbox><el-checkbox value="SALES_RETURN">Sales Returns</el-checkbox><el-checkbox value="STOCK_ADJUSTMENT">Stock Count / Adjustment</el-checkbox></el-checkbox-group>
    <el-input v-model="query.keyword" clearable placeholder="Product Code / Product / Specification" @keyup.enter="load"/><el-input v-model="query.referenceNo" clearable placeholder="Source Document No." @keyup.enter="load"/><el-button type="primary" @click="load">Search</el-button><el-button @click="clear">Clear Filters</el-button>
  </div>
  <el-table :data="rows" v-loading="loading" height="46vh" highlight-current-row stripe class="document-ledger" :default-sort="{prop:'occurredAt',order:'ascending'}" @sort-change="handleSortChange" @row-click="selected=$event" @row-dblclick="openDocument"><el-table-column prop="occurredAt" label="Occurred At" width="170" sortable="custom" :sort-orders="['ascending','descending']"/><el-table-column prop="documentType" label="Document Type" width="130"/><el-table-column prop="warehouseName" label="Warehouse" width="90"/><el-table-column prop="skuCode" label="Code" width="120"/><el-table-column label="Product / Specification" min-width="240"><template #default="s">{{s.row.productName}} {{s.row.specification}}</template></el-table-column><el-table-column prop="unit" label="Unit" width="70"/><el-table-column label="Unit Price" width="105" align="right"><template #default="s">{{money(s.row.unitPrice)}}</template></el-table-column><el-table-column label="Inbound Quantity" width="105" align="right"><template #default="s">{{qty(s.row.inboundQuantity)}}</template></el-table-column><el-table-column label="Inbound Amount" width="115" align="right"><template #default="s">{{money(s.row.inboundAmount)}}</template></el-table-column><el-table-column label="Outbound Quantity" width="105" align="right"><template #default="s">{{qty(s.row.outboundQuantity)}}</template></el-table-column><el-table-column label="Outbound Amount" width="115" align="right"><template #default="s">{{money(s.row.outboundAmount)}}</template></el-table-column><el-table-column label="Supplier / Customer" min-width="190"><template #default="s">{{s.row.supplierName||s.row.customerName||'—'}}</template></el-table-column><el-table-column prop="referenceNo" label="Source Document No." width="155" sortable="custom" :sort-orders="['ascending','descending']"/></el-table>
  <div class="summary"><span>Movement {{summary.rowCount}}  rows</span><span>Document {{summary.documentCount}}  documents</span><span>Inbound Quantity {{qty(summary.inboundQuantity)}}</span><span>Inbound Amount {{money(summary.inboundAmount)}}</span><span>Outbound Quantity {{qty(summary.outboundQuantity)}}</span><span>Outbound Amount {{money(summary.outboundAmount)}}</span></div>
  <section class="inline-detail"><div class="detail-title"><strong>{{selected?`${selected.referenceNo||'No source document number'} · ${selected.skuCode} Movement Details`:'Click a movement above to view details'}}</strong></div><div v-if="selected" class="detail-grid"><span>Product: {{selected.productName}} {{selected.specification}}</span><span>Before: {{qty(selected.beforeQuantity)}}</span><span>After: {{qty(selected.afterQuantity)}}</span><span>Supplier: {{selected.supplierCode}} {{selected.supplierName||'—'}}</span><span>Customer: {{selected.customerCode}} {{selected.customerName||'—'}}</span><span>Handler: {{selected.operatorName}}</span><span class="wide">Change Reason: {{selected.reason}}</span><span>Occurred At: {{selected.occurredAt}}</span></div><el-empty v-else :image-size="48" description="No movement selected"/></section>
</el-card><BusinessDocumentDialog v-model="documentDialog" :type="documentType" :id="documentId"/></div></template>
<style scoped>
.page-heading{margin-bottom:14px}.page-heading h1{margin:0}.page-heading p{margin:6px 0 0;color:#6b7280}.filters{display:flex;gap:9px;align-items:center;margin-bottom:12px;flex-wrap:wrap}.filters .el-input{width:220px}.summary{display:flex;justify-content:flex-end;gap:22px;padding:10px 4px;color:#0f766e;font-weight:600;border-bottom:1px solid #dcdfe6}.inline-detail{padding-top:10px;min-height:138px}.detail-title{margin-bottom:10px}.detail-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:10px 20px;color:#606266;max-height:118px;overflow:auto}.detail-grid .wide{grid-column:span 2}.ledger-page :deep(.el-card__body){padding-bottom:10px}
.document-ledger :deep(.el-table__row){cursor:pointer}
</style>


