<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api} from '../api'
import {localToday} from '../utils/date'
const rows=ref<any[]>([]),detail=ref<any>(),categories=ref<any[]>([]),employees=ref<any[]>([]),loading=ref(false),dialog=ref(false),printPreview=ref(false),saving=ref(false)
const query=reactive({dateFrom:localToday(),dateTo:localToday(),keyword:'',status:'',printStatus:'',sortBy:'date',sortDirection:'asc',page:1,pageSize:100})
const form=reactive<any>({id:null,expenseDate:localToday(),handlerEmployeeId:null,remark:'',version:null,items:[]})
const errorMessage=(e:any)=>e?.response?.data?.message||e?.response?.data?.error||e?.message||'Action failed'
async function load(){loading.value=true;try{const{data}=await api.get('/other-expenses',{params:query});rows.value=data.data.items;if(detail.value){const same=rows.value.find(x=>x.id===detail.value.id);if(!same)detail.value=undefined}}finally{loading.value=false}}
function handleSortChange({prop,order}:{prop:string,order:string}){query.sortBy=prop==='expenseNo'?'documentNo':'date';query.sortDirection=order==='descending'?'desc':'asc';query.page=1;load()}
async function select(row:any){const{data}=await api.get(`/other-expenses/${row.id}`);detail.value=data.data}
function rowClassName({row}:any){return row.status==='VOIDED'?'void-row':''}
function addLine(){form.items.push({categoryCode:'',summary:'',amount:0})}
function openNew(){Object.assign(form,{id:null,expenseDate:localToday(),handlerEmployeeId:null,remark:'',version:null,items:[]});addLine();dialog.value=true}
async function edit(row:any){await select(row);Object.assign(form,{id:detail.value.id,expenseDate:detail.value.expenseDate,handlerEmployeeId:detail.value.handlerEmployeeId,remark:detail.value.remark,version:detail.value.version,items:detail.value.items.map((x:any)=>({categoryCode:x.categoryCode,summary:x.summary,amount:Number(x.amount)}))});dialog.value=true}
async function save(){saving.value=true;try{const editingId=form.id;const payload={expenseDate:form.expenseDate,handlerEmployeeId:form.handlerEmployeeId,remark:form.remark,version:form.version,items:form.items};if(editingId)await api.put(`/other-expenses/${editingId}`,payload);else await api.post('/other-expenses',payload);dialog.value=false;await load();if(editingId){const same=rows.value.find(x=>x.id===editingId);if(same)await select(same)}ElMessage.success('Other expense document saved')}catch(e){ElMessage.error(errorMessage(e))}finally{saving.value=false}}
async function approve(row:any){await ElMessageBox.confirm(`Approve ${row.expenseNo}? It cannot be edited after approval.`,'Approval Confirmation',{type:'warning'});try{await api.post(`/other-expenses/${row.id}/approve`,{version:row.version});await load();if(detail.value?.id===row.id)await select(row);ElMessage.success('Approved successfully')}catch(e){ElMessage.error(errorMessage(e))}}
async function voidExpense(row:any){try{const{value}=await ElMessageBox.prompt('Enter a void reason','Void Other Expense Document',{inputValidator:v=>!!v||'Reason is required',type:'warning'});await api.post(`/other-expenses/${row.id}/void`,{version:row.version,reason:value});await load();if(detail.value?.id===row.id)await select(row);ElMessage.success('Voided')}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(errorMessage(e))}}
async function openPrintPreview(row:any){await select(row);printPreview.value=true}
async function printExpense(){if(!detail.value)return;const row={id:detail.value.id};window.print();try{await ElMessageBox.confirm('Was the document printed successfully or saved as a PDF?','Confirm Print Result',{confirmButtonText:'Print Successful',cancelButtonText:'Print Failed or Cancelled',type:'warning'});await api.post(`/other-expenses/${row.id}/confirm-print`,{version:detail.value.version});await load();await select(row);printPreview.value=true;ElMessage.success('Print Status Recorded')}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(errorMessage(e))}}
async function init(){const [c,e]=await Promise.all([api.get('/other-expenses/categories'),api.get('/reference-data/employees',{params:{enabled:true,page:1,pageSize:500}})]);categories.value=c.data.data;employees.value=e.data.data.items||e.data.data;await load()}
onMounted(init)
</script>
<template><div class="expense-page"><div class="page-heading"><div><h1>Other Expenses</h1><p>Record cash expenses. Printing and approval are independent.</p></div><el-button type="primary" @click="openNew">Add Other Expense</el-button></div>
<el-card><div class="filters"><el-date-picker v-model="query.dateFrom" type="date" value-format="YYYY-MM-DD"/><span>to</span><el-date-picker v-model="query.dateTo" type="date" value-format="YYYY-MM-DD"/><el-input v-model="query.keyword" clearable placeholder="Document No. / Handler / Notes" @keyup.enter="load"/><el-select v-model="query.status" clearable placeholder="All Statuses"><el-option label="Draft" value="DRAFT"/><el-option label="Approved" value="APPROVED"/><el-option label="Voided" value="VOIDED"/></el-select><el-select v-model="query.printStatus" clearable placeholder="All Print Statuses"><el-option label="Not Printed" value="UNPRINTED"/><el-option label="Printed" value="PRINTED"/></el-select><el-button type="primary" @click="load">Search</el-button></div>
<el-table :data="rows" v-loading="loading" height="42vh" highlight-current-row stripe :row-class-name="rowClassName" :default-sort="{prop:'expenseDate',order:'ascending'}" @sort-change="handleSortChange" @row-click="select"><el-table-column prop="expenseNo" label="Document No." width="155" sortable="custom" :sort-orders="['ascending','descending']"/><el-table-column prop="expenseDate" label="Date" width="115" sortable="custom" :sort-orders="['ascending','descending']"/><el-table-column prop="accountName" label="Account" width="85"/><el-table-column prop="handlerName" label="Handler"/><el-table-column prop="totalAmount" label="Total Amount" width="120"/><el-table-column prop="createdByName" label="Created By"/><el-table-column label="Status" width="90"><template #default="s"><el-tag :type="s.row.status==='VOIDED'?'danger':s.row.status==='APPROVED'?'success':'info'">{{s.row.status==='VOIDED'?'Voided':s.row.status==='APPROVED'?'Approved':'Draft'}}</el-tag></template></el-table-column><el-table-column label="Print Status" width="120"><template #default="s"><el-tag :type="s.row.printedAt?'warning':'info'">{{s.row.printedAt?`Printed × ${s.row.printCount||1}`:'Not Printed'}}</el-tag></template></el-table-column><el-table-column label="Actions" width="290" fixed="right"><template #default="s"><el-button link type="primary" @click.stop="select(s.row)">Details</el-button><el-button v-if="s.row.status==='DRAFT'&&!s.row.printedAt" link type="primary" @click.stop="edit(s.row)">Edit</el-button><el-button v-if="s.row.status!=='VOIDED'" link type="primary" @click.stop="openPrintPreview(s.row)">Print Preview</el-button><el-button v-if="s.row.status==='DRAFT'" link type="success" @click.stop="approve(s.row)">Approve</el-button><el-button v-if="s.row.status==='DRAFT'&&!s.row.printedAt" link type="danger" @click.stop="voidExpense(s.row)">Void</el-button></template></el-table-column></el-table>
<section class="inline-detail"><div class="detail-title"><strong>{{detail?`Other Expense Document ${detail.expenseNo} Line Items`:'Click a document above to view details'}}</strong><span v-if="detail">Total ¥{{Number(detail.totalAmount).toFixed(2)}}</span></div><el-table v-if="detail" :data="detail.items" height="190" border><el-table-column prop="lineNo" label="Line No." width="70"/><el-table-column prop="categoryCode" label="Code" width="100"/><el-table-column prop="categoryName" label="Expense Category" width="210"/><el-table-column prop="summary" label="Summary"/><el-table-column prop="amount" label="Amount" width="130"/></el-table><el-empty v-else :image-size="54" description="Please select a document"/><div v-if="detail" class="audit-info"><span>Notes: {{detail.remark||'—'}}</span><span>Created By: {{detail.createdByName}} {{detail.createdAt}}</span><span>Updated By: {{detail.updatedByName}} {{detail.updatedAt}}</span><span>Approved By: {{detail.approvedByName||'—'}} {{detail.approvedAt||'—'}}</span><span>Printed By: {{detail.printedByName||'—'}} {{detail.printedAt||'—'}}</span><span v-if="detail.status==='VOIDED'">Void: {{detail.voidedByName||'—'}} {{detail.voidedAt||'—'}}</span><span v-if="detail.status==='VOIDED'">Void Reason: {{detail.voidReason||'—'}}</span></div></section></el-card>
<el-dialog v-model="dialog" :title="form.id?'Edit Other Expense':'Add Other Expense'" width="950px" destroy-on-close><el-form label-width="72px"><div class="header-form"><el-form-item label="Date"><el-date-picker v-model="form.expenseDate" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="Account"><el-input value="Cash" disabled/></el-form-item><el-form-item label="Handler"><el-select v-model="form.handlerEmployeeId" clearable filterable><el-option v-for="e in employees" :key="e.id" :label="e.name||e.employeeName" :value="e.id"/></el-select></el-form-item></div><el-table :data="form.items" border max-height="360"><el-table-column type="index" label="Line No." width="65"/><el-table-column label="Code / Expense Category" width="260"><template #default="s"><el-select v-model="s.row.categoryCode" filterable><el-option v-for="c in categories" :key="c.code" :label="`${c.code} ${c.name}`" :value="c.code"/></el-select></template></el-table-column><el-table-column label="Summary"><template #default="s"><el-input v-model="s.row.summary"/></template></el-table-column><el-table-column label="Amount" width="160"><template #default="s"><el-input-number v-model="s.row.amount" :min="0" :precision="2" :controls="false"/></template></el-table-column><el-table-column label="Actions" width="80"><template #default="s"><el-button link type="danger" @click="form.items.splice(s.$index,1)">Delete</el-button></template></el-table-column></el-table><el-button class="add-line" @click="addLine">Add Line Item</el-button><el-form-item label="Notes"><el-input v-model="form.remark"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">Cancel</el-button><el-button type="primary" :loading="saving" @click="save">Save</el-button></template></el-dialog>
<el-dialog v-model="printPreview" :title="`Other Expense DocumentPrint Preview ${detail?.expenseNo||''}`" width="900px" class="expense-print-dialog"><div v-if="detail" class="expense-print-area"><h2>OTHER EXPENSE DOCUMENT</h2><div class="print-meta"><span>Date: {{detail.expenseDate}}</span><span>Account: {{detail.accountName}}</span><span>Handler: {{detail.handlerName||'—'}}</span></div><el-table :data="detail.items" border><el-table-column prop="lineNo" label="Line No." width="70"/><el-table-column prop="categoryCode" label="Code" width="100"/><el-table-column prop="categoryName" label="Expense Category" width="210"/><el-table-column prop="summary" label="Summary"/><el-table-column prop="amount" label="Amount" width="130"/></el-table><div class="print-total">Total: ¥{{Number(detail.totalAmount).toFixed(2)}}</div><p>Notes: {{detail.remark||'—'}}</p></div><template #footer><el-button @click="printPreview=false">Close</el-button><el-button type="primary" :disabled="!detail||detail.status==='VOIDED'" @click="printExpense">Open System Print</el-button></template></el-dialog></div></template>
<style scoped>.page-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.page-heading h1{margin:0}.page-heading p{margin:6px 0 0;color:#6b7280}.filters{display:flex;gap:10px;align-items:center;margin-bottom:14px}.filters .el-input{max-width:300px}.filters .el-select{width:150px}.inline-detail{border-top:1px solid #dcdfe6;padding-top:10px}.detail-title{display:flex;justify-content:space-between;margin-bottom:8px}.audit-info{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px;color:#606266}.header-form{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.add-line{margin:10px 0}.expense-page :deep(.el-card__body){padding-bottom:10px}.expense-page :deep(.void-row td){color:#f56c6c!important;background:#fff1f0!important}.expense-print-area h2{text-align:center;letter-spacing:8px}.print-meta{display:flex;justify-content:space-between;margin-bottom:14px}.print-total{text-align:right;margin-top:14px;font-size:18px;font-weight:700}@media print{.page-heading,.filters,.expense-page>.el-card{display:none!important}.expense-print-dialog :deep(.el-dialog__header),.expense-print-dialog :deep(.el-dialog__footer){display:none}}</style>


