<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api'

const query=reactive({keyword:'',page:1,pageSize:20}),rows=ref<any[]>([]),total=ref(0),loading=ref(false),dialog=ref(false),editing=ref(false),importing=ref(false),categories=ref<any[]>([]),parentCategoryId=ref<number|null>(null)
const fileInput=ref<HTMLInputElement|null>(null)
const empty=()=>({id:0,skuCode:'',productName:'',specification:'',color:'',salesUnit:'pail',packageSpec:null as number|null,packageUnit:'',wholesalePrice:null as number|null,retailPrice:null as number|null,totalStock:0,stockLowerLimit:0,lastPurchasePrice:null as number|null,categoryId:null as number|null,version:0})
const form=reactive(empty())

const inventoryDialog=ref(false),inventoryLoading=ref(false),movementRows=ref<any[]>([]),movementTotal=ref(0),movementPage=ref(1),selectedProduct=ref<any>(null)
const adjustment=reactive({type:'INBOUND',quantity:null as number|null,reason:''})
const quantityLabel=computed(()=>adjustment.type==='ADJUSTMENT'?'Stock Count After Adjustment':'Change Quantity')
const quantityMin=computed(()=>adjustment.type==='ADJUSTMENT'?0:0.01)
const movementLabels:Record<string,string>={INBOUND:'Stock In',OUTBOUND:'Outbound',ADJUSTMENT:'Stock Count Adjustment',REVERSAL:'Reverse Dispatch'}

async function load(){loading.value=true;try{const{data}=await api.get('/products',{params:{...query,enabled:true}});rows.value=data.data.items;total.value=data.data.total}finally{loading.value=false}}
const childCategories=computed(()=>categories.value.find((x:any)=>x.id===parentCategoryId.value)?.children||[])
async function loadCategories(){const{data}=await api.get('/product-categories/tree');categories.value=data.data}
function search(){query.page=1;load()}
function add(){Object.assign(form,empty());parentCategoryId.value=null;editing.value=false;dialog.value=true}
function edit(row:any){Object.assign(form,row);parentCategoryId.value=row.parentCategoryId||null;if(!row.parentCategoryId)form.categoryId=null;editing.value=true;dialog.value=true}
function chooseParent(){form.categoryId=null}
async function save(){if(!form.skuCode.trim()||!form.productName.trim()||!form.salesUnit.trim())return ElMessage.warning('Code, product name, and unit are required');if(!parentCategoryId.value||!form.categoryId)return ElMessage.warning('Select a category and subcategory first');try{editing.value?await api.put(`/products/${form.id}`,form):await api.post('/products',form);ElMessage.success('Saved Successfully');dialog.value=false;load()}catch(e:any){ElMessage.error(e.response?.data?.message||'Save failed. Check the product code and category.')}}
async function disable(row:any){await ElMessageBox.confirm(`Disable product “${row.productName}”?`,'Confirm Disable',{type:'warning'});await api.patch(`/products/${row.id}/enabled`,{enabled:false,version:row.version});ElMessage.success('Disabled');load()}
function chooseCsv(){fileInput.value?.click()}
async function importCsv(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;importing.value=true;try{const body=new FormData();body.append('file',file);const{data}=await api.post('/products/import',body);const result=data.data;ElMessage.success(`Import complete: ${result.inserted} added, ${result.updated} updated, ${result.failed} failed`);if(result.errors?.length)await ElMessageBox.alert(result.errors.map((x:any)=>`Row ${x.row}: ${x.message}`).join('\n'),'Import Errors',{type:'warning'});await load()}finally{importing.value=false;input.value=''}}
function stockTag(row:any){return row.stockStatus==='NEGATIVE'||row.stockStatus==='SHORTAGE'?'danger':'success'}
function stockText(row:any){return row.stockStatus==='NEGATIVE'?'Negative Stock':row.stockStatus==='SHORTAGE'?'Shortage':'Normal'}

async function openInventory(row:any){selectedProduct.value=row;Object.assign(adjustment,{type:'INBOUND',quantity:null,reason:''});movementPage.value=1;inventoryDialog.value=true;await loadMovements()}
async function loadMovements(){if(!selectedProduct.value)return;inventoryLoading.value=true;try{const{data}=await api.get(`/products/${selectedProduct.value.id}/inventory-movements`,{params:{page:movementPage.value,pageSize:10}});movementRows.value=data.data.items;movementTotal.value=data.data.total}finally{inventoryLoading.value=false}}
async function submitAdjustment(){if(adjustment.quantity===null||adjustment.quantity<quantityMin.value)return ElMessage.warning(adjustment.type==='ADJUSTMENT'?'The stock count cannot be less than zero':'Enter a quantity greater than zero');if(!adjustment.reason.trim())return ElMessage.warning('Enter a reason for the change');try{await api.post(`/products/${selectedProduct.value.id}/inventory-adjustments`,adjustment);ElMessage.success('Inventory change saved');await load();selectedProduct.value=rows.value.find(x=>x.id===selectedProduct.value.id)||selectedProduct.value;adjustment.quantity=null;adjustment.reason='';movementPage.value=1;await loadMovements()}catch(e:any){ElMessage.error(e.response?.data?.message||'Inventory adjustment failed')}}
function signed(value:any){const n=Number(value);return n>0?`+${n}`:`${n}`}
function formatTime(value:string){return value?value.replace('T',' ').slice(0,19):''}
onMounted(()=>{loadCategories();load()})
</script>

<template>
  <section>
    <div class="page-heading"><div><h1>Products</h1><p>Maintain prices, minimum stock, and recent purchase prices. Inventory quantities are changed through inventory movements.</p></div><div><input ref="fileInput" type="file" accept=".csv,text/csv" hidden @change="importCsv"><el-button :loading="importing" @click="chooseCsv">Import Product CSV (does not change stock)</el-button><el-button type="primary" @click="add">Add Product</el-button></div></div>
    <el-card><div class="toolbar product-toolbar"><el-input v-model="query.keyword" clearable placeholder="Product Code / Name / Mnemonic" @keyup.enter="search"/><el-button type="primary" @click="search">Search</el-button></div>
      <el-table :data="rows" v-loading="loading" stripe><el-table-column prop="skuCode" label="Code" width="105"/><el-table-column prop="productName" label="Product Name" min-width="150"/><el-table-column prop="parentCategoryName" label="Category" width="100"/><el-table-column prop="categoryName" label="Subcategory" width="110"/><el-table-column prop="specification" label="Specification" width="105"/><el-table-column prop="color" label="Color" width="75"/><el-table-column prop="salesUnit" label="Unit" width="60"/><el-table-column label="Total Stock" width="90"><template #default="s"><span :class="Number(s.row.totalStock)<0?'negative-stock':''">{{s.row.totalStock}}</span></template></el-table-column><el-table-column prop="stockLowerLimit" label="Minimum Stock" width="90"/><el-table-column prop="shortageQuantity" label="Shortage Quantity" width="90"/><el-table-column prop="lastPurchasePrice" label="Recent Purchase Price" width="90"/><el-table-column prop="wholesalePrice" label="Wholesale Price" width="80"/><el-table-column label="Inventory Status" width="90"><template #default="s"><el-tag :type="stockTag(s.row)">{{stockText(s.row)}}</el-tag></template></el-table-column><el-table-column label="Actions" width="220" fixed="right"><template #default="s"><el-button link type="primary" @click="edit(s.row)">Edit</el-button><el-button link type="success" @click="openInventory(s.row)">Inventory Adjustments / Movements</el-button><el-button link type="danger" @click="disable(s.row)">Disable</el-button></template></el-table-column></el-table>
      <el-pagination v-model:current-page="query.page" :page-size="query.pageSize" :total="total" layout="total, prev, pager, next" @current-change="load"/>
    </el-card>
    <el-dialog v-model="dialog" :title="editing?'Edit Product':'Add Product'" width="760px"><el-form label-width="100px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="Category" required><el-select v-model="parentCategoryId" filterable placeholder="Select manufacturer/category" style="width:100%" @change="chooseParent"><el-option v-for="c in categories" :key="c.id" :label="`${c.code} ${c.name}`" :value="c.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="Subcategory" required><el-select v-model="form.categoryId" filterable placeholder="Select a product subcategory" style="width:100%" :disabled="!parentCategoryId"><el-option v-for="c in childCategories" :key="c.id" :label="`${c.code} ${c.name}`" :value="c.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="Product Code" required><el-input v-model="form.skuCode"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Product Name" required><el-input v-model="form.productName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Specification"><el-input v-model="form.specification"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Color"><el-input v-model="form.color"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Sales Unit" required><el-input v-model="form.salesUnit"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Package Size"><el-input-number v-model="form.packageSpec" :min="0"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Package Unit"><el-input v-model="form.packageUnit"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Total Stock"><el-input-number v-model="form.totalStock" :disabled="editing" :min="0" :precision="2"/><div v-if="editing" class="field-tip">Use the inventory adjustment feature to change stock.</div></el-form-item></el-col><el-col :span="12"><el-form-item label="Minimum Stock"><el-input-number v-model="form.stockLowerLimit" :min="0" :precision="2"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Recent Purchase Price"><el-input-number v-model="form.lastPurchasePrice" :min="0" :precision="2"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Wholesale Price"><el-input-number v-model="form.wholesalePrice" :min="0" :precision="2"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Retail Price"><el-input-number v-model="form.retailPrice" :min="0" :precision="2"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">Cancel</el-button><el-button type="primary" @click="save">Save</el-button></template></el-dialog>

    <el-dialog v-model="inventoryDialog" :title="`Inventory Management · ${selectedProduct?.skuCode || ''} ${selectedProduct?.productName || ''}`" width="900px">
      <el-alert :closable="false" :type="Number(selectedProduct?.totalStock)<0?'error':'info'" show-icon :title="Number(selectedProduct?.totalStock)<0?`Current Stock: ${selectedProduct?.totalStock} ${selectedProduct?.salesUnit||''}; Inventory Status: Negative stock. Verify purchase reductions, sales issues, and historical inventory.`:`Current Stock: ${selectedProduct?.totalStock ?? 0} ${selectedProduct?.salesUnit || ''}`"/>
      <el-form inline class="inventory-form">
        <el-form-item label="Type"><el-select v-model="adjustment.type" style="width:130px"><el-option label="Stock In" value="INBOUND"/><el-option label="Outbound" value="OUTBOUND"/><el-option label="Stock Count Adjustment" value="ADJUSTMENT"/></el-select></el-form-item>
        <el-form-item :label="quantityLabel"><el-input-number v-model="adjustment.quantity" :min="quantityMin" :precision="2"/></el-form-item>
        <el-form-item label="Reason"><el-input v-model="adjustment.reason" maxlength="500" placeholder="For example: purchase receipt, sample issue, or month-end stock count" style="width:260px"/></el-form-item>
        <el-form-item><el-button type="primary" @click="submitAdjustment">Save Change</el-button></el-form-item>
      </el-form>
      <el-divider content-position="left">Inventory Movements</el-divider>
      <el-table :data="movementRows" v-loading="inventoryLoading" stripe height="330"><el-table-column label="Type" width="100"><template #default="s">{{movementLabels[s.row.movementType]}}</template></el-table-column><el-table-column label="Change" width="90"><template #default="s"><span :class="Number(s.row.quantityChange)>0?'stock-in':'stock-out'">{{signed(s.row.quantityChange)}}</span></template></el-table-column><el-table-column prop="beforeQuantity" label="Before" width="90"/><el-table-column label="After" width="90"><template #default="s"><span :class="Number(s.row.afterQuantity)<0?'negative-stock':''">{{s.row.afterQuantity}}</span></template></el-table-column><el-table-column prop="referenceNo" label="Source Document" width="145"><template #default="s">{{s.row.referenceNo||'Manual Adjustment'}}</template></el-table-column><el-table-column prop="reason" label="Reason" min-width="180"/><el-table-column prop="operatorName" label="Operator" width="100"/><el-table-column label="Time" width="175"><template #default="s">{{formatTime(s.row.createdAt)}}</template></el-table-column></el-table>
      <el-pagination v-model:current-page="movementPage" :page-size="10" :total="movementTotal" layout="total, prev, pager, next" @current-change="loadMovements"/>
    </el-dialog>
  </section>
</template>

<style scoped>
.field-tip{margin-left:8px;color:#909399;font-size:12px}.inventory-form{margin-top:18px}.stock-in{color:#16a34a;font-weight:600}.stock-out,.negative-stock{color:#dc2626;font-weight:700}
</style>


