<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api'

const router=useRouter(),rows=ref<any[]>([]),total=ref(0),categories=ref<any[]>([]),suggestionGroups=ref<any[]>([]),selected=ref<any[]>([]),parentId=ref<number>(),categoryId=ref<number>(),loading=ref(false),running=ref(false)
const query=reactive({keyword:'',page:1,pageSize:50})
const children=()=>categories.value.find((x:any)=>x.id===parentId.value)?.children||[]
async function load(){loading.value=true;try{const[r,c,g]=await Promise.all([api.get('/product-classification/pending',{params:query}),api.get('/product-categories/tree'),api.get('/product-classification/suggestion-groups')]);rows.value=r.data.data.items;total.value=r.data.data.total;categories.value=c.data.data;suggestionGroups.value=g.data.data}finally{loading.value=false}}
function search(){query.page=1;load()}
function chooseParent(){categoryId.value=undefined}
async function autoClassify(){running.value=true;try{const{data}=await api.post('/product-classification/auto-classify');ElMessage.success(`Automatically Classified ${data.data.matched} records, including internal supplies ${data.data.internal} records`);await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'Automatic classification failed')}finally{running.value=false}}
async function confirm(){if(!selected.value.length)return ElMessage.warning('First select theClassifyProduct');const target=categoryId.value||parentId.value;if(!target)return ElMessage.warning('Select a manufacturer or product subcategory');try{const{data}=await api.post('/product-classification/confirm',{productIds:selected.value.map(x=>x.id),categoryId:target});ElMessage.success(`Confirmed ${data.data.updated} records`);selected.value=[];await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'Classification Failed')}}
async function acceptSuggestion(row:any){if(!row.suggestion)return;try{await api.post('/product-classification/confirm',{productIds:[row.id],categoryId:row.suggestion.id});ElMessage.success(`Classified As“${row.suggestion.name}”`);await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'Failed to apply suggestion')}}
async function confirmSuggestionGroup(group:any){try{await ElMessageBox.confirm(`SystemFound  ${group.count} recordsSuggested Category“${group.name}”Products Awaiting Classification.Confirm after will uniformly oneClassify, thisActionsnot will affect those withouthas suggestionProduct.`,'Apply System Suggestions in Batch',{type:'warning',confirmButtonText:`Confirm Classification ${group.count} records`,cancelButtonText:'Cancel'});const{data}=await api.post('/product-classification/confirm-suggestion',{categoryId:group.id});ElMessage.success(`Classify ${data.data.updated} recordsto“${group.name}”`);await load()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.response?.data?.message||'batchFailed to apply suggestion')}}
async function confirmAllMatches(){const keyword=query.keyword.trim(),target=categoryId.value||parentId.value;if(keyword.length<2)return ElMessage.warning('Enter a specific keyword of at least two characters');if(!target)return ElMessage.warning('Select a manufacturer or product subcategory');if(!total.value)return ElMessage.warning('No unclassified products match the current search');const parent=categories.value.find((x:any)=>x.id===parentId.value),child=children().find((x:any)=>x.id===categoryId.value),name=child?`${parent?.name} → ${child.name}`:parent?.name;try{await ElMessageBox.confirm(`Classify all ${total.value} results matching “${keyword}” as “${name}”. Make sure the keyword is specific enough.`,'Confirm Batch Classification',{type:'warning',confirmButtonText:'Confirm Classification',cancelButtonText:'Cancel'});const{data}=await api.post('/product-classification/confirm-matches',{keyword,categoryId:target});ElMessage.success(`Batch classified ${data.data.updated} records`);await load()}catch(e:any){if(e!=='cancel'&&e!=='close')ElMessage.error(e.response?.data?.message||'Batch classification failed')}}
onMounted(load)
</script>
<template><section><div class="page-heading"><div><h1>Products Awaiting Classification</h1><p>The system suggests only clear name matches. Review and confirm selections here to avoid assigning the wrong manufacturer.</p></div><div><el-button @click="router.push('/products')">Return to Find Products by Manufacturer</el-button><el-button type="primary" :loading="running" @click="autoClassify">Automatically Match Clear Products</el-button></div></div>
<el-alert title="Empty cans, drums, crates, and cartons are classified as internal supplies and cannot be added to sales orders" type="warning" :closable="false" show-icon/>
<el-card class="classify-card"><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="Enter a specific keyword, such as: epoxy primer" @keyup.enter="search"/><el-button @click="search">Find</el-button><span class="divider"/><el-select v-model="parentId" placeholder="Step 1: Select Manufacturer/Category" filterable @change="chooseParent"><el-option v-for="c in categories" :key="c.id" :value="c.id" :label="`${c.code} ${c.name}`"/></el-select><el-select v-model="categoryId" clearable placeholder="Step 2: Select Subcategory (Optional)" filterable><el-option v-for="c in children()" :key="c.id" :value="c.id" :label="`${c.code} ${c.name}`"/></el-select><el-button type="success" @click="confirm">Classify Selected ({{selected.length}})</el-button><el-button type="warning" plain @click="confirmAllMatches">Classify All Search Results ({{total}})</el-button></div>
<div v-if="suggestionGroups.length" class="suggestion-groups"><strong>System Suggestions Available for Batch Confirmation: </strong><span v-for="g in suggestionGroups" :key="g.id" class="suggestion-item"><el-tag type="warning" effect="plain">{{g.name}} {{g.count}} records</el-tag><el-button link type="primary" @click="confirmSuggestionGroup(g)">Apply in Batch</el-button></span></div><el-table :data="rows" v-loading="loading" stripe @selection-change="selected=$event"><el-table-column type="selection" width="48"/><el-table-column prop="skuCode" label="Code" width="130"/><el-table-column prop="productName" label="Product Name" min-width="260"/><el-table-column prop="salesUnit" label="Unit" width="70"/><el-table-column prop="totalStock" label="Inventory" width="90"/><el-table-column prop="lastPurchasePrice" label="Recent Purchase Price" width="100"/><el-table-column prop="wholesalePrice" label="Wholesale Price" width="90"/><el-table-column label="System Suggestion" width="210"><template #default="s"><template v-if="s.row.suggestion"><el-tag type="warning" effect="plain">{{s.row.suggestion.name}}</el-tag><el-button link type="primary" @click="acceptSuggestion(s.row)">Apply Suggestion</el-button></template><span v-else class="no-suggestion">No reliable suggestion</span></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :page-size="query.pageSize" :total="total" layout="total, prev, pager, next" @current-change="load"/></el-card></section></template>
<style scoped>.classify-card{margin-top:16px}.toolbar{display:flex;gap:10px;align-items:center;margin-bottom:14px;flex-wrap:wrap}.toolbar>.el-input{width:230px}.toolbar>.el-select{width:230px}.divider{width:1px;height:28px;background:#dcdfe6;margin:0 4px}.no-suggestion{color:#909399;font-size:13px}.suggestion-groups{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:0 0 14px;padding:10px 12px;background:#fff8e8;border:1px solid #f3d19e;border-radius:6px}.suggestion-item{display:inline-flex;align-items:center;gap:2px}</style>


