<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api'
const route=useRoute(),rows=ref<any[]>([]),total=ref(0),loading=ref(false),detail=ref(false),dialog=ref(false),editing=ref(false),current=ref<any>({}),options=reactive({types:[] as any[],departments:[] as any[]}),query=reactive({keyword:'',enabled:'',page:1,pageSize:20})
const empty=()=>({id:0,code:'',name:'',phone:'',mobile:'',fax:'',address:'',remark:'',plateNo:'',vehicleType:'',gender:'',employeeTypeId:null,departmentId:null,positionName:'',education:'',idCard:'',salesperson:false,hometown:'',postalCode:'',hireDate:'',version:0})
const form=reactive<any>(empty())
const simple=(title:string,singular:string)=>({title,singular,hint:`Search by ${singular.toLowerCase()} code, name, or notes`,columns:[['code',`${singular} Code`,160],['name',`${singular} Name`,240],['remark','Notes',320]],details:[['code',`${singular} Code`],['name',`${singular} Name`],['remark','Notes']]})
const configs:any={suppliers:{title:'Suppliers',singular:'Supplier',hint:'Search by supplier code, name, or phone',columns:[['code','Supplier Code',130],['name','Supplier Name',220],['phone','Phone',160],['mobile','Mobile',140],['address','Address',260]],details:[['code','Supplier Code'],['name','Supplier Name'],['phone','Phone'],['mobile','Mobile'],['fax','Fax'],['address','Address'],['remark','Notes']]},employees:{title:'Employees',singular:'Employee',hint:'Search by employee code, name, phone, type, or department',columns:[['code','Employee Code',120],['name','Employee Name',140],['typeName','Employee Type',140],['departmentName','Department',140],['positionName','Position',140],['phone','Phone',150]],details:[['code','Employee Code'],['name','Employee Name'],['gender','Gender'],['phone','Phone'],['typeName','Employee Type'],['departmentName','Department'],['positionName','Position'],['education','Education'],['idCard','National ID (Masked)'],['address','Address'],['hometown','Place of Origin'],['hireDate','Hire Date'],['remark','Notes']]},vehicles:{title:'Vehicles',singular:'Vehicle',hint:'Search by vehicle code, plate, or type',columns:[['code','Vehicle Code',140],['plateNo','License Plate',160],['vehicleType','Vehicle Type',180],['remark','Notes',260]],details:[['code','Vehicle Code'],['plateNo','License Plate'],['vehicleType','Vehicle Type'],['remark','Notes']]},'employee-types':simple('Employee Types','Category'),departments:simple('Departments','Department'),routes:simple('Routes','Route')}
const kind=computed(()=>String(route.meta.kind)),config=computed(()=>configs[kind.value])
const canManage=computed(()=>(localStorage.getItem('role')||'ADMIN')==='ADMIN')
async function load(){loading.value=true;try{const{data}=await api.get(`/reference-data/${kind.value}`,{params:{keyword:query.keyword,enabled:query.enabled===''?undefined:query.enabled,page:query.page,pageSize:query.pageSize}});rows.value=data.data.items;total.value=data.data.total}catch(e:any){ElMessage.error(e.response?.data?.message||'Failed to Load Data')}finally{loading.value=false}}
async function loadOptions(){if(kind.value!=='employees')return;const{data}=await api.get('/reference-data/employee-options');options.types=data.data.types;options.departments=data.data.departments}
function search(){query.page=1;load()} function show(row:any){current.value=row;detail.value=true}
function add(){Object.assign(form,empty());editing.value=false;dialog.value=true}
function edit(row:any){Object.assign(form,empty(),row,{idCard:''});editing.value=true;dialog.value=true}
async function save(){if(!form.code.trim()||(kind.value!=='vehicles'&&!form.name.trim()))return ElMessage.warning('Code and name are required');try{editing.value?await api.put(`/reference-data/${kind.value}/${form.id}`,form):await api.post(`/reference-data/${kind.value}`,form);ElMessage.success('Saved successfully');dialog.value=false;load()}catch(e:any){ElMessage.error(e.response?.data?.message||'Save failed. Check whether the code is duplicated.')}}
async function toggle(row:any){const action=row.enabled?'Disable':'Enable';await ElMessageBox.confirm(`${action} “${row.name||row.plateNo||row.code}”?`,`${action} Record`,{type:row.enabled?'warning':'info'});await api.patch(`/reference-data/${kind.value}/${row.id}/enabled`,{enabled:!row.enabled,version:row.version??0});ElMessage.success(`${action}d successfully`);load()}
async function remove(row:any){await ElMessageBox.confirm(`Permanently delete “${row.name||row.plateNo||row.code}”? This cannot be undone.`,'Confirm Permanent Deletion',{type:'error',confirmButtonText:'Delete Permanently'});try{await api.delete(`/reference-data/${kind.value}/${row.id}`);ElMessage.success('Deleted successfully');load()}catch(e:any){ElMessage.error(e.response?.data?.message||'This record is used by a business document and cannot be deleted. Disable it instead.')}}
watch(kind,()=>{Object.assign(query,{keyword:'',enabled:'',page:1,pageSize:20});load();loadOptions()},{immediate:true})
</script>
<template><section><div class="page-heading"><div><h1>{{config.title}}</h1><p>{{config.hint}}</p></div><el-button v-if="canManage" type="primary" @click="add">Add {{config.singular}}</el-button></div><el-card><div class="toolbar"><el-input v-model="query.keyword" clearable :placeholder="config.hint" @keyup.enter="search"/><el-select v-model="query.enabled" style="width:130px"><el-option label="All Statuses" value=""/><el-option label="Active" :value="true"/><el-option label="Disabled" :value="false"/></el-select><el-button type="primary" @click="search">Search</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column v-for="c in config.columns" :key="c[0]" :prop="c[0]" :label="c[1]" :width="c[2]" show-overflow-tooltip/><el-table-column v-if="kind==='employees'" label="Salesperson" width="80"><template #default="s">{{s.row.salesperson?'Yes':'No'}}</template></el-table-column><el-table-column label="Status" width="90"><template #default="s"><el-tag :type="s.row.enabled?'success':'info'">{{s.row.enabled?'Active':'Disabled'}}</el-tag></template></el-table-column><el-table-column label="Actions" :width="canManage?220:80" fixed="right"><template #default="s"><el-button link type="primary" @click="show(s.row)">View</el-button><template v-if="canManage"><el-button link type="primary" @click="edit(s.row)">Edit</el-button><el-button link :type="s.row.enabled?'warning':'success'" @click="toggle(s.row)">{{s.row.enabled?'Disable':'Restore'}}</el-button><el-button link type="danger" @click="remove(s.row)">Delete</el-button></template></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :page-size="query.pageSize" :total="total" layout="total, prev, pager, next" @current-change="load"/></el-card>
<el-drawer v-model="detail" :title="config.title+' Details'" size="480px"><el-descriptions :column="1" border><el-descriptions-item v-for="d in config.details" :key="d[0]" :label="d[1]">{{current[d[0]]||'—'}}</el-descriptions-item><el-descriptions-item v-if="kind==='employees'" label="Salesperson">{{current.salesperson?'Yes':'No'}}</el-descriptions-item><el-descriptions-item label="Status"><el-tag :type="current.enabled?'success':'info'">{{current.enabled?'Active':'Disabled'}}</el-tag></el-descriptions-item></el-descriptions></el-drawer>
<el-dialog v-model="dialog" :title="(editing?'Edit ':'Add ')+config.singular" width="680px"><el-form label-width="100px"><el-row :gutter="16"><el-col :span="12"><el-form-item label="Code" required><el-input v-model="form.code"/></el-form-item></el-col><el-col v-if="kind!=='vehicles'" :span="12"><el-form-item label="Name" required><el-input v-model="form.name"/></el-form-item></el-col>
<template v-if="kind==='suppliers'"><el-col :span="12"><el-form-item label="Phone"><el-input v-model="form.phone"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Mobile"><el-input v-model="form.mobile"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Fax"><el-input v-model="form.fax"/></el-form-item></el-col><el-col :span="24"><el-form-item label="Address"><el-input v-model="form.address"/></el-form-item></el-col></template>
<template v-if="kind==='vehicles'"><el-col :span="12"><el-form-item label="License Plate"><el-input v-model="form.plateNo"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Vehicle Type"><el-input v-model="form.vehicleType"/></el-form-item></el-col></template>
<template v-if="kind==='employees'"><el-col :span="12"><el-form-item label="Phone"><el-input v-model="form.phone"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Gender"><el-select v-model="form.gender" clearable><el-option label="Male" value="Male"/><el-option label="Female" value="Female"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="Employee Types"><el-select v-model="form.employeeTypeId" clearable><el-option v-for="o in options.types" :key="o.id" :label="o.name" :value="o.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="Department"><el-select v-model="form.departmentId" clearable><el-option v-for="o in options.departments" :key="o.id" :label="o.name" :value="o.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="Position"><el-input v-model="form.positionName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Hire Date"><el-date-picker v-model="form.hireDate" value-format="YYYY-MM-DD" type="date"/></el-form-item></el-col><el-col :span="12"><el-form-item label="National ID"><el-input v-model="form.idCard" :placeholder="editing?'Leave blank to keep the original number':''"/></el-form-item></el-col><el-col :span="12"><el-form-item label="Salesperson"><el-switch v-model="form.salesperson"/></el-form-item></el-col><el-col :span="24"><el-form-item label="Address"><el-input v-model="form.address"/></el-form-item></el-col></template>
<el-col :span="24"><el-form-item label="Notes"><el-input v-model="form.remark" type="textarea"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">Cancel</el-button><el-button type="primary" @click="save">Save</el-button></template></el-dialog></section></template>


