<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api } from '../api'
const rows=ref<any[]>([]),total=ref(0),loading=ref(false),dialog=ref(false),resetDialog=ref(false),editing=ref(false),query=reactive({keyword:'',page:1,pageSize:20})
const empty=()=>({id:0,username:'',displayName:'',role:'SALES',password:'',version:0}),form=reactive<any>(empty()),passwordForm=reactive({id:0,password:'',version:0})
const roles=[['ADMIN','Administrator'],['SALES','Salesperson'],['WAREHOUSE','Warehouse Staff'],['DISPATCH','Dispatch Staff']],roleName=(v:string)=>roles.find(r=>r[0]===v)?.[1]||v
async function load(){loading.value=true;try{const{data}=await api.get('/users',{params:query});rows.value=data.data.items;total.value=data.data.total}finally{loading.value=false}}
function search(){query.page=1;load()} function add(){Object.assign(form,empty());editing.value=false;dialog.value=true} function edit(row:any){Object.assign(form,empty(),row);editing.value=true;dialog.value=true}
async function save(){if(!form.username&&!editing.value)return ElMessage.warning('Enter a username');if(!form.displayName)return ElMessage.warning('Enter a display name');try{editing.value?await api.put(`/users/${form.id}`,form):await api.post('/users',form);ElMessage.success('Saved successfully');dialog.value=false;load()}catch(e:any){ElMessage.error(e.response?.data?.message||'Save failed. Check the username and password format.')}}
async function toggle(row:any){const action=row.enabled?'disable':'restore';await ElMessageBox.confirm(`Are you sure you want to ${action} “${row.displayName}”?`,`Confirm ${action}`,{type:'warning'});try{await api.patch(`/users/${row.id}/enabled`,{enabled:!row.enabled,version:row.version});ElMessage.success(row.enabled?'Account disabled successfully':'Account restored successfully');load()}catch(e:any){ElMessage.error(e.response?.data?.message||'Action failed')}}
function reset(row:any){Object.assign(passwordForm,{id:row.id,password:'',version:row.version});resetDialog.value=true} async function savePassword(){try{await api.patch(`/users/${passwordForm.id}/password`,passwordForm);ElMessage.success('Password reset. A password change is required at the next sign-in.');resetDialog.value=false;load()}catch(e:any){ElMessage.error(e.response?.data?.message||'The password must be at least 8 characters and include both letters and numbers.')}}
async function unlock(row:any){await ElMessageBox.confirm(`Are you sure you want to unlock “${row.displayName}”?`,'Confirm unlock',{type:'warning'});try{await api.patch(`/users/${row.id}/unlock`,{version:row.version});ElMessage.success('Account unlocked');load()}catch(e:any){ElMessage.error(e.response?.data?.message||'Unlock failed')}}
onMounted(load)
</script>
<template><section><div class="page-heading"><div><h1>User Accounts</h1><p>Create internal accounts, assign roles, disable or unlock accounts, and reset passwords</p></div><el-button type="primary" @click="add">Add Account</el-button></div><el-card><div class="toolbar"><el-input v-model="query.keyword" clearable placeholder="Username / Name / Role" @keyup.enter="search"/><el-button type="primary" @click="search">Search</el-button></div><el-table :data="rows" v-loading="loading" stripe><el-table-column prop="username" label="Username" width="170"/><el-table-column prop="displayName" label="Display Name" width="160"/><el-table-column label="Role" width="120"><template #default="s">{{roleName(s.row.role)}}</template></el-table-column><el-table-column label="Sign-in Security" width="190"><template #default="s"><el-tag v-if="s.row.locked" type="danger">Locked (10 Failed Attempts)</el-tag><el-tag v-else-if="!s.row.enabled" type="info">Disabled</el-tag><el-tag v-else-if="s.row.mustChangePassword" type="warning">Password Change Required at First Sign-in</el-tag><el-tag v-else type="success">Normal</el-tag><small v-if="!s.row.locked&&s.row.failedLoginAttempts" class="attempts">Incorrect Attempts: {{s.row.failedLoginAttempts}}</small></template></el-table-column><el-table-column prop="updatedAt" label="Last Updated" min-width="185"/><el-table-column label="Actions" width="305"><template #default="s"><el-button link type="primary" @click="edit(s.row)">Edit</el-button><el-button link type="primary" @click="reset(s.row)">Reset Password</el-button><el-button v-if="s.row.locked" link type="warning" @click="unlock(s.row)">Unlock</el-button><el-button link :type="s.row.enabled?'danger':'success'" @click="toggle(s.row)">{{s.row.enabled?'Disable':'Restore'}}</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :page-size="query.pageSize" :total="total" layout="total, prev, pager, next" @current-change="load"/></el-card>
<el-dialog v-model="dialog" :title="editing?'Edit Account':'Add Account'" width="520px"><el-form label-width="90px"><el-form-item v-if="!editing" label="Username" required><el-input v-model="form.username" maxlength="64" placeholder="letters, numbers, periods, hyphens, or underscores"/></el-form-item><el-form-item label="Display Name" required><el-input v-model="form.displayName" maxlength="100"/></el-form-item><el-form-item label="Role" required><el-select v-model="form.role"><el-option v-for="r in roles" :key="r[0]" :value="r[0]" :label="r[1]"/></el-select></el-form-item><el-form-item v-if="!editing" label="Initial Password" required><el-input v-model="form.password" type="password" show-password placeholder="At least 8 characters including letters and numbers"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">Cancel</el-button><el-button type="primary" @click="save">Save</el-button></template></el-dialog>
<el-dialog v-model="resetDialog" title="Reset Password" width="460px"><el-alert title="After reset, this account must change its password at the next sign-in." type="warning" :closable="false"/><el-form label-width="90px" style="margin-top:18px"><el-form-item label="New Password" required><el-input v-model="passwordForm.password" type="password" show-password placeholder="At least 8 characters including letters and numbers"/></el-form-item></el-form><template #footer><el-button @click="resetDialog=false">Cancel</el-button><el-button type="primary" @click="savePassword">Confirm Reset</el-button></template></el-dialog></section></template>
<style scoped>.attempts{display:block;color:#c45656;margin-top:4px}</style>


